<section class="content">
    <div class="box box-default admin_form_bg">
<?php if($this->flashMessenger()->hasCurrentErrorMessages()){?>
        <div class="box box-solid alert-error">
            <div class="box-tools pull-right">
                <button data-widget="remove" class="btn btn-box-tool text-gray"><i class="fa fa-times"></i></button>                    
            </div>
            <div class="box-body"><?php echo $this->flashMessenger()->render('error');?></div>
        </div>
<?php }?>
        <form role="form" data-toggle="validator" class="form-horizontal register_employer_form" method="post" enctype="multipart/form-data">
            <h1 class="page-heading border-bottom">Edit Article</h1>
            <div class="form-group">
                <label class="col-sm-2 col-md-2 control-label">Category:</label>
                <div class="col-sm-10 col-md-10">
                    <div class="check_box_scroller_container">
<?php               foreach($this->cats as $cat){?>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" id="checkboxSuccess" name="cat[]" value="<?php echo $cat["id"];?>" <?php echo (in_array($cat["id"],$catsSelected))?'checked':'';?> />
                                <?php echo $cat["title"];?>
                            </label>
                        </div>
<?php               }?>
                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="form-group">
                <label for="title" class="col-sm-2 col-md-2 control-label">Article Title:</label>
                <div class="col-sm-5 col-md-5">
                    <input type="text" class="form-control" value="<?php echo $this->article->title;?>" name="title" placeholder="Article Title" required />
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 col-md-2 control-label">Article Description:</label>
                <div class="col-sm-10 col-md-10">
                    <textarea id="description" name="description" rows="10" cols="80"><?php echo $this->article->description;?></textarea>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="form-group">
                <label for="article-image" class="col-sm-2 col-md-2 control-label">Article Image:</label>
                <div class="col-sm-5 col-md-5">
                    <input type="file" id="article-image" name="article-image" />                
                </div>
                <div class="col-sm-10 col-md-10">
                    <img width="50" src="<?php echo ($this->article->article_image!=NULL)?$this->basepath('/images/article/'.$this->article->article_image):$this->basepath('/img/default.jpg');?>" alt="Article Image" title="Article Image" />
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 col-md-2 control-label">Is Active?</label>
                <div class="col-sm-5 col-md-5">
                    <label>
                        <input type="radio" name="status" value="1" class="minimal" <?php echo ($this->article->status=="1") ? 'checked' : '';?> />Yes
                    </label>
                    <label>
                        <input type="radio" name="status" value="0" class="minimal" <?php echo ($this->article->status=="0") ? 'checked' : '';?> />No
                    </label>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="form-group">
                <div class=" col-xs-12 col-sm-6 col-md-6 col-sm-offset-2 col-md-offset-2 btn_submit">
                    <button type="submit" class="btn btn-primary pull-left">Update</button>&nbsp;
                    <a class="btn btn-default" href="<?php echo $this->serverUrl()."/admin/article";?>" role="button">Back</a>
                </div>
            </div>
            <div class="clearfix"></div>
        </form>
    </div>
</section>
<script>
    $(function(){
        $("[data-mask]").inputmask();
        CKEDITOR.replace('description');

        //iCheck for checkbox and radio inputs
        $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
            checkboxClass: 'icheckbox_minimal-blue',
            radioClass: 'iradio_minimal-blue'
        });
    });
</script>