<?php use Carbon\Carbon;?>
<section class="content">
    <div class="box box-default">
        <div class="box-header with-border">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <h1 class="pull-left page-heading">Featured Articles</h1>
                    <div class="pull-right">
                        <div class="btn-group">
                            <a class="btn btn-success" href="<?php echo "/admin/article/add";?>" ><i class="fa fa-plus"></i> Add New</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="box-body">
<?php   if($this->flashMessenger()->hasCurrentSuccessMessages()){?>
            <div class="box box-success box-solid alert-success">
                <div class="box-tools pull-right">
                    <button data-widget="remove" class="btn btn-box-tool text-gray"><i class="fa fa-times"></i></button>
                </div>
                <div class="box-body"><?php echo $this->flashMessenger()->setMessageOpenFormat('<strong>')->setMessageCloseString('</strong>')->render('success');?></div>
            </div>
<?php   }?>
            <table id="articles" class="table table-bordered table-striped table-condensed">
                <thead>
                    <th>SN.</th>
                    <th>Title</th>
                    <th>Status</th>
                    <th>Modified By</th>
                    <th>Created at</th>
                    <th>Updated at</th>
                    <th>Action</th>
                </thead>
                <tbody>
<?php           foreach($this->articles as $key=>$article):?>
                    <tr>
                        <td><?php echo $key+1;?></td>
                        <td><?php echo $article["title"];?></td>
                        <td><?php echo ($article["status"]==1)?"Active":"Inactive";?></td>
                        <td><?php echo $article["full_name"]; ?></td>
                        <td>
<?php
                            $dt=Carbon::createFromFormat('Y-m-d H:i:s',$article["created_at"]);
                            echo $dt->toFormattedDateString();
?>
                        </td>
                         <td>
<?php
                            $dt=Carbon::createFromFormat('Y-m-d H:i:s',$article["updated_at"]);
                            echo $dt->toFormattedDateString();
?>
                        </td>
                        
                        <td>
                            <div class="btn-group">
                                <a class="btn btn-success btn-xs" href='<?php echo "/articleDetails/".$article["id"];?>' target="_blank"><i class="fa fa-eye"></i> Preview </a>
                                <a class="btn btn-primary btn-xs" href='<?php echo "/admin/article/edit/".$article["id"];?>' target="_blank"><i class="fa fa-edit"></i> Edit</a>
                                <form method="POST" action="<?php echo "/admin/article/delete/".$article["id"];?>" accept-charset="UTF-8" style="display:inline">
                                    <button style="border-bottom-left-radius:0;border-top-left-radius:0;" class="btn btn-xs btn-danger" type="button" data-toggle="modal" data-target="#confirmDelete" data-title="Delete Article" data-message="Are you sure you want to delete this article ?">
                                        <i class="glyphicon glyphicon-trash"></i> Delete
                                    </button>
                                </form>
                            </div>
                        </td>
                    </tr>
<?php           endforeach;?>
                </tbody>
                <tfoot>
                    <th>SN.</th>
                    <th>Title</th>
                    <th>Status</th>
                    <th>Modified By</th>
                    <th>Created at</th>
                    <th>Updated at</th>
                </tfoot>
            </table>
        </div>
    </div>
</section>
<script>
    $(document).ready(function(){
        $('#articles').dataTable();
    });
</script>