<section class="content">
    <div class="box box-primary">
        <div class="box-header">
            <h1 class="page-heading border-bottom">Add Membership Type</h1>
        </div><!-- /.box-header -->
        <!-- form start -->
        <form role="form" data-toggle="validator" method="post">
            <div class="box-body">
<?php       if(count($error_messages)){?>
                <div class="box box-solid alert-error">
                    <div class="box-tools pull-right">
                        <button data-widget="remove" class="btn btn-box-tool text-gray"><i class="fa fa-times"></i></button>                    
                    </div>
                    <div class="box-body">
<?php
                    foreach($error_messages as $msg)
                        echo $msg;
?>
                    </div>
                </div>
<?php       }?>
                <div class="form-group">
                    <label for="mName"> Membership Name </label><span class="valid_star">*</span>
                    <input name="mtname" type="text" id="mName" value="<?php echo ($this->post_data->mtname ? $this->post_data->mtname : "");?>" placeholder="Type Name" class="form-control" autofocus required>
                    <div id="mName-check"></div>
                </div>
                <div class="form-group">
                    <label for="mDesc">Description</label><span class="valid_star">*</span>
                    <textarea name="description" id="mDesc" placeholder="Type Description" rows="3" class="form-control" required><?php echo ($this->post_data->description ? $this->post_data->description : "");?></textarea>
                </div>
            </div><!-- /.box-body -->

            <div class="box-footer">
                <button class="btn btn-primary" type="submit">Add</button>
                <a class="btn btn-default" href="<?php echo $this->serverUrl()."/admin/mtype";?>" role="button">Back</a>
            </div>
        </form>
    </div>
</section>
<script type="text/javascript">
    $(function(){
        $("#mName").focusout(function(e){
            var postData=$("#mName").val();
            if(postData!==""){
                var URL="/admin/mtype/mtypecheck";
                $.ajax({
                    url:URL,
                    type:"POST",
                    data:{mName:postData},
                    success:function(data,textStatus,jqXHR){
                        $("#mName-check").show();
                        if(data.success){
                            $("#mName-check").css("color","red");
                            $("#mName-check").html("This Membership Type already exists");
                            e.preventDefault();
                        }
                        if(!data.success){
                            $("#mName-check").css("color","green");
                            $("#mName-check").html("Membership Type available");
                        }
                    }
                });
                e.preventDefault();
            }else
                $("#mName-check").hide();
        });
    });
</script>