<div class="box box-primary">
    <div class="box-header">
        <h1 class="page-heading border-bottom">Edit Member Type</h1>
    </div><!-- /.box-header -->
    <!-- form start -->
    <form role="form" data-toggle="validator" method="post">
        <div class="box-body">
            <div class="form-group">
                <label for="mName"> Membership Name </label><span class="valid_star">*</span>
                <input name="mtname" type="text" id="mName" value="<?php echo $this->mtypes->name; ?>" placeholder="Type Name" class="form-control" autofocus required>
            </div>
            <div class="form-group">
                <label for="mDesc">Description</label><span class="valid_star">*</span>
                <textarea name="description" id="mDesc" placeholder="Type Description" rows="5" cols="10" class="form-control" required><?php echo $this->mtypes->description; ?></textarea>
            </div>            
        </div><!-- /.box-body -->

        <div class="box-footer">
            <button class="btn btn-primary" type="submit">Update</button>
            <a class="btn btn-default" href="<?php echo $this->serverUrl()."/admin/mtype";?>" role="button">Back</a>
        </div>
    </form>
</div>