<?php use Carbon\Carbon; ?>
<section class="content">

    <!-- Default box -->
    <div class="box box-default">
        <div class="box-header with-border">
            
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <h1 class="pull-left page-heading">Membership Type</h1>
                    <div class="pull-right">
                        <div class="btn-group">
                            <a class="btn btn-success"  href="<?php echo "/admin/mtype/add"; ?>" ><i class="fa fa-plus"></i> Add New</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="box-body">           
         
        <?php
        if ($this->flashMessenger()->hasCurrentSuccessMessages()) {
            ?>
            <div class="box box-success box-solid alert-success">
                <div class="box-tools pull-right">
                    <button data-widget="remove" class="btn btn-box-tool text-gray"><i class="fa fa-times"></i></button>                    
                </div><!-- /.box-tools -->

                <div class="box-body">
                    <?php
                    //$flashMessenger = $this->flashMessenger();
                    //if ($flashMessenger->hasMessages()) {     
                    echo $this->flashMessenger()
                            ->setMessageOpenFormat('<strong>')
                            ->setMessageCloseString('</strong>')
                            ->render('success');
                    //} 
                    ?> 
                </div><!-- /.box-body -->
            </div><!-- /.box -->
            <?php
        }
        if ($this->flashMessenger()->hasCurrentErrorMessages()) {
            ?>
            <div class="box box-danger box-solid alert-danger">
                <div class="box-tools pull-right">
                    <button data-widget="remove" class="btn btn-box-tool text-gray"><i class="fa fa-times"></i></button>                    
                </div><!-- /.box-tools -->

                <div class="box-body">
                    <?php
                    //$flashMessenger = $this->flashMessenger();
                    //if ($flashMessenger->hasMessages()) {     
                    echo $this->flashMessenger()
                            ->setMessageOpenFormat('<strong>')
                            ->setMessageCloseString('</strong>')
                            ->render('error');
                    //} 
                    ?> 
                </div><!-- /.box-body -->
            </div><!-- /.box -->
            <?php
        }
        ?>

            <table id="example1" class="table table-bordered table-striped table-condensed">
                <thead>
                    <tr>
                        <th>SN.</th>
                        <th>Membership Type </th>
                        <th>Modified By </th>                        
                        <th>Updated at </th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->mtypes as $key=>$mtype): ?>
                        <tr>
                            <td><?php echo $key+1;?></td>
                            <td><?php echo $mtype['name']; ?></td>
                            <td><?php echo $mtype['full_name']; ?></td>                            
                            <td>
                              <?php
                                $dt = Carbon::createFromFormat('Y-m-d H:i:s',$mtype['updated_at']);
                                echo $dt->toFormattedDateString();
                              ?>
                            </td>
                            
                            <td>
                                <div class="btn-group">
                                    <a class="btn btn-primary btn-xs" href='<?php echo "/admin/mtype/edit/".$mtype['id'];?>' target="_blank"><i class="fa fa-edit"></i> Edit</a>
                                    <!--<a class="btn btn-danger btn-xs" href="#"><i class="fa fa-remove"></i> Delete</a>-->
                                    <form method="POST" action="<?php echo "/admin/mtype/delete/".$mtype['id'];?>" accept-charset="UTF-8" style="display:inline">
                                        <button style="border-bottom-left-radius:0;border-top-left-radius:0;" class="btn btn-xs btn-danger" type="button" data-toggle="modal" data-target="#confirmDelete" data-title="Delete Membership Type" data-message="Are you sure you want to delete this type ?">
                                            <i class="glyphicon glyphicon-trash"></i> Delete
                                        </button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach; ?>

                </tbody>
                <tfoot>
                    <tr>
                        <th>SN.</th>
                        <th>Membership Type </th>
                        <th>Modified By </th>
                        <th>Updated at </th>
                        <th>Action</th>
                    </tr>
                </tfoot>
            </table>
        </div><!-- /.box-body -->

    </div><!-- /.box -->

</section><!-- /.content -->

<script type="text/javascript">

    var objectId;
    $(function() {
        //$("#example1").dataTable();
         $('#example1').dataTable();
    });
</script>
