<div class="col-xs-12 col-sm-12 col-md-12 category_dtls_page_top_container">   
    <div class="col-xs-12 col-sm-10 col-md-10">
        <h2>Sorry !!! This Job  Is Not Available!</h2> 
        <!--<p>Choose from 8,973 jobs. Let employers find you online. Receive matching jobs by email.
            Easy and 100% free!</p>-->
    </div>

    <div class="col-xs-12 col-sm-2 col-md-2">
        
    </div>
</div>
