<?php

use Carbon\Carbon;
?>
<div class="hidden-xs common_google_ads t1-position-ad">
    <div class="row">
        <!-- /85406138/Chakri_Jobdetails_T1_970x90 -->
        <div id='div-gpt-ad-1440660280027-0'>
            <script type='text/javascript'>
                googletag.cmd.push(function() {
                    googletag.display('div-gpt-ad-1440660280027-0');
                });
            </script>
        </div>
        <!-- /85406138/Chakri_Jobdetails_T1_970x90 -->

    </div>
</div>

<div class="col-xs-12 col-sm-8 col-md-8 job_details_left_container">     
    <div class="row">
        <?php if ($this->flashMessenger()->hasCurrentSuccessMessages()) { ?>
            <div class="box box-success box-solid alert alert-success alert-dismissable col-xs-12 col-sm-10 col-md-12">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <?php echo strip_tags($this->flashMessenger()->render('success', array('alert', 'alert-dismissable', 'alert-success'))); ?>
            </div>
            <?php
        }
        if ($this->flashMessenger()->hasCurrentErrorMessages()) {
            ?>
            <div class="box box-danger box-solid alert alert-danger alert-dismissable col-xs-12 col-sm-10 col-md-12">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <?php echo strip_tags($this->flashMessenger()->render('error', array('alert', 'alert-dismissable', 'alert-success'))); ?>
            </div>
        <?php } ?>
        <div class="col-xs-12 col-sm-10 col-md-10">
            <h3 class="dtls_job_title"><?php echo $this->job->job_title; ?> </h3>
            <h4 class="dtls_company_name">
                <?php
                if ($this->job->show_company_status == "No") {
                    echo $this->job->full_name;
                } else {
                    echo $this->job->hidden_company_name;
                }
                ?>   
            </h4>

            <?php if (!empty($this->job->job_experienced)) { ?>
                <p class="dtls_experience"><?php echo $this->job->job_experienced; ?> yrs</p> 
            <?php }
            ?>

            <?php if (!empty($this->job_location)) { ?>
                <p class="dtls_company_location"><?php echo $this->job_location; ?></p>
            <?php }
            ?>

            <div class="clearfix"></div>
            <?php
            if ($this->identity()) {
                if (($this->identity()->user_type == 3) && ($this->job->online_cv_received != "")) {
                    if ($job_status[0]["app_status"] == "apply") {
                        ?>
                        <div class="dtls_login_btn_container">
                            <a data-id="<?php echo $id; ?>"  id="already_apply_job"  href="javascript:void(0);" class="btn btn-primary dtls_login" role="button">Apply</a>                    
                        </div>      
                        <?php
                    } else {
                        ?>
                        <div class="dtls_login_btn_container">
                            <a data-id="<?php echo $id; ?>"  id="apply_job"  href="javascript:void(0);" class="btn btn-primary dtls_login" role="button">Apply</a>                    
                        </div>
                        <?php
                    }
                }
            } else {
                if ($this->job->online_cv_received != "") {
                    ?>
                    <div class="dtls_login_btn_container">
                        <a href="javascript:void(0);" data-type="apply" class="col-xs-12 col-sm-4 col-md-6 btn btn-primary dtls_login" role="button">Login to Apply</a>
                        <a href="/registration" class="col-xs-12 col-sm-6 col-md-5 btn btn-primary dtls_registar" role="button">Registrar and Apply</a>
                        <div class="clearfix"></div>
                    </div> 

                    <?php
                }
            }
            ?>


        </div>

        <div class="col-xs-12 col-sm-2 col-md-2">            
            <?php
            if (($this->company["company_logo"] != "") && ($this->job->show_company_status == "No")) {
                ?>
                <img src="<?php echo '/upload/client/' . $this->company["company_logo"]; ?>" alt="" class="job_dtls_company_logo img-responsive">

                <?php
            }
            ?>
        </div>

        <div class="clearfix"></div>
    </div>


    <div class="col-xs-12 col-sm-12 col-md-12 dtls_save_full_container"> 
        <div class="row">
            <div class="col-xs-12 col-sm-1 col-md-1 dtls_save_sprtr">
                <?php
                if ($this->identity()) {
                    if (($this->identity()->user_type == 3)) {


                        //print_r ($job_status);
                        //exit ();

                        if ($job_status[0]["app_status"] == "apply") {
                            ?>
                            <a data-type="save"  id="already_apply_job"  href="javascript:void(0);" title="Save this job">
                                <img src="<?php echo $this->basePath('/images/trans.png'); ?>" alt="saved jobs" class="dtls_saved_jobs_icon_saved">
                            </a>
                            <?php
                        } elseif ($job_status[0]["app_status"] == "save") {
                            ?>
                            <a data-type="save"  id="already_save_job"  href="javascript:void(0);" title="Save this job">
                                <img src="<?php echo $this->basePath('/images/trans.png'); ?>" alt="saved jobs" class="dtls_saved_jobs_icon_saved">
                            </a>
                            <?php
                        } else {
                            ?>
                            <a data-id="<?php echo $id; ?>"  id="save_job" data-type="save" href="javascript:void(0);" title="Save this job">
                                <img src="<?php echo $this->basePath('/images/trans.png'); ?>" alt="saved jobs" id="save_jobs_img" class="dtls_saved_jobs_ic">
                            </a>
                            <?php
                        }
                    }
                } else {
                    ?>
                    <a data-id="<?php echo $id; ?>" data-type="save"  class="login_to_apply" href="javascript:void(0);" title="Save this job">
                        <img src="<?php echo $this->basePath('/images/trans.png'); ?>" alt="saved jobs" id="save_jobs_img" class="dtls_saved_jobs_ic">
                    </a>
                    <?php
                }
                ?>


            </div>
            <div class="col-xs-12 col-sm-3 col-md-3 dtls_save_sprtr no_right_padding">
                <p>Total Job Opening's:<span class="dtls_total_job"> <?php echo $company_job_count; ?> </span></p>
            </div>
            <div class="col-xs-12 col-sm-4 col-md-4 dtls_save_sprtr">
                <p>Job Posted:<span class="dtls_date_posted_job">
                        <?php
                        if ($this->job->posting_date != NULL) {
                            $carbon_start_dt = Carbon::createFromFormat('Y-m-d', $this->job->posting_date);
                            echo $carbon_start_dt->toFormattedDateString();
                        }
//echo $this->job->posting_date_diff; 
                        ?> </span></p>
            </div>

            <div class="col-xs-12 col-sm-4 col-md-4 ">
                <p>Job Deadline:<span class="dtls_date_posted_job">
                        <?php
                        if ($this->job->job_deadline != NULL) {
                            $carbon_end_dt = Carbon::createFromFormat('Y-m-d', $this->job->job_deadline);
                            echo $carbon_end_dt->toFormattedDateString();
                        }
//echo $this->job->posting_date_diff; 
                        ?> </span></p>
            </div>

            <div class="clearfix"></div>
        </div>
    </div>

    <!-- End of dtls_save_full_container -->

    <div class="col-xs-12 col-sm-12 col-md-12 dtls_save_btom_container">
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-6 dtls_job_share_container pull-right">
                <div class="addinto_sharebox">
                    <div class="social_buttons">                   

                        <a class="addinto_button_linkedin"><img id="linkedin" src="<?php echo $this->basePath('/images/trans.png'); ?>" alt="Linked in" class="dtls_share_icon"></a> 
                        <a class="addinto_button_twitter"><img id="twitter" src="<?php echo $this->basePath('/images/trans.png'); ?>" alt="Twitter" class="dtls_share_icon"></a>
                        <a class="addinto_button_facebook"><img id="facebook" src="<?php echo $this->basePath('/images/trans.png'); ?>" alt="facebook" class="dtls_share_icon" /></a> 
                        <p>Share on</p>
                        <p><i class="fa fa-flag"></i><a id="report-abuse-link" href="javascript:void(0);" data-toggle="modal" data-target="#report-abuse">Report Abuse</a> |</p>

                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <div class="clearfix"></div>

    <p class="dtls_job_title"><b> Job Description </b><?php //echo $this->job->job_title;                                               ?></p>        
    <p> <?php echo $this->job->job_description; ?></p>

    <p class="dtls_job_qualifications">Job Requirements</p>
    <p><?php echo $this->job->job_requirement; ?></p>

    <div class="row">
        <div class="col-xs-12 col-sm-3 col-md-3 dtls_salary_left_p">
            <p>No of Vacancies:</p>
        </div>
        <div class="col-xs-12 col-sm-9 col-md-9 dtls_salary_right_p">
            <p> 
                <?php echo $this->job->no_of_vacencies; ?> 
            </p>
        </div>
        <div class="clearfix"></div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-3 col-md-3 dtls_salary_left_p">
            <p>Salary:</p>
        </div>
        <div class="col-xs-12 col-sm-9 col-md-9 dtls_salary_right_p">
            <p> 
                <?php if (!empty($this->job->salary_range)) { ?>
                    <?php echo $this->job->salary_range; ?>

                <?php } else { ?>
                    Not Disclosed by Recruiter
                <?php } ?>
            </p>
        </div>
        <div class="clearfix"></div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-3 col-md-3 dtls_salary_left_p">
            <p>Industry:</p>
        </div>
        <div class="col-xs-12 col-sm-9 col-md-9 dtls_salary_right_p">
            <p>
                <?php
                $counter = 1;
                foreach ($this->job_industry as $val) {
                    if (count($this->job_industry) == $counter) {
                        $coma = "";
                    } else {
                        $coma = ", ";
                    }
                    echo $val["name"] . $coma;

                    $counter++;
                }
                ?>                    

            </p>
        </div>
        <div class="clearfix"></div>
    </div>


    <div class="row">
        <div class="col-xs-12 col-sm-3 col-md-3 dtls_salary_left_p">
            <p>Functional Area:</p>
        </div>
        <div class="col-xs-12 col-sm-9 col-md-9 dtls_salary_right_p">
            <p>
                <?php
                $counter = 1;
                foreach ($this->job_department as $val) {
                    if (count($this->job_department) == $counter) {
                        $coma = "";
                    } else {
                        $coma = ", ";
                    }
                    echo $val["name"] . $coma;

                    $counter++;
                }
                ?>                    
            </p>
        </div>
        <div class="clearfix"></div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-3 col-md-3 dtls_salary_left_p">
            <p>Role Category:</p>
        </div>
        <div class="col-xs-12 col-sm-9 col-md-9 dtls_salary_right_p">
            <p>
                <?php
                $counter = 1;
                foreach ($this->job_role as $val) {
                    if (count($this->job_role) == $counter) {
                        $coma = "";
                    } else {
                        $coma = ", ";
                    }
                    echo $val["name"] . $coma;

                    $counter++;
                }
                ?>                    

            </p>
        </div>
        <div class="clearfix"></div>
    </div>

    <div class="row">

        <?php if (!empty($this->job->age_limit_from)) { ?>
            <div class="col-xs-12 col-sm-3 col-md-3 dtls_salary_left_p">
                <p>Age Limit:</p>
            </div>
            <div class="col-xs-12 col-sm-9 col-md-9 dtls_salary_right_p">
                <p> 
                    <?php echo $this->job->age_limit_from . "-" . $this->job->age_limit_to . " Yrs"; ?>                                       
                </p>
            </div>
            <div class="clearfix"></div>
        <?php } ?>

        <?php if (!empty($this->job->age_limit_other)) { ?>
            <div class="col-xs-12 col-sm-3 col-md-3 dtls_salary_left_p">
                <p>Age Limit:</p>
            </div>
            <div class="col-xs-12 col-sm-9 col-md-9 dtls_salary_right_p">
                <p> 
                    <?php echo $this->job->age_limit_other . " Yrs"; ?>                                       
                </p>
            </div>
            <div class="clearfix"></div>
        <?php } ?>
    </div>

    <div class="row">
        <?php if (!empty($this->job->job_level)) { ?>
            <div class="col-xs-12 col-sm-3 col-md-3 dtls_salary_left_p">
                <p>Job Level:</p>
            </div>
            <div class="col-xs-12 col-sm-9 col-md-9 dtls_salary_right_p">
                <p> 
                    <?php echo $this->job->job_level; ?>                                       
                </p>
            </div>
            <div class="clearfix"></div>
        <?php } ?>
    </div>

    <div class="row">
        <?php if (!empty($this->job->job_type)) { ?>
            <div class="col-xs-12 col-sm-3 col-md-3 dtls_salary_left_p">
                <p>Job Nature:</p>
            </div>
            <div class="col-xs-12 col-sm-9 col-md-9 dtls_salary_right_p">
                <p> 
                    <?php echo $this->job->job_type; ?>                                       
                </p>
            </div>
            <div class="clearfix"></div>
        <?php } ?>
    </div>




    <!--    End of salary_details_container-->

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="dtls_keyskill_container">
                <h3>Preferred Business Area</h3>           
                <?php
                foreach ($this->job_business as $val) {
                    echo "<p>" . $val["name"] . "</p>";
                }
                ?>  

            </div>
            <div class="clearfix"></div>

            <div class="dtls_education_required">

                <h4>Other Benefits</h4>
                <p><?php echo $this->job->other_benefits; ?></p>

            </div>
            <!--End of dtls_education_required-->

            <!--    End of dtls_keyskill_container-->

            <div class="dtls_education_required">
                <h3>Desired Candidate Profile</h3>
                <h4>Education-</h4>
                <p><?php echo $this->job->job_education; ?></p>

            </div>
            <!--End of dtls_education_required-->

            <div class="dtls_company_profile_container">
                <h3>Company Profile:</h3>
                <?php
                if ($this->job->show_company_status == "No") {
                    ?>
                    <h4><?php echo $this->job->full_name; ?></h4>                   
                    <p><?php echo $this->company["company_description"]; ?></p>
                    <?php
                } else {
                    ?>
                    <h4><?php echo $this->job->hidden_company_name; ?></h4>
                    <?php
                }
                ?>
            </div>




            <!--    End of dtls_company_profile_container-->
            <?php if (!empty($this->job->email_cv_received) || !empty($this->job->hardcopy_cv_received)) { ?>

                <h2 class="apply_instruction">Apply Instructions:</h2>
                <?php if (!empty($this->job->email_cv_received)) { ?>        
                    <p>Please send your Resume (email): <a href="mailto:<?php echo $this->job->email_cv_received; ?>"><?php echo $this->job->email_cv_received; ?></a></p>
                <?php } ?>

                <?php if (!empty($this->job->hardcopy_cv_received)) { ?>        
                    <p>For Hardcopy: <?php echo $this->job->hardcopy_cv_received; ?>  </p>
                <?php } ?>     



            <?php } ?>




            <?php
            if ($this->identity()) {
                if (($this->identity()->user_type == 3) && ($this->job->online_cv_received != "")) {
                    if ($job_status[0]["app_status"] == "apply") {
                        ?>
                        <div class="dtls_login_btn_container">
                            <a data-id="<?php echo $id; ?>"  id="already_apply_job"  href="javascript:void(0);" class="btn btn-primary dtls_login" role="button">Apply</a>                    
                        </div>      
                        <?php
                    } else {
                        ?>
                        <div class="dtls_login_btn_container">
                            <a data-id="<?php echo $id; ?>"  id="apply_job"  href="javascript:void(0);" class="btn btn-primary dtls_login" role="button">Apply</a>                    
                        </div>
                        <?php
                    }
                }
            } else {
                if ($this->job->online_cv_received != "") {
                    ?>
                    <div class="dtls_login_btn_container">
                        <a href="javascript:void(0);" data-type="apply" class="login_to_apply btn btn-primary dtls_login" role="button">Login to Apply</a>
                        <a href="/registration" class="btn btn-primary dtls_registar" role="button">Registrar and Apply</a>
                    </div>  
                    <?php
                }
            }
            ?>



            <div class="dtls_view_similar_jobs_contner">
                <ul>
                    <li><a href="/job?cat_id=/<?php echo $this->job->category_id ?>">View similar jobs</a></li>
                    <li><a href="/job?emp=/<?php echo $this->job->employer_id ?>">View jobs by this company</a></li>
                    <li><a href="#">Email this jobs</a></li>                
                </ul>
                <div class="clearfix"></div>
            </div>
            <!--    End of dtls_view_similar_jobs_contner-->

            <div class="col-xs-12 col-sm-12 col-md-12 no_padding_left no_right_padding">


                <?php if (count($this->similar_jobs) > 0) { ?>
                    <div class="dtls_similar_job_container">  
                        <p class="similar_jobs">Similar Jobs for You</p>
                        <?php
                        $row = 0;

                        foreach ($this->similar_jobs as $similar) {
                            // print_r($similar);
                            //echo $similar["id"]."--";
                            //echo ($row % 2)."---<br>";
                            if (($row % 2) == 0) {
                                ?>
                                <div class="col-xs-12 col-sm-5 col-md-5 dtls_similar_job_each no_padding_left">
                                    <h3 class="dtls_job_title"> <a href="<?php echo "/job/show/" . $similar["id"]; ?>"><?php echo $similar["job_title"]; ?></a> </h3>
                                    <h4 class="dtls_company_name"><?php echo $this->job->full_name; ?></h4>

                                    <?php if (!empty($similar["job_experienced"])) { ?>
                                        <p class="dtls_experience"><?php echo $similar["job_experienced"]; ?> yrs </p>  
                                    <?php }
                                    ?>

                                    <?php if (!empty($similar["job_location"])) { ?>
                                        <p class="dtls_company_location"><?php echo $similar["job_location"]; ?></p>   
                                    <?php }
                                    ?>                                                                                                                                                <!--<h4 class="dtls_company_name"><?php echo $this->job->full_name; ?></h4>-->


                                    <div class="clearfix"></div>
                                </div>
                                <?php
                            } else {
                                ?>
                                <div class="col-xs-12 col-sm-5 col-md-5 dtls_similar_job_each no_border no_padding_left pull-right">
                                    <h3 class="dtls_job_title"><a href="<?php echo "/job/show/" . $similar["id"]; ?>"><?php echo $similar["job_title"]; ?></a> </h3>
                                    <h4 class="dtls_company_name"><?php echo $this->job->full_name; ?></h4>
                                    <?php if (!empty($similar["job_experienced"])) { ?>
                                        <p class="dtls_experience"><?php echo $similar["job_experienced"]; ?> yrs </p>  
                                    <?php }
                                    ?>

                                    <?php if (!empty($similar["job_location"])) { ?>
                                        <p class="dtls_company_location"><?php echo $similar["job_location"]; ?></p>   
                                    <?php }
                                    ?>  
                                    <div class="clearfix"></div>
                                </div>
                                <div class="clearfix"></div>
                                <?php
                            }
                            $row++;
                        }
                        ?>

                        <div class="clearfix"></div>        
                        <div class="dtls_similar_jobs_view_all"><p><a href="/job?emp=<?php echo $this->similar_jobs[0]["employer_id"]; ?>">View All</a></p></div>
                        <div class="clearfix"></div>        
                    </div>
                <?php } ?>
                <!--    End of dtls_similar_job_container-->


            </div>
        </div> 

        <div class="clearfix"></div>
    </div>

    <div class="hidden-xs common_google_ads">        
        <!-- /85406138/Chakri_Jobdetails_L1_650x250 -->
        <div id='div-gpt-ad-1440660585694-0' style='height:250px; width:650px;'>
            <script type='text/javascript'>
                googletag.cmd.push(function() {
                    googletag.display('div-gpt-ad-1440660585694-0');
                });
            </script>
        </div> 
        <!--  End of dtls_similar_job_container-->
    </div>

</div>


<div class="hidden-xs col-sm-4 col-md-4 job_details_right_container no_right_padding">
    <div class="common_google_ads ad_right">
        <!-- /85406138/Chakri_Jobdetails_R1_336x280 -->
        <div id='div-gpt-ad-1440660357789-0' style='height:280px; width:336px;'>
            <script type='text/javascript'>
                googletag.cmd.push(function() {
                    googletag.display('div-gpt-ad-1440660357789-0');
                });
            </script>
        </div>
        <!-- /85406138/Chakri_Jobdetails_R1_336x280 -->
    </div>

    <div class="common_google_ads">
        <!-- /85406138/Chakri_Jobdetails_F1_300x600 -->
        <div id='div-gpt-ad-1440660461405-0' style='height:600px; width:300px;'>
            <script type='text/javascript'>
                googletag.cmd.push(function() {
                    googletag.display('div-gpt-ad-1440660461405-0');
                });
            </script>
        </div>
    </div>

</div>

<div class="clearfix"></div>

<div class="hidden-xs common_google_ads">
    <!-- /85406138/Chakri_Jobdetails_B2_970x90 -->
    <div id='div-gpt-ad-1440660710266-0'>
        <script type='text/javascript'>
            googletag.cmd.push(function() {
                googletag.display('div-gpt-ad-1440660710266-0');
            });
        </script>
    </div>
</div>


<!-- Modal -->
<div id="deleteModal" class="modal fade" role="dialog" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Upload Image </h4>
            </div>
            <div class="modal-body">
                <p>You are about to delete this user. Are you sure that you want to continue?</p>
            </div>

            <div class="modal-footer">
                <button id="confirm" class="btn btn-primary">Yes</button>
                <button id="cancel" class="btn" data-dismiss="modal" aria-hidden="true">No, leave</button>
            </div>
        </div>        
    </div>
</div>  

<div id="loginBox" style="display: none;">
    <form id="loginForm" method="post" class="form-horizontal">
        <div id="error_message">

        </div>

        <div class="form-group">
            <label class="col-xs-3 control-label">Username</label>
            <div class="col-xs-5">
                <input type="text" class="form-control" name="user_name" required />
            </div>
        </div>

        <div class="form-group">
            <label class="col-xs-3 control-label">Password</label>
            <div class="col-xs-5">
                <input type="password" class="form-control" name="password" required />
            </div>
        </div>

        <div class="form-group">
            <div class="col-xs-5 col-xs-offset-3">
                <input type="hidden" value="<?php echo $id; ?>" name="job_id"/>
                <input id="job_type" type="hidden" value="" name="type" />
                <button type="submit" class="btn btn-default">Login</button>
                <!--<button type="submit" class="btn btn-default back_button">Back</button>-->
            </div>
        </div>
    </form>
</div>

<div class="modal fade" tabindex="-1" id="report-abuse" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="feedback_modal">
                <button type="button" class="close feedback_close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title modal_title" id="myModalLabel"> Report Abuse</h4>
            </div>
            <div class="modal-body">
                <form id="report_abuse_form" action="/application/reportAbuse" method="post" class="form-horizontal">
                    <?php if (!$this->identity()) { ?>
                        <div class="form-group">
                            <label class="col-xs-3 control-label" for="report-abuse-email">Your e-mail</label>
                            <div class="col-xs-5">
                                <input type="email" id="report-abuse-email" class="form-control" name="email" required />
                            </div>
                        </div>
                    <?php } ?>
                    <div class="form-group">
                        <label class="col-xs-3 control-label" for="report-abuse-type">Select abuse type</label>
                        <div class="col-xs-5">
                            <select name="abuse_type" class="form-control" id="report-abuse-type" multiple size="6" required>
                                <option value="fraud">Fraud</option>
                                <option value="duplicate">Duplicate</option>
                                <option value="wrong_category">Wrong category</option>
                                <option value="offensive">Offensive</option>
                                <option value="sold_item">Sold item</option>
                                <option value="other">Other</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-3 control-label" for="report-abuse-message">Message</label>
                        <div class="col-xs-5">
                            <input type="hidden" name="page" value="<?php echo $this->job->job_title . " (Job)"; ?>" />
                            <input type="hidden" name="edit" value="<?php echo $this->job->job_title . " (Job)"; ?>" />
                            <textarea class="form-control" id="report-abuse-message" name="message" rows="5" cols="50"></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-5 col-xs-offset-3">
                            <button type="submit" class="btn btn-default btn-primary">Send</button>
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div><!-- Report Abuse -->

<div id="applyBox" style="display: none;">
    <form id="afterLoginApplyJobForm" method="post" class="form-horizontal">        
        <div class="form-group">
            <label class="col-xs-3 control-label">Expected salary</label>
            <div class="col-xs-5">
                <input type="number" class="form-control" name="expected_salary" required />
            </div>
        </div>

        <div class="form-group">
            <label class="col-xs-3 control-label">Select your cv</label>
            <div class="col-xs-5">
                <select name="cv_id" required>
                    <option value="">Select cv</option>
                    <?php
                    foreach ($chk_cv as $val) {
                        ?>
                        <option value="<?php echo $val["id"]; ?>"><?php echo $val["resume_title"]; ?></option>
                        <?php
                    }
                    ?>
                </select>
            </div>
        </div>

        <div class="form-group">
            <div class="col-xs-5 col-xs-offset-3">
                <input type="hidden" value="<?php echo $id; ?>" name="id"/>
                <input id="job_type" type="hidden" value="apply" name="type" />
                <button class="btn btn-default after_login_apply" type="submit">Apply</button>
                <!--<button class="btn btn-default back_button" type="submit">Back</button>-->
            </div>
        </div>
    </form>
</div>

<script type="text/javascript" src="http://static.addinto.com/ai/ai2_bkmk.js"></script>
<script type="text/javascript" src="/js/validator.js"></script>

<script type="text/javascript">
            $("body").on("click", "#save_job", function(e) {
                e.preventDefault();
                var job_id = $(this).attr("data-id");
                bootbox.confirm("Are you sure want to save this job?", function(confirmed) {
                    //console.log("Confirmed: id " + edu_id);
                    // var edu_id = $(this).attr("data-id");
                    if (confirmed)
                    {
                        $.ajax({
                            url: '/job/savejob',
                            type: 'post',
                            dataType: 'json',
                            data: {id: job_id, type: 'save'},
                            success: function(data) {
                                //bootbox.alert(data.message);
                                bootbox.alert({
                                    closeButton: false,
                                    title: "",
                                    message: data.message,
                                    callback: currentPageReload
                                });
                            }
                        });
                    }
                });

            });

            $("body").on("click", "#apply_job", function(e) {


                var type = $(this).attr("data-type");
                $("#job_type").val(type);

                // $('#login_to_apply').on('click', function() {
                bootbox
                        .dialog({
                            title: 'Please select your option.',
                            message: $('#applyBox'),
                            show: false // We will show it manually later
                        })
                        .on('shown.bs.modal', function() {
                            $('#applyBox')
                                    .show();                             // Show the login form
                            //.formValidation('resetForm', true); // Reset form
                        })
                        .on('hide.bs.modal', function(e) {
                            // Bootbox will remove the modal (including the body which contains the login form)
                            // after hiding the modal
                            // Therefor, we need to backup the form
                            $('#applyBox').hide().appendTo('body');
                        })
                        .modal('show');
            });

            $("body").on("submit", "#afterLoginApplyJobForm", function(e) {
                e.preventDefault();
                $.ajax({
                    url: '/job/savejob',
                    type: 'post',
                    dataType: 'json',
                    data: $('#afterLoginApplyJobForm').serialize(),
                    success: function(data) {

                        $('#afterLoginApplyJobForm').html(data.message);
                        exit;
                        bootbox.hideAll();
                        //bootbox.alert(data.message);
                        bootbox.alert({
                            closeButton: false,
                            title: "",
                            message: data.message,
                            callback: currentPageReload
                        });
                    }
                });

            });


</script>

<script>
//    $("body").on("click", "#report-abuse-link", function(e) {
//        bootbox
//        .dialog({
//            closeButton: true,
//            title: 'Report Abuse',
//            message: $('#report-abuse'),
//            show: false // We will show it manually later
//        })
//        .on('shown.bs.modal', function() {
//            $('#report-abuse').show();
//        })
//        .on('hide.bs.modal', function(e) {
//            $('#report-abuse').hide().appendTo('body');
//        })
//        .modal('show');
//    });
    // Report Abuse form submits
//    $("body").on("submit", "#report_abuse_form", function(e){
//        
//        e.preventDefault();
//        $.ajax({
//            url: '/chkapi/user/abuse',
//            type: 'post',
//            dataType: 'json',
//            data: $('#report_abuse_form').serialize(),
//            success: function(data){
//             $('#report_abuse_form').html('ok');
    //  bootbox.hideAll();
    /*   bootbox.alert({
     closeButton: false,
     title: "ssssssssssssssssss",
     message: datatttt.message,
     callback: currentPageReload
     });
     */
//            },
//            fail: function(data){alert('ddddd fail');},
//            done: function(data){alert('ddddd fail');}
//        });
//    });
</script>


<script type="text/javascript">
    $(document).ready(function() {
        // Login button click handler
        $("body").on("click", ".login_to_apply", function(e) {

            var type = $(this).attr("data-type");
            $("#job_type").val(type);


            bootbox.dialog({
                closeButton: true,
                title: 'Login',
                message: $('#loginBox'),
                show: false // We will show it manually later
            })
                    .on('shown.bs.modal', function() {
                        $('#loginBox')
                                .show(); // Show the login form
                        //.formValidation('resetForm', true); // Reset form
                    })
                    .on('hide.bs.modal', function(e) {
                        $('#loginBox').hide().appendTo('body');
                    })
                    .modal('show');

        });

        // login button submit     
        $("body").on("submit", "#loginForm", function(e) {
            e.preventDefault();
            var job_id = $(this).attr("data-id");
            //console.log($(this).serialize());
            $.ajax({
                url: '/chkapi/user/login',
                type: 'post',
                dataType: 'json',
                data: $('#loginForm').serialize(),
                success: function(data) {
                    //...do something with the data...
                    if (data.success == 1)
                    {

                        if (data.status == "already_apply")
                        {
                            bootbox.hideAll();
                            bootbox.alert({
                                closeButton: false,
                                title: "",
                                message: "You alredy apply this job.",
                                callback: currentPageReload
                            });
                        }
                        else if (data.status == "already_save")
                        {
                            bootbox.hideAll();
                            bootbox.alert({
                                closeButton: true,
                                title: "",
                                message: "You alredy save this job",
                                callback: currentPageReload
                            });
                        }
                        else if (data.status == "insert_apply" || data.status == "update_apply")
                        {
                            $('.modal-title').html('<div style="color:#3c763d;font-seze:15px;">Successfully login. Please select your option.</div>');
                            $('#loginBox').html(data.apply_form);
                        }
                        else if (data.status == "insert_save")
                        {
                            bootbox.hideAll();
                            bootbox.alert({
                                closeButton: true,
                                title: "",
                                message: "Succefully save your job",
                                callback: currentPageReload
                            });
                        }

                    }
                    else
                    {
                        $('#error_message').html('<div class="alert alert-danger">' + data.err_msgs + "<div>");
                    }
                }
            });

        });

        //For applay job
        $("body").on("submit", "#applyJobForm", function(e) {

            e.preventDefault();
            //console.log($(this).serialize());
            $.ajax({
                url: '/job/savejob',
                type: 'post',
                dataType: 'json',
                data: $('#applyJobForm').serialize(),
                success: function(data) {
                    bootbox.hideAll();
                    bootbox.alert({
                        closeButton: true,
                        title: "",
                        message: data.message,
                        callback: currentPageReload
                    });

                }
            });

        });


        $("body").on("click", "#already_apply_job", function(e) {
            e.preventDefault();
            bootbox.alert("Already applied for this job.");
        });

        $("body").on("click", "#already_save_job", function(e) {
            e.preventDefault();
            bootbox.alert("Already saved this job.");

        });
    });

    $("body").on("click", ".back_button", function(e) {
        bootbox.hideAll();
        location.reload();
    });


    $("body").on("click", ".close_button", function(e) {
        bootbox.hideAll();
    });

    function currentPageReload() {

        location.reload();
    }

</script>

<script type="text/javascript">
    $(document).ready(function() {
        $('.login_to_apply img').on('click', function() {
            $(this).attr('src', '/images/dtls_saved_jobs_icon_saved.png');
        });
    });
</script>

