<form class="form-horizontal">
    <div class="form-group">
        <label for="inputEmail3" class="col-sm-3 control-label">Email Address:</label>
        <div class="col-sm-9">
            <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
        </div>
        <div class="clearfix"></div>
    </div>

    <div class="form-group">
        <label for="inputEmail3" class="col-sm-3 control-label">Phone:</label>
        <div class="col-sm-9">
            <input type="text" class="form-control" id="inputEmail3" placeholder="Phone Number">
        </div>
        <div class="clearfix"></div>
    </div>


    <div class="form-group">
        <label for="inputEmail3" class="col-sm-3 control-label">Present Address:</label>
        <div class="col-sm-9">
            <textarea class="form-control" rows="3"></textarea>
        </div>
        <div class="clearfix"></div>
    </div>

    <div class="form-group">
        <label for="inputEmail3" class="col-sm-3 control-label">Permanent Address:</label>
        <div class="col-sm-9">
            <textarea class="form-control" rows="3"></textarea>
        </div>
        <div class="clearfix"></div>
    </div>                 

    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-2">
            <button type="submit" class="btn btn-primary">Save Changes</button>
        </div>

        <div class="col-sm-2">
            <button type="submit" id="cancel_btn" class="btn btn-default">Cancel</button>
        </div>
    </div>
    <div class="clearfix"></div>
</form>