<div class="hidden-xs common_google_ads t1-position-ad">
    <!-- /85406138/Chakri_Articles_T1_970x90 -->
    <div id='div-gpt-ad-1444651027888-0'>
        <script type='text/javascript'>
            googletag.cmd.push(function() {
                googletag.display('div-gpt-ad-1444651027888-0');
            });
        </script>
    </div>
</div>

<div class="col-xs-12 col-sm-12 col-md-12 special_page_for_ad article_page_container">
    <div class="pagination_top_container">
        <ul>
            <li><a href="/articles">Home</a></li>
            <li>Article Details</li>
            <div class="clearfix"></div>
        </ul>
    </div>

    <div class="col-xs-12 col-sm-7 col-md-7 article_details_container no_padding_left no_right_padding">
        <h2><?php echo $article[0]['title']; ?></h2>
        <p class="author_details"><span class="date"><?php echo $article[0]['created_at']; ?></span></p>
        <div>
            <img src="<?php echo ($article[0]['article_image'] != NULL) ? $this->basepath('../images/article/' . $article[0]['article_image']) : $this->basepath('/img/default.jpg'); ?>" class="img-responsive article_details_banner pull-right" alt="Article image" height="300" />
            <?php echo $article[0]['description']; ?>
        </div>

        <div class="hidden-xs common_google_ads"> 
            <!-- /85406138/Chakri_Articles_L1_650x250 -->
            <div id='div-gpt-ad-1444719862461-0' style='height:250px; width:650px;'>
                <script type='text/javascript'>
                    googletag.cmd.push(function() {
                        googletag.display('div-gpt-ad-1444719862461-0');
                    });
                </script>
            </div>
        </div>
    </div>

    <div class="col-md-5 about_right_ad_container pull-right">
        <div class="hidden-xs common_google_ads no_top_margin">
            <!-- /85406138/Chakri_Articles_R1_336x280 -->
            <div id='div-gpt-ad-1444719776818-0' style='height:280px; width:336px;'>
                <script type='text/javascript'>
                    googletag.cmd.push(function() {
                        googletag.display('div-gpt-ad-1444719776818-0');
                    });
                </script>
            </div>

        </div>

        <div class="hidden-xs common_google_ads"> 
            <!-- /85406138/Chakri_Articles_F1_300x600 -->
            <div id='div-gpt-ad-1444719812009-0' style='height:600px; width:300px;'>
                <script type='text/javascript'>
                    googletag.cmd.push(function() {
                        googletag.display('div-gpt-ad-1444719812009-0');
                    });
                </script>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
</div>

<div class="hidden-xs col-sm-12 col-md-12 common_google_ads">
    <!-- /85406138/Chakri_About-Policy-Terms_B2_970x90 -->
    <div id='div-gpt-ad-1444720307947-0'>
        <script type='text/javascript'>
            googletag.cmd.push(function() {
                googletag.display('div-gpt-ad-1444720307947-0');
            });
        </script>
    </div>
</div>