<?php
$permissions = $this->permission_helper();
$user_permissions = implode(',', $permissions);
$req_helper = $this->current_request_helper();
$route = $req_helper->get('route');

$nav_route['buisnesstype'] = 'Manage Data';
$nav_route['membershipType'] = 'Members';
$nav_route['jobCategory'] = 'Jobs';
//$nav_route['adminjob'] ='Members';
$nav_route['Reports'] = 'Reports';
$nav_route['Contacts'] = 'Others';
$nav_route['role'] = 'Access Controll';
?>
<ol class="breadcrumb">
    <li><a href="/admin"><i class="fa fa-dashboard"></i> Dashboard</a></li>
    
    <?php if (count($this->pages) == 0) { ?>
        <li><a href="javascript:history.back();"><i class="fa fa-dashboard"></i> Back </a></li>
    <?php } else { ?>

        <?php foreach ($this->pages as $key => $page): ?>
            <?php
            // if this isn't the last page, add a link and the separator


            if ($key == 0) {
                continue;
            }
            if ($key < count($this->pages) - 1):
                ?>
                <li> <a href="<?php echo $page->getHref(); ?>"><?php echo $page->getLabel(); ?></a></li>
            <?php else: ?>
                <li class="active"> <?php echo $page->getLabel(); ?> </li> 
                <?php endif; ?>         
            <?php endforeach; ?>

    <?php } ?>     

</ol>