<?php
$curr_req = $this->current_request_helper();
$router = $curr_req->get('route');
$controller = $curr_req->get('controller');
$action = $curr_req->get('action');

?>
<?php if ($this->pageCount): ?>
    <div>
        <ul class="pagination">
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route,array('action' => $action),array('query' => $this->params)); ?><?php echo count($this->params)> 0 ?"& ":"?" ?>page=<?php echo $this->previous; ?>">
                        <<
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        <<
                    </a>
                </li>
            <?php endif; ?>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li>
                        <a href="<?php echo $this->url($this->route,array('action' => $action),array('query' => $this->params)); ?><?php echo count($this->params)> 0 ?"&":"?";?>page=<?php echo $page;?>">
                            <?php echo $page; ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="active">
                        <a href="#"><?php echo $page; ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route,array('action' => $action),array('query' => $this->params));?><?php echo count($this->params)> 0 ?"&":"?";?>page=<?php echo $this->next; ?>">
                        >>
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        >>
                    </a>
                </li>
            <?php endif; ?>
        </ul>
    </div>
<?php endif;?>