<section class="content">
    <div class="govt_job_ad_form_container box box-default admin_form_bg">
        <form role="form" data-toggle="validator" class="form-horizontal register_employer_form" method="post">
            <h1>Add New Role</h1>
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Role Name:</label>
                <div class="col-sm-5 col-md-5">
                    <input type="text" class="form-control" id="perm_name" name="role_name" placeholder="Role Name" value="<?php echo ($this->post_data["role_name"] != "") ? $this->post_data["role_name"] : $this->results["role_name"]; ?>" required />
                </div>
                <div class="clearfix"></div>
            </div>  

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Permission: </label>
                <div class="col-sm-10 col-md-10">
                    <div class="check_box_scroller_container">
                        <?php
                        foreach($this->permissions as $val)
                        {
                           ?>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" id="checkboxSuccess" name="perm_id[]" value="<?php echo $val["id"]; ?>" <?php echo (! isset($this->post_data["perm_id"]) && in_array($val["id"], $selected_role_permissions_id)) ? 'checked="checked"' : '' ?>  <?php echo (isset($this->post_data["perm_id"]) && in_array($val["id"], $this->post_data["perm_id"])) ? 'checked="checked"' : '' ?> />
                                    <?php echo $val["perm_name"]; ?>
                                </label>
                             </div>
                           <?php
                        }    
                        ?>                  

                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
            
            <div class="form-group">
                <div class=" col-xs-12 col-sm-6 col-md-6 col-sm-offset-2 col-md-offset-2 btn_submit">
                    <button type="submit" class="btn btn-primary pull-left">Submit</button>&nbsp;
                    <a class="btn btn-default" href="<?php echo $this->serverUrl()."/admin/role";?>" role="button">Back</a>
                </div>                                            
            </div>            
            <div class="clearfix"></div>

            <div class="box-footer">
                
            </div>
        </form>
    </div>
</section>

