<?php use Carbon\Carbon;?>
<section class="content">
    <div class="box box-default">
        <div class="box-header with-border">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <h1 class="pull-left page-heading">Report Abuse</h1>
                </div>
            </div>
        </div>
        <div class="box-body">
<?php   if($this->flashMessenger()->hasCurrentSuccessMessages()){?>
            <div class="box box-success box-solid alert-success">
                <div class="box-tools pull-right">
                    <button data-widget="remove" class="btn btn-box-tool text-gray"><i class="fa fa-times"></i></button>
                </div>
                <div class="box-body"><?php echo $this->flashMessenger()->setMessageOpenFormat('<strong>')->setMessageCloseString('</strong>')->render('success');?></div>
            </div>
<?php   }?>
            <table id="report-abuse" class="table table-bordered table-striped table-condensed">
                <thead>
                    <th>SN.</th>
                    <th>Name</th>
                    <th>URL</th>
                    <th>Abuse Type</th>
                    <th>Status</th>
                    <th>Viewed By</th>
                    <th>Created at</th>
                    <th>Updated at</th>
                    <th>Action</th>
                </thead>
                <tbody>
<?php           foreach($this->reports as $key=>$report):?>
                    <tr>
                        <td><?php echo $key+1;?></td>
                        <td>
<?php
                            $user_type=($report["user_type"]==3 ? "Job Seeker" : ($report["user_type"]==4 ? "Employer" : ($report["user_type"]==2 ? "Admin" : NULL)));
                            $user_type=($user_type != NULL ? " (".$user_type.")" : "");
                            echo ($report["name"]!=NULL ? $report["name"] : "Public User" ).$user_type;
?>
                        </td>
                        <td><a href="<?php echo $report["url"];?>" target="_blank"><?php echo $report["page"];?></a></td>
                        <td><?php echo ucfirst($report["abuse_type"]);?></td>
                        <td><?php echo ($report["status"]==0) ? "Inactive" : "Active";?></td>
                        <td><?php echo $report["viewed_by"];?></td>
                        <td>
<?php
                            $dt=Carbon::createFromFormat('Y-m-d H:i:s',$report["created_at"]);
                            echo $dt->toFormattedDateString();
?>
                        </td>
                        <td>
<?php
                            $dt=Carbon::createFromFormat('Y-m-d H:i:s',$report["updated_at"]);
                            echo $dt->toFormattedDateString();
?>
                        </td>
                        <td>
                            <div class="btn-group">
                                <a class="btn btn-primary btn-xs" href='<?php echo "/admin/reportabuse/show/".$report["id"];?>' target="_blank"><i class="fa fa-edit"></i> Show</a>
                                <form method="POST" action="<?php echo "/admin/reportAbuse/delete/".$report["id"];?>" accept-charset="UTF-8" style="display:inline">
                                    <button style="border-bottom-left-radius:0;border-top-left-radius:0;" class="btn btn-xs btn-danger" type="button" data-toggle="modal" data-target="#confirmDelete" data-title="Delete Report" data-message="Are you sure you want to delete this report ?">
                                        <i class="glyphicon glyphicon-trash"></i> Delete
                                    </button>
                                </form>
                            </div>
                        </td>
                    </tr>
<?php           endforeach;?>
                </tbody>
                <tfoot>
                    <th>SN.</th>
                    <th>Name</th>
                    <th>URL</th>
                    <th>Abuse Type</th>
                    <th>Status</th>
                    <th>Viewed By</th>
                    <th>Created at</th>
                    <th>Updated at</th>
                    <th>Action</th>
                </tfoot>
            </table>
        </div>
    </div>
</section>
<script>
    $(document).ready(function(){
        $('#report-abuse').dataTable();
    });
</script>