<?php use Carbon\Carbon;?>

<section class="content">
    <!-- Default box -->
    <div class="box box-default">
        <form role="form" data-toggle="validator" class="form-horizontal" method="post">
            <div class="col-lg-12 col-sm-12 col-md-12"><a id="print_report" href="#" class="feedback_align"> <i class="fa fa-print fa-3x feedback_prnt_icon"></i></a></div>
            <div class="clearfix"></div>
            <table id="report-abuse" class="table table-bordered table-striped table-condensed">
                <thead>
                    <th colspan="2">Report</th>
                </thead>
                <tbody>
                    <tr>
                        <td>Name</td>
                        <td>
<?php
                            $user_type=($report["user_type"]==3 ? "Job Seeker" : ($report["user_type"]==4 ? "Employer" : ($report["user_type"]==2 ? "Admin" : NULL)));
                            $user_type=($user_type != NULL ? " (".$user_type.")" : "");
                            echo ($report["full_name"]!=NULL ? $report["full_name"] : "User" ).$user_type;
?>
                        </td>                       
                    </tr>
                    <tr>
                        <td>Email</td>
                        <td><?php echo ($report["email"]) ? $report["email"] : ($report["member_email"] ? $report["member_email"] : "Email address not found. Invalid user");?></td>
                    </tr>
                    <tr>
                        <td>URL</td>
                        <td><a href="<?php echo $report["url"];?>" target="_blank"><?php echo $report["page"];?></a></td>
                    </tr>
                    <tr>
                        <td>Message</td>
                        <td><?php echo $report["message"];?></td>
                    </tr>
                    <tr>
                        <td>Created At</td>
                        <td>
<?php
                            $dt=Carbon::createFromFormat('Y-m-d H:i:s',$report["created_at"]);
                            echo $dt->toFormattedDateString();
?>
                        </td>
                    </tr>
                    <tr>
                        <td>Updated At</td>
                        <td>
<?php
                            $dt=Carbon::createFromFormat('Y-m-d H:i:s',$report["updated_at"]);
                            echo $dt->toFormattedDateString();
?>
                        </td>
                    </tr>
                </tbody>
            </table>
            <a class="btn btn-default" href="<?php echo $this->serverUrl()."/admin/reportabuse";?>" role="button">Back</a>
        </form>
    </div><!-- /.box -->
</section><!-- /.content -->

<script src="<?php echo $this->basePath('js/jQuery.print.js'); ?>"></script>
<script>
    $("body").on("click", "#print_report", function (e) {
        $("#report-abuse").print({
            globalStyles: true,
            mediaPrint: false,
            stylesheet: null,
            noPrintSelector: ".no-print",
            iframe: true,
            append: null,
            prepend: null,
            manuallyCopyFormValues: true,
            deferred: $.Deferred()
        });
    });

$("#print_icon").show();

</script>
<style type="text/css">
    .feedback_align{
        float: right;
    }
    .feedback_prnt_icon{
        font-size: 24px;
    }
    .box{padding:10px;}
</style>