<?php use Carbon\Carbon;?>

<section class="content">
    <!-- Default box -->
    <div class="box box-default">
        <div class="box-header with-border">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="pull-left"><h4> Feedback : </h4></div>
                    
                </div>
            </div>
        </div>
        
        <div class="box-body">
           
            
<?php   if($this->flashMessenger()->hasCurrentSuccessMessages()){?>
            <div class="box box-success box-solid alert-success">
                <div class="box-tools pull-right">
                    <button data-widget="remove" class="btn btn-box-tool text-gray"><i class="fa fa-times"></i></button>
                </div>
                <div class="box-body">
<?php               echo $this->flashMessenger()->setMessageOpenFormat('<strong>')->setMessageCloseString('</strong>')->render('success');?> 
                </div>
            </div>
<?php   }?>
            <table id="example1" class="table table-bordered table-striped table-condensed">
                <thead>
                    <tr>
                        <th>SN.</th>
                        <th>Feedback Type</th>
                        <th>Email</th>
                        <th>Subject</th>
                        <th>Message</th>
                        <th>Created At</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->feedbacks as $key=>$feedback): ?>

                        <tr>
                            <td><?php echo $key+1; ?></td>
                            <td><?php echo $feedback["type"]; ?></td>                            
                            <td><?php echo $feedback["email"]; ?></td>
                            <td><?php echo $feedback["subject"];?></td>
                            <td><?php echo $feedback["message"];?></td>
                            <td>
                                <?php 
                            $dt=Carbon::createFromFormat('Y-m-d H:m:s',$feedback["created_at"]);
                            echo $dt->toFormattedDateString(); ?>
                                <?php // echo '/ '.$feedback["created_at"];?>
                            </td>
                            
         
                            <td>
                                <div class="btn-group">
                                    <?php $id = $feedback["id"]; ?>
                                     <form method="POST" action="<?php echo "/admin/feed/delete/$id";?>" accept-charset="UTF-8" style="display:inline">                                      
                                        <a class="btn btn-primary btn-xs" href='<?php echo "/admin/feed/show/$id";?>' target="_blank"><i class="fa fa-edit"></i> Show</a>
                                        <button style="border-bottom-left-radius:0;border-top-left-radius:0;" class="btn btn-xs btn-danger" type="button" data-toggle="modal" data-target="#confirmDelete" data-title="Department Type" data-message="Are you sure you want to delete this type ?">
                                            <i class="glyphicon glyphicon-trash"></i> Delete
                                        </button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach; ?>

                </tbody>
                <tfoot>
                    <tr>
                        <th>SN.</th>
                        <th>Feedback Type</th>
                        <th>Email</th>
                        <th>Subject</th>
                        <th>Message</th>
                        <th>Created At</th>
                        <th>Action</th>
                    </tr>
                </tfoot>
            </table>
        </div><!-- /.box-body -->

    </div><!-- /.box -->

</section><!-- /.content -->

<script type="text/javascript">
    var objectId;
    $(function() {
        //$("#example1").dataTable();
        $('#example1').dataTable({});
    });
</script>