<div class="col-xs-12 col-sm-12 col-md-12 about_us_page_container cv_view_top_container">    

    <div class="col-xs-12 col-sm-10 col-md-10 no_padding_left cv_view_container">
        <h2 class="cv_view">Md. Rounak alam khan</h2>
        <p>Cell:01730260993 <br/>Email: rounak1@gmail.com <br/>Address:Green road, Dhaka.</p>   
        <div class="icon_container">
            <a href="#"> <i class="fa fa-print fa-2x"></i></a>
            <a href="#"><i class="fa fa-save fa-2x"></i> </a>
        </div>
    </div>

    <div class="col-xs-12 col-sm-2 col-md-2 no_padding_left no_right_padding">        
        <img src="<?php echo $this->basePath('/images/default_profile.jpg'); ?>" alt="profile picture" width="150" height="150" class="view_cv_photo" />
    </div>
    <div class="clearfix"></div>


    <div class="cv_view_each_container">
        <div class="col-xs-12 col-sm-3 col-md-3 no_padding_left section_title">        
            <h3 class="section_title_each">Career Objective:</h3>        
        </div>

        <div class="col-xs-12 col-sm-9 col-md-9 no_padding_left no_right_padding">        
            <p>I want to work in such an organization I nwant to work in such organization I nwant to work in such organization I nwant to work in such organization .           
            </p>       
        </div>
        <div class="clearfix"></div>
    </div>



    <div class="cv_view_each_container">
        <div class="col-xs-12 col-sm-3 col-md-3 no_padding_left section_title">        
            <h3 class="section_title_each">Career Summary:</h3>        
        </div>

        <div class="col-xs-12 col-sm-9 col-md-9 no_padding_left no_right_padding">        
            <p>Working in The Daily Prothom alo as a web developer from December 07, 2012 to continuing.</p>       
        </div>
        <div class="clearfix"></div>
    </div>



    <div class="cv_view_each_container">
        <div class="col-xs-12 col-sm-3 col-md-3 no_padding_left section_title">        
            <h3 class="section_title_each">Education</h3>        
        </div>

        <div class="col-xs-12 col-sm-9 col-md-9 no_padding_left no_right_padding">        
            <p><span class="highlight_text"> Education Level:</span> S.S.C <br />
                <span class="highlight_text">Group/Subject:</span> Science<br />
                <span class="highlight_text">Institute Name,Board:</span> Jamalpur Zilla School <br />
                <span class="highlight_text">Result:</span> First Class <br />
                <span class="highlight_text">Passing Year:</span> 1999            
            </p>

            <p><span class="highlight_text"> Education Level: </span>  S.S.C <br />
                <span class="highlight_text">Group/Subject:</span> Science<br />
                <span class="highlight_text">Institute Name,Board:</span> Jamalpur Zilla School <br />
                <span class="highlight_text">Result:</span> First Class <br />
                <span class="highlight_text">Passing Year:</span> 1999            
            </p>

            <p><span class="highlight_text"> Education Level:</span>  S.S.C <br />
                <span class="highlight_text">Group/Subject:</span> Science<br />
                <span class="highlight_text">Institute Name,Board:</span> Jamalpur Zilla School <br />
                <span class="highlight_text">Result:</span> First Class <br />
                <span class="highlight_text">Passing Year:</span> 1999            
            </p>
        </div>
        <div class="clearfix"></div>
    </div>




    <div class="cv_view_each_container">
        <div class="col-xs-12 col-sm-3 col-md-3 no_padding_left section_title">        
            <h3 class="section_title_each">Work Experience</h3>        
        </div>

        <div class="col-xs-12 col-sm-9 col-md-9 no_padding_left no_right_padding">        
            <p><span class="highlight_text">The Daily Prothom Alo </span><br />
                Karwan bazar, Dhaka <br />
                Working Experience:January, 2009 to December, 2012 <br /> 
                Web developer <br />
                IT <br />
                <span class="highlight_text">Responsibilities:</span>jskadjkshjd khsajkdhjskahdjksadsa jskadjkshjdk hsajkdhjsk ahdjksadsa
                jskadjk shjdkhsa jkdhjskahd jksadsa jskadjks hjdkhsajk dhjskahdjksadsa           
            </p> 

            <p><span class="highlight_text">The Daily Prothom Alo </span><br />
                Karwan bazar, Dhaka <br />
                Working Experience:January, 2009 to December, 2012 <br /> 
                Web developer <br />
                IT <br />
                <span class="highlight_text">Responsibilities:</span>jskadjkshjdkhsajkdhjskahdjksadsa jskadjkshjdkhsajkdhjskahdjksadsa jskadjkshjdkhsajkdhjskahdjksadsa jskadjkshjdkhsajkdhjskahdjksadsa           
            </p> 

            <p><span class="highlight_text">The Daily Prothom Alo</span> <br />
                Karwan bazar, Dhaka <br />
                Working Experience:January, 2009 to December, 2012 <br /> 
                Web developer <br />
                IT <br />
                <span class="highlight_text">Responsibilities:</span>jskadjkshjdkhsajkdhjskahdjksadsa jskadjkshjdkhsajkdhjskahdjksadsa jskadjkshjdkhsajkdhjskahdjksadsa jskadjkshjdkhsajkdhjskahdjksadsa           
            </p> 

        </div>
        <div class="clearfix"></div>
    </div>



    <div class="cv_view_each_container">
        <div class="col-xs-12 col-sm-3 col-md-3 no_padding_left section_title">        
            <h3 class="section_title_each">Skills/Interest</h3>        
        </div>

        <div class="col-xs-12 col-sm-9 col-md-9 no_padding_left no_right_padding">        
            <p><strong>PHP </strong><br />
                <strong>Title:</strong> Hypertext Preprocessor<br />
                Self Score: 8 out of 5 </p>

            <p><strong>Java</strong><br />
                <strong>Title:</strong> JavaSelf <br />
                Score: 8 out of 5 </p>         



        </div>
        <div class="clearfix"></div>
    </div>


    <div class="cv_view_each_container">
        <div class="col-xs-12 col-sm-3 col-md-3 no_padding_left section_title">        
            <h3 class="section_title_each">Personal Details</h3>        
        </div>

        <div class="col-xs-12 col-sm-9 col-md-9 no_padding_left no_right_padding">        
            <p><span class="col-xs-6 col-sm-4 col-md-4 no_padding_left highlight_text">Father's Name:</span><span class="col-xs-6 col-sm-8 col-md-8">  Md. AVCD EFGH Islam</span> <br />
                <span class="col-xs-6 col-sm-4 col-md-4 no_padding_left highlight_text">Mother's Name:</span><span class="col-xs-6 col-sm-8 col-md-8"> Mrs. Mafia Begum</span> <br />
                <span class="col-xs-6 col-sm-4 col-md-4 no_padding_left highlight_text">Date of Birth:</span> <span class="col-xs-6 col-sm-8 col-md-8">Jamalpur Zilla School</span> <br />
                <span class="col-xs-6 col-sm-4 col-md-4 no_padding_left highlight_text">Marital Status:</span><span class="col-xs-6 col-sm-8 col-md-8"> First Class</span><br />
                <span class="col-xs-6 col-sm-4 col-md-4 no_padding_left highlight_text">Religion:</span> <span class="col-xs-6 col-sm-8 col-md-8">Islam  </span><br />
                <span class="col-xs-6 col-sm-4 col-md-4 no_padding_left highlight_text">Nationality</span><span class="col-xs-6 col-sm-8 col-md-8">Bangladeshi </span><br />
                <span class="col-xs-6 col-sm-4 col-md-4 no_padding_left highlight_text">National_id:</span><span class="col-xs-6 col-sm-8 col-md-8">011222222</span>
            </p>

        </div>
        <div class="clearfix"></div>
    </div>


    <div class="cv_view_each_container">
        <div class="col-xs-12 col-sm-3 col-md-3 no_padding_left section_title">        
            <h3 class="section_title_each">Reference (s):</h3>        
        </div>

        <div class="col-xs-12 col-sm-4 col-md-4 no_padding_left no_right_padding">        
            <p><span class="col-xs-6 col-sm-4 col-md-4 no_padding_left highlight_text"> Name:</span> <span class="col-xs-6 col-sm-8 col-md-8"> Md. Tomuk </span><br />
                <span class="col-xs-6 col-sm-4 col-md-4 no_padding_left highlight_text">Organization:</span><span class="col-xs-6 col-sm-8 col-md-8"> Science</span><br />
                <span class="col-xs-6 col-sm-4 col-md-4 no_padding_left highlight_text">Designation:</span><span class="col-xs-6 col-sm-8 col-md-8"> Jamalpur Zilla School</span> <br />
                <span class="col-xs-6 col-sm-4 col-md-4 no_padding_left highlight_text">Address:</span><span class="col-xs-6 col-sm-8 col-md-8"> First Class</span> <br />
                <span class="col-xs-6 col-sm-4 col-md-4 no_padding_left highlight_text">Phone :</span> <span class="col-xs-6 col-sm-8 col-md-8">02-260993</span>  <br />  
                <span class="col-xs-6 col-sm-4 col-md-4 no_padding_left highlight_text">Mobile</span><span class="col-xs-6 col-sm-8 col-md-8"> 01730260993</span><br />
                <span class="col-xs-6 col-sm-4 col-md-4 no_padding_left highlight_text">E-Mail</span><span class="col-xs-6 col-sm-8 col-md-8"> rounak1@gmail.com </span><br />
                <span class="col-xs-6 col-sm-4 col-md-4 no_padding_left highlight_text">Relation</strong></span> <span class="col-xs-6 col-sm-8 col-md-8">Cousin</span>
            </p>

        </div>
        <div class="col-xs-12 col-sm-5 col-md-5 no_padding_left no_right_padding">        
            <p><span class="col-xs-6 col-sm-4 col-md-4 no_padding_left highlight_text"> Name:</span><span class="col-xs-6 col-sm-8 col-md-8">  Md. Omuk  </span><br />
                <span class="col-xs-6 col-sm-4 col-md-4 no_padding_left highlight_text">Organization:</span><span class="col-xs-6 col-sm-8 col-md-8"> Science</span><br />
                <span class="col-xs-6 col-sm-4 col-md-4 no_padding_left highlight_text">Designation:</span> <span class="col-xs-6 col-sm-8 col-md-8">Jamalpur Zilla School </span><br />
                <span class="col-xs-6 col-sm-4 col-md-4 no_padding_left highlight_text">Address:</span><span class="col-xs-6 col-sm-8 col-md-8"> First Class</span> <br />
                <span class="col-xs-6 col-sm-4 col-md-4 no_padding_left highlight_text">Phone :</span> <span class="col-xs-6 col-sm-8 col-md-8">02-260993</span>  <br />  
                <span class="col-xs-6 col-sm-4 col-md-4 no_padding_left highlight_text">Mobile</span> <span class="col-xs-6 col-sm-8 col-md-8">01730260993</span><br />
                <span class="col-xs-6 col-sm-4 col-md-4 no_padding_left highlight_text">E-Mail</span><span class="col-xs-6 col-sm-8 col-md-8"> rounak1@gmail.com</span> <br />
                <span class="col-xs-6 col-sm-4 col-md-4 no_padding_left highlight_text">Relation</span> <span class="col-xs-6 col-sm-8 col-md-8">Cousin</span>
            </p>

        </div>
        <div class="clearfix"></div>
    </div>


</div>
