</div>
</div>
</div>
<div class="container-fluid footer_top_full_container">
    <div class="container footer_top_middle_container">
        <div class="row"> 
            <h3 class="hidden-xs">Find Jobs in</h3>
            <div class="footer_top_list hidden-xs">                
                <div class="hidden-xs col-sm-12 col-md-12 no_padding_left">
                    <ul>
                        <li><a href="/job?loc=13">Dhaka</a></li>
                        <li><a href="/job?loc=9">Chittagong</a></li>
                        <li><a href="/job?loc=54">Rajshahi</a></li>
                        <li><a href="/job?loc=27">Khulna</a></li>
                        <li><a href="/job?loc=62">Sylhet</a></li>
                        <li><a href="/job?loc=56">Rangpur</a></li>
                        <li><a href="/job?loc=4">Barisal</a></li>
                        <div class="clearfix"></div>                        
                    </ul>                    
                </div>  
                <div class="clearfix"></div> 
            </div> 
        </div> 
        <!--End of row-->

        <div class="row">
            <div class="about_chakri_container">            
                <div class="hidden-xs col-sm-4 col-md-4 footer_each_border about_first_container">                    
                    <h4> About Chakri.com</h4>
                    <p>Chakri.com is an online employment solution for people seeking jobs and the employers who need great people in Bangladesh. Our aim is to help people in the country find jobs and companies they love. Chakri.com is the top most transparent career community in Bangladesh that is changing the way people find jobs, and companies recruit top talent. It helps to connect job seekers directly with ...<a href="/about" target="_blank">more</a></p>
                    <a href="#" target="_blank"><img src="<?php echo $this->basepath('/images/prothom-alo.png'); ?>" alt="prothom alo" class="footer_logo" /></a>
                </div>

                <div class="col-xs-6 col-sm-2 col-md-2 footer_each_border">
                    <h4> Company</h4>
                    <ul>
                        <li><a href="/about">About Us</a></li>
                        <li><a href="/contact">Contact us</a></li>
                        <li><a href="/page/policy">Privacy Policy</a></li>
                        <li><a href="#">Careers</a></li>
                        <li><a href="#">Press Corner</a></li>
                        <li><a href="#">Site Map</a></li>
                    </ul>
                </div>

                <div class="hidden-xs col-sm-2 col-md-2 footer_each_border">
                    <h4>Job Seekers</h4>
                    <ul>
                        <li><a href="/registration">Create Account</a></li>
                        <li><a href="/seeker">My Chakri</a></li>
                        <li><a href="#">Career Counseling</a></li>
                        <li><a href="#">Video Guides</a></li>
                        <li><a href="/page/seeker-faq">FAQ</a></li>
                        <li><a href="/page/jobseeker-terms">Jobseeker Terms &amp; Conditions</a></li>
                    </ul>

                </div>

                <div class="hidden-xs col-sm-2 col-md-2 footer_each_border">
                    <h4>Employers</h4>
                    <ul>
                        <li><a href="/employer-registration">Create Account</a></li>
                        <li><a href="#">Products / Service</a></li>
                        <li><a href="/employer">Post a Job</a></li>
                        <li><a href="/page/employer-faq">FAQ</a></li>
                        <li><a href="/page/employer-terms">Employers Terms &AMP; Conditions</a></li>                       
                    </ul>

                </div>

                <div class="col-xs-6 col-sm-2 col-md-2 no_padding_right">                                
                    <h4>Follow</h4>
                    <ul class="fa-ul">
                        <li><a href="http://www.facebook.com/jobspalo"><i class="fa fa-facebook-square"></i> Facebook</a></li>
                        <li><a href="https://plus.google.com/101248160372229467399"><i class="fa fa-google-plus-square"></i> Google+ </a></li>
                        <li><a href="https://twitter.com/prothomalojobs"><i class="fa fa-twitter-square"></i> Twitter</a></li>
                        <li><a href="http://www.youtube.com/user/prothomalojobs"><i class="fa fa-youtube-square"></i> Youtube</a></li>

                    </ul>             

                </div>
                <div class="clearfix"></div>
            </div>
        </div> 
        <!--End of row-->
    </div>
</div>


<div class="container-fluid footer_full_container">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 footer_middle_container">            
                <p>&COPY; 2015 Copyright Mediastar Limited. All Rights Reserved. <a href="/page/terms">Terms of use</a>&nbsp;&nbsp;<a href="/page/policy">Privacy Statement</a></p>  
                <p>Reproduction of material of any chakri.com pages without written permission is strictly prohibited.</p>            
            </div>
        </div>
    </div>
</div>
<!-- Bootstrap -->


<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->

<!--<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>-->
<script src="<?php echo $this->basepath('js/jquery-ui.min.js'); ?>"></script>

<!-- Include all compiled plugins (below), or include individual files as needed -->
<!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>-->
<script src="<?php echo $this->basepath('bootstrap/js/bootstrap.min.js'); ?>"></script>

<script src="<?php echo $this->basepath('js/validator.js'); ?>"></script>
<script src="<?php echo $this->basePath('js/jquery.custom-scrollbar.js'); ?>"></script>
<!-- FastClick -->
<script src="<?php echo $this->basePath('/plugins/pace/pace.js') ?>"></script>

<script src="<?php echo $this->basePath('/js/bootbox.min.js') ?>" type="text/javascript"></script> 

<script type="text/javascript">
    $(window).load(function() {
        $(".demo").customScrollbar();
        $("#fixed-thumb-size-demo").customScrollbar({fixedThumbHeight: 50, fixedThumbWidth: 60});
    });
</script>



</body>
</html>