<?php

use Carbon\Carbon;

$req_route = $this->seeker_helper();
$seeker_message_notification = $req_route['seeker_message_notification'];
$seeker_all_unread_message = $req_route['seeker_all_unread_message'];

$req_route_notification = $this->notification_helper();
$total_notification = $req_route_notification['total_notification'];
$all_notification = $req_route_notification['all_notification'];
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Chakri.com</title>
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico')) ?>
        <link rel="stylesheet" href="<?php echo $this->basePath('/bootstrap/css/bootstrap.min.css'); ?>">        
        <link rel="stylesheet" href="<?php echo $this->basePath('css/style.css'); ?>">
        <link rel="stylesheet" href="<?php echo $this->basePath('css/font-awesome.min.css') ?>">
        <link rel="stylesheet" href="<?php echo $this->basePath('css/jquery.custom-scrollbar.css'); ?>">

<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>-->
        <script src="<?php echo $this->basePath('js/jquery.min.js'); ?>"></script>

        <!--        DFP Script for Advertisement-->
        <script type='text/javascript'>
            var googletag = googletag || {};
            googletag.cmd = googletag.cmd || [];
            (function() {
                var gads = document.createElement('script');
                gads.async = true;
                gads.type = 'text/javascript';
                var useSSL = 'https:' == document.location.protocol;
                gads.src = (useSSL ? 'https:' : 'http:') +
                        '//www.googletagservices.com/tag/js/gpt.js';
                var node = document.getElementsByTagName('script')[0];
                node.parentNode.insertBefore(gads, node);
            })();
        </script>

        <script type='text/javascript'>
            googletag.cmd.push(function() {
                googletag.defineSlot('/85406138/Chakri_HP_Middle_970x90', [[970, 90], [728, 90]], 'div-gpt-ad-1440659257413-0').addService(googletag.pubads());
                googletag.defineSlot('/85406138/Chakri_Category_T1_970x90', [[728, 90], [970, 90]], 'div-gpt-ad-1440659656479-0').addService(googletag.pubads());
                googletag.defineSlot('/85406138/Chakri_Category_B2_970x90', [[728, 90], [970, 90]], 'div-gpt-ad-1440659863993-0').addService(googletag.pubads());
                googletag.defineSlot('/85406138/Chakri_Jobdetails_T1_970x90', [[728, 90], [970, 90]], 'div-gpt-ad-1440660280027-0').addService(googletag.pubads());
                googletag.defineSlot('/85406138/Chakri_Jobdetails_B2_970x90', [[970, 90], [728, 90]], 'div-gpt-ad-1440660710266-0').addService(googletag.pubads());

                googletag.defineSlot('/85406138/Chakri_Jobdetails_R1_336x280', [336, 280], 'div-gpt-ad-1440660357789-0').addService(googletag.pubads());
                googletag.defineSlot('/85406138/Chakri_Jobdetails_F1_300x600', [300, 600], 'div-gpt-ad-1440660461405-0').addService(googletag.pubads());
                googletag.defineSlot('/85406138/Chakri_Jobdetails_L1_650x250', [650, 250], 'div-gpt-ad-1440660585694-0').addService(googletag.pubads());
                googletag.defineSlot('/85406138/Chakri_Search-Contact_T1_970x90', [[728, 90], [970, 90]], 'div-gpt-ad-1444720380589-0').addService(googletag.pubads());

                googletag.defineSlot('/85406138/Chakri_About-Policy-Terms_T1_970x90', [[970, 90], [728, 90]], 'div-gpt-ad-1444720035828-0').addService(googletag.pubads());
                googletag.defineSlot('/85406138/Chakri_About-Policy-Terms_B2_970x90', [[728, 90], [970, 90]], 'div-gpt-ad-1444720307947-0').addService(googletag.pubads());
                googletag.defineSlot('/85406138/Chakri_About-Policy-Terms_R1_336x280', [336, 280], 'div-gpt-ad-1444720195570-0').addService(googletag.pubads());
                googletag.defineSlot('/85406138/Chakri_About-Policy-Terms_F1_300x600', [300, 600], 'div-gpt-ad-1444720239236-0').addService(googletag.pubads());

                googletag.defineSlot('/85406138/Chakri_Articles_T1_970x90', [[970, 90], [728, 90]], 'div-gpt-ad-1444651027888-0').addService(googletag.pubads());
                googletag.defineSlot('/85406138/Chakri_Articles_B2_970x90', [[728, 90], [970, 90]], 'div-gpt-ad-1444719912075-0').addService(googletag.pubads());
                googletag.defineSlot('/85406138/Chakri_Articles_R1_336x280', [336, 280], 'div-gpt-ad-1444719776818-0').addService(googletag.pubads());
                googletag.defineSlot('/85406138/Chakri_Articles_F1_300x600', [300, 600], 'div-gpt-ad-1444719812009-0').addService(googletag.pubads());
                googletag.defineSlot('/85406138/Chakri_Articles_L1_650x250', [650, 250], 'div-gpt-ad-1444719862461-0').addService(googletag.pubads());
                googletag.pubads().enableSingleRequest();
                googletag.enableServices();
            });
        </script>       

        <!--  Close  DFP Script for Advertisement-->


        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js"></script>

    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container-fluid menu">
                <div class="container">
                    <div class="row header_specl_class">

                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>                           
                        </div>

                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav menu_left">
                                <?php
                                if ($user = $this->identity()) {

                                    switch ($user->user_type) {
                                        case 2 :
                                            $my_chakri = '/admin';
                                            break;
                                        case 3:
                                            $my_chakri = '/seeker';
                                            break;
                                        case 4:
                                            $my_chakri = '/employer';
                                            break;
                                    }
                                    ?>
                                    <li class="active"><a href="<?php echo $my_chakri; ?>">My Chakri<span class="sr-only">(current)</span></a></li>
                                <?php } ?>
                                <li><a href="/job">Jobs</a></li>                                
                                <li role="presentation" class="dropdown">
                                    <a class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                                        Resources <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a href="/articles">Home</a></li>
                                        <li><a href=<?php echo "/articles/4"; ?>>Career Articles</a></li>
                                        <li><a href=<?php echo "/articles/3"; ?>>Interview Tips</a></li>
                                        <li><a href=<?php echo "/articles/6"; ?>>Expert opinion</a></li>
                                    </ul>
                                </li>                                
                                <li><a href="#">Workshop</a></li>
                                <li><a href="/job?job_type=Intern">Internship</a></li>
                                <li><a href="/contact">Contact us</a></li>                                

                            </ul>

                            <?php
                            if (!$this->identity()) {
                                ?>
                                <ul class="nav navbar-nav navbar-right menu_right">
                                    <li><a href="/login">Login</a></li> 
                                    <li><a href="/registration">Register</a></li>
                                    <!-- <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">English <span class="caret"></span></a>
                                        <ul class="dropdown-menu" role="menu">
                                            <li><a href="#">Bangla</a></li>
                                            <li><a href="#">Another action</a></li>                                        
                                        </ul>
                                    </li> -->
                                    <li class="last_menu_btn"><a href="/employer-registration"><button type="button" class="btn btn-primary btn-sm nav_right_btn">For Employers</button></a></li>


                                </ul>
                            <?php } ?>



                            <!--After  Login -->
                            <?php
                            if ($this->identity()) {
                                ?>

                                <ul class="nav navbar-nav navbar-right menu_right logged_in_menu">
                                    <?php if ($this->identity()->user_type == 3) { ?>
                                        <li class="dropdown messages-menu">
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                                <i class="fa fa-envelope-o"></i>
                                                <span class="label label-success"><?php echo $seeker_message_notification; ?></span>
                                            </a>
                                            <ul class="dropdown-menu">
                                                <li class="header">You have <span class="tolal_notification"><?php echo $seeker_message_notification; ?></span> message.</li>
                                                <li>
                                                    <!-- inner menu: contains the actual data -->
                                                    <ul class="logged_in">
                                                        <?php
                                                        foreach ($seeker_all_unread_message as $row) {
                                                            ?>
                                                            <li>
                                                                <a href="#">    
                                                                    <div><small class="pull-left"><?php echo substr($row["description"], 0, 30) . "..."; ?></small><?php echo ($row["created_at"] != "0000-00-00 00:00:00") ? '<small class="pull-right"><i class="fa fa-clock-o"></i> ' . Carbon::parse($row["created_at"])->diffForHumans() . '</small>' : ""; ?></div>    
                                                                    <div class="clear"></div>
                                                                </a>
                                                            </li>
                                                            <?php
                                                        }
                                                        ?>                                                    
                                                    </ul>
                                                </li>
                                                <li class="footer"><a href="/seeker/mailBox">See All Messages</a></li>
                                            </ul>
                                        </li>
                                    <?php } ?>
                                    <!-- Notifications: style can be found in dropdown.less -->
                                    <li class="dropdown notifications-menu">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                            <i class="fa fa-bell-o"></i>
                                            <span class="label label-warning tolal_notification"><?php echo $total_notification; ?></span>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li class="header">You have <span class="tolal_notification"><?php echo $total_notification; ?></span> notifications</li>
                                            <li>
                                                <!-- inner menu: contains the actual data -->
                                                <ul class="logged_in all_notification">
                                                    <?php foreach ($all_notification as $val) { ?>
                                                        <li>
                                                            <a href="javscript:void(0);">
                                                                <i class="fa fa-users text-aqua"></i> <?php echo $val["subject"]; ?>
                                                            </a>
                                                        </li>
                                                    <?php } ?>
                                                </ul>
                                            </li>
                                            <?php if ($total_notification != 0) { ?>
                                                <li class="footer all_notification"><a onclick href="javascript:void(0);" id="notification_mark">Mark all read</a></li>
                                            <?php } ?>
                                        </ul>
                                    </li>
                                    <li class="dropdown user user-menu">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                            <!--<img src="<?php echo $this->basePath('/dist/img/user2-160x160.jpg'); ?>" class="user-image" alt="User Image"/>-->
                                            <?php
                                            if ($this->identity()) {
                                                ?>

                                                <span class="hidden-xs"><?php
                                                    echo $this->identity()->full_name;
                                                    ?></span>
                                            <?php } ?>
                                        </a>
                                        <ul class="dropdown-menu dropdown-menu_image">

                                            <!-- User image -->
                                            <li class="user-header">
                                                <img src="<?php echo ($this->identity()->profile_image != '') ? $this->identity()->profile_image : $this->basePath('/dist/img/user2-160x160.jpg'); ?>" class="img-circle" alt="User Image" />                                                
                                                <p>
                                                    <?php echo $this->identity()->full_name; ?>

                                                    <?php
                                                    if ($this->identity()->last_login != "" && $this->identity()->last_login != "Y-m-d H:i:s") {
                                                        $dt = Carbon::createFromFormat('Y-m-d H:i:s', $this->identity()->last_login);
                                                        echo "<br><small>Last Logged in " . $dt->toFormattedDateString() . "</small>";
                                                    }
                                                    ?>                                                  
                                                </p>
                                            </li>
                                            <!-- Menu Footer-->
                                            <li class="user-footer">
                                                <div class="pull-left">                                                    
                                                    <a href="<?php echo $my_chakri; ?>/settings" class="btn btn-default btn-flat">Settings</a>
                                                </div>
                                                <div class="pull-right">
                                                    <a href="/logout" class="btn btn-default btn-flat">Log out</a>
                                                </div>
                                                <div class="clearfix"></div>

                                            </li>
                                        </ul>
                                    </li>
                                </ul>

                            <?php } ?>
                            <a href="/"><img src="<?php echo $this->basePath('/images/chakri-logo-small.png'); ?>" alt="Chakri" class="header_logo" /></a>



                        </div><!-- /.navbar-collapse -->                        

                    </div>


                </div> <!-- End of Container-->
            </div><!-- /.container-fluid --> 
            <div class="clearfix"></div>
        </nav>

        <div class="container-fluid content_full_bg">                           
            <div class="container">  
                <div class="row">
                    <div class="visible-xs visible-sm  hidden-md">
                        <a href="/">
                            <img src="/images/chakri.png" alt="chakri" class="logo-inner center-block img-responsive" />
                        </a>
                    </div>

                    <script type="text/javascript">
            $("body").on("click", "#notification_mark", function(e) {

                e.preventDefault();
                //console.log($(this).serialize());
                $.ajax({
                    url: '/chkapi/api/updateSeekerNotification',
                    type: 'post',
                    dataType: 'json',
                    data: {type: 'save'},
                    success: function(data) {
                        $(".tolal_notification").html("0");
                        $(".all_notification").remove();
                    }
                });

            });
                    </script>