<div class="col-xs-12 col-sm-12 col-md-12 job_details_ad_container">
    <img src="<?php echo $this->basePath('/images/job_details_t1_ad.jpg'); ?>" alt="ad" class="center-block">
</div>

<div class="col-xs-12 col-sm-8 col-md-8">
    <div class="job_details_left_container">
        <div class="col-xs-12 col-sm-8 col-md-8 no_padding_left">
            <h3 class="dtls_job_title"><a href="#"> Web developer (PHP)</a> </h3>
            <h4 class="dtls_company_name">Symantic Software Company ltd</h4>
            <p class="dtls_experience">8-13 yrs</p> 
            <p class="dtls_company_location">Dhaka</p>
            <div class="clearfix"></div>

            <div class="dtls_login_btn_container">
                <a href="#" class="btn btn-primary dtls_login" role="button">Login to Apply</a>
                <a href="#" class="btn btn-primary dtls_registar" role="button">Registrar and Apply</a>
            </div>      

        </div>

        <div class="col-xs-12 col-sm-4 col-md-4 no_right_padding">
            <a href="#"> <img src="<?php echo $this->basePath('/images/job_dtls_company_logo.jpg'); ?>" alt="company_logo" class="job_dtls_company_logo"></a> 
        </div>

        <div class="clearfix"></div>

        <div class="col-xs-12 col-sm-12 col-md-12 dtls_save_full_container">        
            <div class="col-xs-3 col-sm-1 col-md-1 dtls_save_sprtr">
<!--                <a href="#"><img src="<?php echo $this->basePath('/images/dtls_saved_jobs_icon.png'); ?>" alt="saved jobs" id="save_jobs"></a>-->
            </div>
            <div class="col-xs-3 col-sm-4 col-md-4 dtls_save_sprtr">
                <p>Total job opening's:<span class="dtls_total_job"> 3 </span></p>
            </div>
            <div class="col-xs-3 col-sm-4 col-md-4 dtls_save_sprtr">
                <p>jobs posted:<span class="dtls_date_posted_job"> 1 </span> day ago </p>
            </div>
            <div class="clearfix"></div>
        </div>

        <!-- End of dtls_save_full_container -->

        <div class="col-xs-12 col-sm-12 col-md-12 dtls_save_btom_container">
            <div class="col-xs-6 col-sm-3 col-md-3 no_padding_left">
                <p>Job description</p>
            </div>

            <div class="col-xs-6 col-sm-6 col-md-6 dtls_job_share_container pull-right no_right_padding">        
                <a href="#"><img src="<?php echo $this->basePath('/images/social-share-icon.jpg'); ?>" alt="facebook" class="dtls_share_icon" id="facebook" /></a>
                <a href="#"><img src="<?php echo $this->basePath('/images/social-share-icon.jpg'); ?>" alt="Twitter" class="dtls_share_icon" id="twitter" /></a>
                <a href="#"><img src="<?php echo $this->basePath('/images/social-share-icon.jpg'); ?>" alt="Linked in" class="dtls_share_icon" id="linkedin" /></a>
                <p>Send me jobs like this</p>
            </div>
            <div class="clearfix"></div>
        </div>

        <p class="dtls_job_title">Web developer (PHP)</p>
        <p class="dtls_job_responsibility">Responsibilities</p>
        <p> 1. Responsible for controlling Internal defects, Scrap & Internal Audit through CIP.
            2. Ensuring the product & process requirements by conducting internal audits related to
            products and processes
            3. Imparting training & awareness to concerned people for the customer issues and
            problem-solving techniques
            4. Designing and implementing the quality benchmarks to meet customer-specific
            requirements
            5. Responsible for Process Audits & Layout inspection
            6. Ensuring customer interactions and quality issues and handle customer audits to
            track & improve customer PPM & rating
            7. Ensuring Quality system adherence in operations quality.
            8. Supervising & guiding team for Dock, CTQ audits to ensure that the right quality of
            products are being dispatched to the customers
            9. Maintaining daily & Monthly MIS in order to keep everyone updated.
            10. Handling series production changes/PPAP, Handling customer quality and warranty
            issues.</p>


        <p class="dtls_job_qualifications">Qualifications</p>
        <p> 1. Responsible for controlling Internal defects, Scrap & Internal Audit through CIP.<br>
            2. Ensuring the product & process requirements by conducting internal audits related to
            products and processes <br>
            3. Imparting training & awareness to concerned people for the customer issues and
            problem-solving techniques<br>
            4. Designing and implementing the quality benchmarks to meet customer-specific
            requirements </p>
        <p> Responsible for Process Audits & Layout inspection
            6. Ensuring customer interactions and quality issues and handle customer audits to
            track & improve customer PPM & rating
            7. Ensuring Quality system adherence in operations quality.
            8. Supervising & guiding team for Dock, CTQ audits to ensure that the right quality of
            products are being dispatched to the customers
            9. Maintaining daily & Monthly MIS in order to keep everyone updated.
            10. Handling series production changes/PPAP, Handling customer quality and warranty
            issues.</p>
        <p> Responsible for Process Audits & Layout inspection
            6. Ensuring customer interactions and quality issues and handle customer audits to
            track & improve customer PPM & rating
            7. Ensuring Quality system adherence in operations quality.
            8. Supervising & guiding team for Dock, CTQ audits to ensure that the right quality of
            products are being dispatched to the customers
            9. Maintaining daily & Monthly MIS in order to keep everyone updated.
            10. Handling series production changes/PPAP, Handling customer quality and warranty
            issues.</p>



        <div class="col-xs-12 col-sm-12 col-md-12 salary_details_container no_padding_left">

            <div class="col-xs-6 col-sm-3 col-md-3 dtls_salary_left_p no_padding_left">
                <p>Salary:</p>
            </div>
            <div class="col-xs-6 col-sm-9 col-md-9 dtls_salary_right_p">
                <p>Not Disclosed by Recruiter</p>
            </div>


            <div class="col-xs-6 col-sm-3 col-md-3 dtls_salary_left_p no_padding_left">
                <p>Industry:</p>
            </div>
            <div class="col-xs-6 col-sm-9 col-md-9 dtls_salary_right_p">
                <p>Automobile / Auto Anciliary / Auto Components</p>
            </div>


            <div class="col-xs-6 col-sm-3 col-md-3 dtls_salary_left_p no_padding_left">
                <p>Functional Area:</p>
            </div>
            <div class="col-xs-6 col-sm-9 col-md-9 dtls_salary_right_p">
                <p>It Software - Client/server Programming</p>
            </div>


            <div class="col-xs-6 col-sm-3 col-md-3 dtls_salary_left_p no_padding_left">
                <p>Role Category:</p>
            </div>
            <div class="col-xs-6 col-sm-9 col-md-9 dtls_salary_right_p">
                <p>Programming</p>
            </div>


            <div class="col-xs-6 col-sm-3 col-md-3 dtls_salary_left_p no_padding_left">
                <p>Role:</p>
            </div>
            <div class="col-xs-6 col-sm-9 col-md-9 dtls_salary_right_p">
                <p>Software developer</p>
            </div> 
        </div>

        <!--    End of salary_details_container-->

        <div class="dtls_keyskill_container">
            <h3>Keyskills</h3>
            <p>C#</p> 
            <p>Jquery</p>
            <p>Php</p>
            <p>Codeignitor</p>
            <p>MVC framework</p>
            <p>Asp.Net Mvc</p>
            <p>Asp.Net Mvc</p>
            <p>Asp.Net Mvc</p>
            <p>User experience</p>
        </div>

        <div class="clearfix"></div>

        <!--    End of dtls_keyskill_container-->

        <div class="dtls_education_required">
            <h3>Desired Candidate Profile</h3>
            <h4>Education-</h4>
            <p>UG: B.Tech/B.E. - Any Specialization <br/>
                PG:Post Graduation Not Required <br/>
                Doctorate:Doctorate Not Required</p>

        </div>
        <!--End of dtls_education_required-->

        <div class="dtls_company_profile_container">
            <h3>Company Profile:</h3>
            <h4>MAHLE Behr India Pvt. Ltd.</h4>
            <p>As a leading global development partner for the automotive and engine industry, MAHLE offers unique systems competence in the areas of engine systems, filtration, electrics/mechatronics, and thermal management. The MAHLE Group ranks among the top three systems suppliers worldwide for mobile applications in these sectors.
                In the original equipment industry, MAHLE provides technologically innovative solutions for automotive, commercial vehicle, machinery, and other industrial applications. The Aftermarket business unit also serves the independent parts market with MAHLE products in OE quality.
                MAHLE has a local presence in all major world markets. In 2014, some 66,000 employees at approximately 150 production locations generate sales of around EUR ten billion. At ten major research and development centers in Germany, Great Britain, the USA, Brazil, Japan, China, and India, more than 4,500 development engineers and technicians are working on forward-looking concepts, products, and systems</p>
        </div>

        <!--    End of dtls_company_profile_container-->

        <h2 class="dtls_job"><a href="#">View Contact Details</a></h2>

        <div class="dtls_login_btn_container">
            <a href="#" class="btn btn-primary dtls_login" role="button">Login to Apply</a>
            <a href="#" class="btn btn-primary dtls_registar" role="button">Registrar and Apply</a>
        </div> 


    </div>

    <div class="dtls_view_similar_jobs_contner">
        <ul>
            <li><a href="#">View similar jobs</a></li>
            <li><a href="#">View jobs by this company</a></li>
            <li><a href="#">Email this jobs</a></li>
            <li class="no_sprtr"><a href="#">Salaries in Industry</a></li>
        </ul>
        <div class="clearfix"></div>
    </div>
    <!--    End of dtls_view_similar_jobs_contner-->

    <div class="col-xs-12 col-sm-12 col-md-12 no_padding_left no_right_padding">
        <div class="job_details_left_container dtls_similar_job_container">
            <h2>Similar Jobs for You </h2>

            <div class="col-xs-12 col-sm-5 col-md-5 dtls_similar_job_each no_padding_left">
                <h3 class="dtls_job_title"> <a href="#">Web developer (PHP)</a> </h3>
                <h4 class="dtls_company_name">Symantic Software Company ltd</h4>
                <p class="dtls_experience">8-13 yrs</p> 
                <p class="dtls_company_location">Dhaka</p>
                <div class="clearfix"></div>                 

            </div>


            <div class="col-xs-12 col-sm-5 col-md-5 dtls_similar_job_each no_border no_padding_left pull-right">
                <h3 class="dtls_job_title"><a href="#">Web developer (PHP)</a></h3>
                <h4 class="dtls_company_name">Symantic Software Company ltd</h4>
                <p class="dtls_experience">8-13 yrs</p> 
                <p class="dtls_company_location">Dhaka</p>
                <div class="clearfix"></div>                 

            </div>

            <div class="clearfix"></div>


            <div class="col-xs-12 col-sm-5 col-md-5 dtls_similar_job_each no_padding_left">
                <h3 class="dtls_job_title"><a href="#"> Web developer (PHP)</a> </h3>
                <h4 class="dtls_company_name">Symantic Software Company ltd</h4>
                <p class="dtls_experience">8-13 yrs</p> 
                <p class="dtls_company_location">Dhaka</p>
                <div class="clearfix"></div>                 

            </div>


            <div class="col-xs-12 col-sm-5 col-md-5 dtls_similar_job_each no_border no_padding_left pull-right">
                <h3 class="dtls_job_title"><a href="#"> Web developer (PHP)</a> </h3>
                <h4 class="dtls_company_name">Symantic Software Company ltd</h4>
                <p class="dtls_experience">8-13 yrs</p> 
                <p class="dtls_company_location">Dhaka</p>
                <div class="clearfix"></div>                 

            </div>

            <div class="clearfix"></div>

            <div class="dtls_similar_jobs_view_all"><p><a href="#">View All</a></p></div>

            <div class="clearfix"></div>        
        </div> 

        <!--    End of dtls_similar_job_container-->

        <div class="col-xs-12 col-sm-12 col-md-12 no_padding_left no_right_padding">
            <div class="job_details_left_container dtls_add_by_google_container">
                <h2>Adds By Google</h2>
                
                <h3>Public Relations Jobs</h3>
                <p>Staff Wanted. Hiring Now! Public Relations officer</p>
                
                <h3>Public Relations Jobs</h3>
                <p>Staff Wanted. Hiring Now! Public Relations officer.Hiring Now! Public Relations officer</p>
                
                <h3>Public Relations Jobs</h3>
                <p>Staff Wanted. Hiring Now! Public Relations officer</p>
            </div> 

            <!--    End of dtls_similar_job_container-->



        </div>







    </div>

</div>

<div class="col-xs-12 col-sm-4 col-md-4 job_details_right_container">
    <div class="common_google_ads ad_right">
        <img src="<?php echo $this->basePath('/images/dtls_right_ad_300_600.jpg'); ?>" alt="ad" class="center-block img-responsive">
    </div>
    
    <div class="common_google_ads">
        <img src="<?php echo $this->basePath('/images/dtls_right_ad_300_250.jpg'); ?>" alt="ad" class="center-block img-responsive">
    </div>
    
</div>