<html>
    <head>
    <style type="text/css">
		body {
			margin:0 auto;
			padding:0;
		}
		@media only screen and (max-width:481px){				
			table[class=first_tbl]{
				width:420px !important;				
			}
			
			table[class=footer_first_item]{
				width:47% !important;
				display:inline-block !important;
				padding-bottom:10px !important;	
				padding-right:6px !important;		
				
			}
			
			table[class=footer_second_item]{
				width:47% !important;
				display:inline-block !important;
				padding-bottom:10px !important;
			}
			
			table[class=footer_third_item]{
				width:47% !important;
				display:inline-block !important;
				padding-bottom:10px !important;
				padding-right:6px !important;
			}
			
			table[class=footer_fourth_item]{
				width:47% !important;
				display:inline-block !important;
				padding-bottom:10px !important;
			}
				
				
				
		}

 
	</style>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Untitled Document</title>
    </head>
        <body bgcolor="#ffffff">
        <table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#ffffff" style="table-layout:fixed">
          <tr>
            <td>            
                <table class="first_tbl" align="center" bgcolor="#e3e3e3" width="640" border="0" cellspacing="0" cellpadding="0">
                    <tr>
                    <td valign="top" align="center" >
                    
                    <table width="610" border="0" cellspacing="0" cellpadding="0" align="center">
                      <tr>
                        <td align="left" valign="top" style="padding:1px 0 15px 0px;">     
                    
                    
                        <table width="256" border="0" cellspacing="0" cellpadding="0" align="right">
                        <tr>
                            <td><a href="#"><img src="http://paimages.prothom-alo.com/contents/uploads/media/2015/05/21/678cebf46446ce305f45824ca077f545-chakri-recruiter.jpg" width="256" height="52" alt=""></a></td>
                          </tr>
                      </table></td>
                  </tr>
                    
                   
                  
                    <tr>
                    <td align="left" valign="top" bgcolor="#ffffff" style="padding: 18px 12px 25px;">
                    
                    
                            <p style="font-family:Arial, Helvetica, sans-serif; font-size:13px; margin:0; padding:0; line-height:20px;">Dear <?php echo $this->email;?><br>
                            Please verify emailto activate your  account instantly.<br>
                            <p align="center"><a href="<?php echo $this->serverUrl();?>/registration/activate/<?php echo $this->activation_code;?>" style="border:none"><img src="http://paimages.prothom-alo.com/contents/uploads/media/2015/05/21/f27bdec26b2ade0c36f64e1d9af6ca90-verify_email_btn.jpg" width="170" height="39" alt="" border="0"></a></p>
                            <p style="font-family:Arial, Helvetica, sans-serif; font-size:13px; color:#7e7e7e;">Note: This link will be functional  for 72 hours and can only be used once.</p>
                            <p style="font-family:Arial, Helvetica, sans-serif; font-size:13px; margin:0; padding:0; line-height:20px;">Regards,<br>
                            ChakriRecruiter Team<br>
                            <br>
                            You can receiving this mail because  <?php echo $this->full_name; ?> was used to create an account on ChakriRecruiter. If you did not create this account, or created it unintentionally,  you can delete it.<br>
                          </p>
                          </td>
                  </tr>
                    
                    <tr>
                    <td align="left" valign="top" style="padding:15px 0 15px 8px;">
                    
                    <p style="color:#525257; font-weight:bold; font-family:Arial, Helvetica, sans-serif; font-size:13px; padding: 3px 0 5px 0px; margin: 0;">You can reach us at</p>
                    	<table class="footer_first_item" width="144" border="0" cellspacing="0" cellpadding="0" align="left">
                            <tr>
                            <td align="left" valign="top" ><p style="color:#5C5C5C; font-weight:bold; font-family:Arial, Helvetica, sans-serif; font-size:11px; margin: 0;  background:url(http://paimages.prothom-alo.com/contents/uploads/media/2015/05/23/380a0ee8cb29338693c376e0680bca20-phone-icon.jpg) no-repeat left 5px; padding:0px 0px 9px 29px;"> 01922 626 056 <br/>
                                01916 832 507 </p></td>
                          </tr>
                          </table>
                            <table class="footer_second_item" width="144" border="0" cellspacing="0" cellpadding="0" align="left">
                            <tr>
                                <td align="left" valign="top"><p style="font-weight:bold; font-family:Arial, Helvetica, sans-serif; font-size:11px;margin: 0;  background:url(http://www.prothom-alojobs.com/upload/test/newsletter/support.png) no-repeat left 0px; padding:0px 20px 12px 21px;"> <a href="mailto:support@chakri.com" style="text-decoration:none;color:#0E609B">support@chakri.com</a></p></td>
                              </tr>
                          </table>
                          
                            <table class="footer_third_item" width="144" border="0" cellspacing="0" cellpadding="0" align="left">
                            <tr>
                                <td align="left" valign="top"><p style="font-weight:bold; font-family:Arial, Helvetica, sans-serif; font-size:11px;  margin: 0;  background:url(http://www.prothom-alojobs.com/upload/test/newsletter/home.gif) no-repeat left 0px; padding:0px 0px 12px 18px;"> <a href="#" style="text-decoration:none;color:#0E609B">Our Branches</a></p></td>
                              </tr>
                          </table>
                            <table class="footer_fourth_item" width="144" border="0" cellspacing="0" cellpadding="0" align="left">
                            <tr>
                                <td align="left" valign="top"><p style="font-weight:bold; font-family:Arial, Helvetica, sans-serif; font-size:11px;  margin: 0;  background:url(http://www.prothom-alojobs.com/upload/test/newsletter/bell.png) no-repeat left 0px; padding:0px 0px 12px 21px;"> <a href="#" style="text-decoration:none;color:#0E609B;">Report a Problem </a></p></td>
                              </tr>
                          </table> 
                          <br style="clear:both;" />
                          </td>
                      </tr>
                    </table>
                      
                      
                      
                      </td>
                  </tr>
                  </table></td>
          </tr>
        </table>
</body>
</html>