<!DOCTYPE HTML>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>Untitled Document</title>
        <style type="text/css">	
            body{
                margin:0;
                padding:0;
                background:#bfbfbf;
            }

            @media only screen and (max-width:660px){

                table[class=first_tbl]{
                    width:100% !important;
                    display:block !important;
                }
            }

            @media only screen and (max-width:420px){

                table[class = "footer_first_item"] p{
                    width:100% !important;
                    display:block !important;
                    font-size:13px !important;
                }
                table[class = "footer_second_item"]{
                    width:100% !important;
                    display:block !important;	
                    padding-left:26px !important;				
                }
                table[class = "footer_second_item"] p{                    
                    font-size:13px !important;
                }
                table[class = "footer_third_item"]{
                    width:100% !important;
                    display:block !important;
                    padding-left:26px !important;

                }
                table[class = "footer_third_item"] p{                    
                    font-size:13px !important;
                }
            }



        </style>
    </head>

    <body bgcolor="#bfbfbf" style="background:#bfbfbf;">
        <table width="100%" border="0" cellspacing="0" cellpadding="0" style="background-color:#bfbfbf;">
            <tr>
                <td>

                    <table width="650" border="0" align="center" cellpadding="0" cellspacing="0" class="first_tbl">
                        <tr bgcolor="#ffffff">
                            <td>&nbsp;</td>
                            <td align="center" valign="top"><p style="font-family:Arial, Helvetica, sans-serif; font-size:12px; color:#333; line-height:16px; padding:8px; text-align:center; margin:0;">To ensure delivery to inbox, add <span style="color:#2f88dc;"><a href="#" style="color:#2f88dc; text-decoration:none;" >no-reply@chakri.com</a></span> to your address book.<br/>
                                    If you're having trouble viewing this email <span style="color:#2f88dc;"><a href="#" style="color:#2f88dc; text-decoration:none;" >click here</a></span></p></td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr bgcolor="#eeeeee">
                            <td width="40">&nbsp;</td>
                            <td width="560" align="left" valign="top">
                                <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                    <tr>
                                        <td align="left" valign="top"></td>
                                    </tr>
                                    <tr>
                                        <td align="left" valign="top" style="padding-top:25px;">
                                            <a href="#"><img src="http://www.prothom-alojobs.com/upload/test/newsletter/chakri.png" width="231" height="84" alt="Chakri"></a>
                                            <p style="font-family:Arial, Helvetica, sans-serif; font-size:17px; color:#3f3f3f; padding: 32px 0 0 0; margin:0;">Dear <strong> &ldquo;<?php echo $this->full_name; ?>&rdquo;,</strong></p>
                                            <p style="font-family:Arial, Helvetica, sans-serif; font-size:17px; color:#3f3f3f; line-height:22px; margin:0; padding: 22px 0 20px 0;">We're sending this email because we received a request from you to change your password.
                                                <br>
                                                (If you did not make this request, please ignore this email.) <br>
                                                To change your password, click the link below</p>
                                            <p style="font-family:Arial, Helvetica, sans-serif; font-size:17px; font-weight:bold; margin:0;">
                                                <a href="<?php echo $this->serverUrl(); ?>/changepassword/<?php echo $this->activation_code; ?>" style="text-decoration:none; color:#fff;display:block;padding:11px 35px;background-color:#f67a20;width:194px;">Change Your Password</a>
                                            </p>
                                            <p style="font-family:Arial, Helvetica, sans-serif; font-size:17px; color:#3f3f3f; line-height:22px; margin:0; padding: 22px 0 0 0; ">Once you change your password, be sure to keep it  secure. Never disclose your password to anyone, and never respond to an email  asking for your password Information. Even from Chakri.com Team.</p>
                                            <p style="font-family:Arial, Helvetica, sans-serif; font-size:17px; color:#3f3f3f; line-height:22px; padding: 22px 0 0 0; margin:0;">Regards,<br>
                                                The Chakri.com Team</span><br>
                                            </p>
                                            <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" style="padding: 36px 0 0 0;">
                                                <tr>
                                                    <td align="left" valign="top"><table class="footer_first_item" width="215" border="0" cellspacing="0" cellpadding="0" align="left">
                                                            <tr>
                                                                <td width="163" align="left" valign="top" ><p style="color:#1b99d4; font-weight:normal; font-family:Arial, Helvetica, sans-serif; font-size:16px; padding: 0; margin: 0;  background:url(http://www.prothom-alojobs.com/upload/test/newsletter/phn_icon.jpg) no-repeat left -10px; padding:8px 0px 9px 40px; "> <span style="">You can reach us at <br/>
                                                                            +8801922 626 056 <br/>
                                                                            +8801674 894 347 </span></p></td>
                                                            </tr>
                                                        </table>
                                                        <table width="220" border="0" align="left" cellpadding="0" cellspacing="0" class="footer_second_item" >
                                                            <tr>
                                                                <td align="left" valign="top"><p style="font-weight:normal; font-family:Arial, Helvetica, sans-serif; font-size:16px; padding: 0; margin: 0;  background:url(http://www.prothom-alojobs.com/upload/test/newsletter/env.jpg) no-repeat 2px; padding:13px 0px 12px 24px;"> <a href="mailto:service@chakri.com" style="text-decoration:none;"><span style="color:#1b99d4;">service@chakri.com</span></a></p></td>
                                                            </tr>
                                                        </table>
                                                        <table class="footer_third_item" width="132" border="0" cellspacing="0" cellpadding="0" align="left">
                                                            <tr>
                                                                <td align="left" valign="top"><p style="font-weight:normal; font-family:Arial, Helvetica, sans-serif; font-size:16px; padding: 0; margin: 0;   padding:13px 0px 12px 5px;"> <a href="http://dev1.chakri.com/contact" target="_blank"style="text-decoration:none;"><span style="color:#1b99d4;"><u>Report a Problem</u></span></a></p></td>
                                                            </tr>
                                                        </table></td>
                                                </tr>
                                            </table>
                                            <p style="font-family:Arial, Helvetica, sans-serif; font-size:12px;color:#9b9b9b; padding: 22px 0 14px 0; margin:0;" align="center">Top stop receiving mails from us <a href="http://dev1.chakri.com/contact" target="_blank" style="color:#545454; text-decoration:none;">unsubsribe</a></p>
                                        </td>
                                    </tr>
                                </table>
                            </td>
                            <td width="40">&nbsp;</td>
                        </tr>
                    </table></td></tr></table>
    </body>
</html>
