<!DOCTYPE html>
<html>
    <head>
    <style type="text/css">
		body {
			margin:0 auto;
			padding:0;
		}
		@media only screen and (max-width:481px){				
			table[class=first_tbl]{
				width:420px !important;				
			}
			
			table[class=footer_first_item]{
				width:47% !important;
				display:inline-block !important;
				padding-bottom:10px !important;	
				padding-right:6px !important;		
				
			}
			
			table[class=footer_second_item]{
				width:47% !important;
				display:inline-block !important;
				padding-bottom:10px !important;
			}
			
			table[class=footer_third_item]{
				width:47% !important;
				display:inline-block !important;
				padding-bottom:10px !important;
				padding-right:6px !important;
			}
			
			table[class=footer_fourth_item]{
				width:47% !important;
				display:inline-block !important;
				padding-bottom:10px !important;
			}
				
				
				
		}

 
	</style>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Untitled Document</title>
    </head>
        <body bgcolor="#ffffff">
        <table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#ffffff" style="table-layout:fixed">
          <tr>
            <td>            
                <table class="first_tbl" align="center" bgcolor="#e3e3e3" width="640" border="0" cellspacing="0" cellpadding="0">
                    <tr>
                    <td valign="top" align="center" >
                    
                    <table width="610" border="0" cellspacing="0" cellpadding="0" align="center">
                      <tr>
                        <td align="left" valign="top" style="padding:1px 0 15px 0px;">     
                    
                    
                        <table width="256" border="0" cellspacing="0" cellpadding="0" align="right">
                        <tr>
                            <td><a href="#"><img src="http://paimages.prothom-alo.com/contents/uploads/media/2015/05/21/678cebf46446ce305f45824ca077f545-chakri-recruiter.jpg" width="256" height="52" alt=""></a></td>
                          </tr>
                      </table></td>
                  </tr>
                    
                   
                  
                    <tr>
                    <td align="left" valign="top" bgcolor="#ffffff" style="padding: 18px 12px 25px;">
                    
                    
                            <p style="font-family:Arial, Helvetica, sans-serif; font-size:13px; margin:0; padding:0; line-height:19px;">
                            
                            
                            Welcome to Chakri.com, <?php echo $this->full_name;?><br>
			<div style="font-family:Arial, Helvetica, sans-serif; font-size:13px; margin:0; padding:0; line-height:19px;text-align:center; font-size:14px;"><strong>Welcome to Chakri.com</strong></div>
			<hr />
            
            <table width="99%">
				<tr>
					
					<td width="92%"><h2 style="font-size:18px; color:#269cc2;font-family:Arial, Helvetica, sans-serif; margin:0; padding:0; line-height:24px; background:url(http://www.prothom-alojobs.com/upload/test/newsletter/1.jpg) no-repeat left 0px;padding-left:42px;padding-bottom: 6px;">Create Your CV</h2>
                    <p style="font-family:Arial, Helvetica, sans-serif; font-size:13px; margin:0; padding:0; line-height:19px; padding-left:41px;">Use Chakri.com's CV Editor to create  a professional and effective CV.</td>
					<td width="7%" rowspan="2" align="left" valign="top"><img src="http://www.prothom-alojobs.com/upload/test/newsletter/arrow.jpg" width="23" height="36" alt=""></td>
				</tr>
				
			</table>		
			<hr />            
            <table width="99%">
				<tr>
					
					<td width="92%"><h2 style="font-size:18px; color:#269cc2;font-family:Arial, Helvetica, sans-serif; margin:0; padding:0; line-height:24px; background:url(http://www.prothom-alojobs.com/upload/test/newsletter/2.jpg) no-repeat left 0px;padding-left:42px;padding-bottom: 6px;">Find Jobs</h2>
                    <p style="font-family:Arial, Helvetica, sans-serif; font-size:13px; margin:0; padding:0; line-height:19px; padding-left:41px;">With over 40,000 employers on Chakri.com,you have thousands of jobs to choose from.</td>
					<td width="7%" rowspan="2" align="left" valign="top"><img src="http://www.prothom-alojobs.com/upload/test/newsletter/arrow.jpg" width="23" height="36" alt=""></td>
				</tr>
				
			</table>		
			<hr />
            
            <table width="99%">
				<tr>
					
					<td width="92%"><h2 style="font-size:18px; color:#269cc2;font-family:Arial, Helvetica, sans-serif; margin:0; padding:0; line-height:24px; background:url(http://www.prothom-alojobs.com/upload/test/newsletter/3.jpg) no-repeat left 0px;padding-left:42px;padding-bottom: 6px;">Use Your Dashboard to Manage Your Applications</h2>
                    <p style="font-family:Arial, Helvetica, sans-serif; font-size:13px; margin:0; padding:0; line-height:19px; padding-left:41px;">The Dashboard is designed to keep you on track with all of your applications.</td>
					<td width="7%" rowspan="2" align="left" valign="top"><img src="http://www.prothom-alojobs.com/upload/test/newsletter/arrow.jpg" width="23" height="36" alt=""></td>
				</tr>
				
			</table>       
            
			           
			<hr />
            
            <table width="99%">
				<tr>
					
					<td width="92%"><h2 style="font-size:18px; color:#269cc2;font-family:Arial, Helvetica, sans-serif; margin:0; padding:0; line-height:24px; background:url(http://www.prothom-alojobs.com/upload/test/newsletter/4.jpg) no-repeat left 0px;padding-left:42px;padding-bottom: 6px;">Get an Email when the Job is perfect for you</h2>
                    <p style="font-family:Arial, Helvetica, sans-serif; font-size:13px; margin:0; padding:0; line-height:19px; padding-left:41px;">Create a "Job Alert" and we will send you relevant job postings to your email when employers post them.</td>
					<td width="7%" rowspan="2" align="left" valign="top"><img src="http://www.prothom-alojobs.com/upload/test/newsletter/arrow.jpg" width="23" height="36" alt=""></td>
				</tr>
				
			</table>		
            
			<hr />
            
			<table width="99%">
				<tr>
					
					<td width="92%"><h2 style="font-size:18px; color:#269cc2;font-family:Arial, Helvetica, sans-serif; margin:0; padding:0; line-height:24px; background:url(http://www.prothom-alojobs.com/upload/test/newsletter/5.jpg) no-repeat left 0px;padding-left:42px;padding-bottom: 5px;">Engage with Specialists Like Yourself, Shine and Get Noticed!</h2>
                    <p style="font-family:Arial, Helvetica, sans-serif; font-size:13px; margin:0; padding:0; line-height:19px; padding-left:41px;">Chakri.com Specialties is a great way to find answers to your career questions, network, and shine!</td>
					<td width="7%" rowspan="2" align="left" valign="top"><img src="http://www.prothom-alojobs.com/upload/test/newsletter/arrow.jpg" width="23" height="36" alt=""></td>
				</tr>
				
			</table>
            
			<p style="text-align:center">
            	<a href="#"><img src="http://paimages.prothom-alo.com/contents/uploads/media/2015/05/21/1f602e9fc59f5f1fea5500ffe869be12-premium_image.jpg" alt="Premium" width="92" height="92" /></a>
           	</p>                
                <p style="text-align:center"><a href="#"><img src="http://paimages.prothom-alo.com/contents/uploads/media/2015/05/21/747f0e44c207a6087213a40f7379d586-upgrade_now.jpg" alt="upgrade" width="145" height="44" /></a></p>      
                           
                 	 </td>
                  </tr>
                    
                    <tr>
                    <td align="left" valign="top" style="padding:15px 0 15px 8px;">
                    
                    <p style="color:#525257; font-weight:bold; font-family:Arial, Helvetica, sans-serif; font-size:13px; padding: 3px 0 5px 0px; margin: 0;">You can reach us at</p>
                    	<table class="footer_first_item" width="144" border="0" cellspacing="0" cellpadding="0" align="left">
                            <tr>
                            <td align="left" valign="top" ><p style="color:#5C5C5C; font-weight:bold; font-family:Arial, Helvetica, sans-serif; font-size:11px; margin: 0;  background:url(http://paimages.prothom-alo.com/contents/uploads/media/2015/05/23/380a0ee8cb29338693c376e0680bca20-phone-icon.jpg) no-repeat left 5px; padding:0px 0px 9px 29px;"> 01922 626 056 <br/>
                                01916 832 507 </p></td>
                          </tr>
                          </table>
                            <table class="footer_second_item" width="144" border="0" cellspacing="0" cellpadding="0" align="left">
                            <tr>
                                <td align="left" valign="top"><p style="font-weight:bold; font-family:Arial, Helvetica, sans-serif; font-size:11px;margin: 0;  background:url(http://www.prothom-alojobs.com/upload/test/newsletter/support.png) no-repeat left 0px; padding:0px 20px 12px 21px;"> <a href="mailto:support@chakri.com" style="text-decoration:none;color:#0E609B">support@chakri.com</a></p></td>
                              </tr>
                          </table>
                          
                            <table class="footer_third_item" width="144" border="0" cellspacing="0" cellpadding="0" align="left">
                            <tr>
                                <td align="left" valign="top"><p style="font-weight:bold; font-family:Arial, Helvetica, sans-serif; font-size:11px;  margin: 0;  background:url(http://www.prothom-alojobs.com/upload/test/newsletter/home.gif) no-repeat left 0px; padding:0px 0px 12px 18px;"> <a href="#" style="text-decoration:none;color:#0E609B">Our Branches</a></p></td>
                              </tr>
                          </table>
                            <table class="footer_fourth_item" width="144" border="0" cellspacing="0" cellpadding="0" align="left">
                            <tr>
                                <td align="left" valign="top"><p style="font-weight:bold; font-family:Arial, Helvetica, sans-serif; font-size:11px;  margin: 0;  background:url(http://www.prothom-alojobs.com/upload/test/newsletter/bell.png) no-repeat left 0px; padding:0px 0px 12px 21px;"> <a href="#" style="text-decoration:none;color:#0E609B;">Report a Problem </a></p></td>
                              </tr>
                          </table> 
                          <br style="clear:both;" />
                          </td>
                      </tr>
                    </table>
                      
                      
                      
                      </td>
                  </tr>
                  </table></td>
          </tr>
        </table>
</body>
</html>