<section class="content">
<div class="govt_job_ad_form_container box box-default admin_form_bg">
    <form role="form" data-toggle="validator" class="form-horizontal register_employer_form" method="post" enctype="multipart/form-data">
        <div class="box-body">
<?php   if(count($error_messages)){?>
            <div class="box box-solid alert-error">
                <div class="box-tools pull-right">
                    <button data-widget="remove" class="btn btn-box-tool text-gray"><i class="fa fa-times"></i></button>                    
                </div>
                <div class="box-body">
<?php
                foreach($error_messages as $msg)
                    echo $msg;
?>
                </div>
            </div>
<?php   }?>
            <h1>Add Event</h1>
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Event Title: <span class="valid_star">*</span></label>
                <div class="col-sm-5 col-md-5">
                    <input type="text" class="form-control" id="event_title" name="event_title" placeholder="Event Title" value="<?php echo ($this->post_data->event_title ? $this->post_data->event_title : "");?>" required />
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Event Conduct By:</label>
                <div class="col-sm-5 col-md-5">
                    <input type="text" class="form-control" id="event_conduct" name="event_conduct_by" placeholder="Event Conduct By"  value="<?php echo ($this->post_data->event_conduct_by ? $this->post_data->event_conduct_by : "");?>">
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Details:</label>
                <div class="col-sm-10 col-md-10">
                    <textarea id="details" name="details" rows="8" cols="80"><?php echo ($this->post_data->details ? $this->post_data->details : "");?></textarea>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Objectives / Benefits:</label>
                <div class="col-sm-10 col-md-10">
                    <textarea id="benefits" name="benefits" rows="8" cols="80"><?php echo ($this->post_data->benefits ? $this->post_data->benefits : "");?></textarea>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Event Logo:<span class="valid_star"> * </span></label>
                <div class="col-sm-5 col-md-5">
                    <input type="file" id="event_logo" name="event_logo" required> <span>Maximum upload file size: width:900px and height:100px. File types allowed: jpg, jpeg, gif only.</span>               
                </div>
                <div class="clearfix"></div>
            </div>
    <!--        <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Event Banner:</label>
                <div class="col-sm-5 col-md-5">
                    <input type="file" id="event_banner" name="event_banner">                
                </div>
                <div class="clearfix"></div>
            </div>-->
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">URL:</label>
                <div class="col-sm-5 col-md-5">
                    <input type="url" class="form-control" id="url" name="url" placeholder="URL" value="<?php echo ($this->post_data->url ? $this->post_data->url : "");?>" />
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Program Type: <span class="valid_star">*</span></label>
                <div class="col-sm-5 col-md-5">
                    <input type="text" class="form-control" id="program_type" name="program_type" placeholder="Program Type" required value="<?php echo ($this->post_data->program_type ? $this->post_data->program_type : "");?>">
                </div>
                <div class="clearfix"></div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Venue: <span class="valid_star">*</span></label>
                <div class="col-sm-5 col-md-5">
                    <input type="text" class="form-control" id="venue" name="venue" placeholder="Venue" required value="<?php echo ($this->post_data->venue ? $this->post_data->venue : "");?>">
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Event Date: <span class="valid_star">*</span></label>
                <div class="col-sm-5 col-md-5">
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-calendar"></i>
                        </div>
                        <input type="text" name="event_date" value="<?php echo ($this->post_data->event_date ? $this->post_data->event_date : "");?>" class="form-control" data-inputmask="'alias': 'yyyy-mm-dd'" required data-mask/>
                    </div>                
                </div>

                <div class="clearfix"></div>
            </div>
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Event Expire Date:</label>
                <div class="col-sm-5 col-md-5">
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-calendar"></i>
                        </div>
                        <input type="text" name="event_expire_date" value="<?php echo ($this->post_data->event_expire_date ? $this->post_data->event_expire_date : "");?>" class="form-control" data-inputmask="'alias': 'yyyy-mm-dd'" data-mask />
                    </div>                
                </div>

                <div class="clearfix"></div>
            </div>
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Event Last Registration Date:</label>
                <div class="col-sm-5 col-md-5">
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-calendar"></i>
                        </div>
                        <input type="text" name="lastRegiDate" value="<?php echo ($this->post_data->lastRegiDate ? $this->post_data->lastRegiDate : "");?>" class="form-control" data-inputmask="'alias': 'yyyy-mm-dd'" data-mask/>
                    </div>                
                </div>

                <div class="clearfix"></div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 col-md-2 control-label">Is Active?</label>
                <div class="col-sm-5 col-md-5">
                    <label>
                        <input type="radio" name="status" value="1" class="minimal" <?php echo ($this->post_data->status==1 ? "checked" : "");?> />Yes
                    </label>
                    <label>
                        <input type="radio" name="status" value="0" class="minimal" <?php echo ($this->post_data->status==0 ? "checked" : "");?> />No
                    </label>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="form-group">
                <div class=" col-xs-12 col-sm-6 col-md-6 col-sm-offset-2 col-md-offset-2 btn_submit">
                    <button type="submit" class="btn btn-primary pull-left">Submit</button>&nbsp;
                    <a class="btn btn-default" href="<?php echo $this->serverUrl()."/admin/event";?>" role="button">Back</a>
                </div>                                            
            </div>            
            <div class="clearfix"></div>
        </div>
    </form>
</div>
</section>

<script type="text/javascript">
    
        $(function(){
            
         //Datemask dd/mm/yyyy
        $("#datemask").inputmask("dd/mm/yyyy", {"placeholder": "dd/mm/yyyy"});
        //Datemask2 mm/dd/yyyy
        $("#datemask2").inputmask("dd/mm/yyyy", {"placeholder": "dd/mm/yyyy"});
        //Money Euro
        $("[data-mask]").inputmask();
        // Replace the <textarea id="editor1"> with a CKEditor
        // instance, using default configuration.
        CKEDITOR.replace('details');
        CKEDITOR.replace('benefits');
        //$(".textarea").wysihtml5();
        
        
        CKEDITOR.replace('details', {
            filebrowserBrowseUrl: '/ckfinder/ckfinder.html',
            filebrowserImageBrowseUrl: '/ckfinder/ckfinder.html',
            filebrowserFlashBrowseUrl: '/ckfinder/ckfinder.html',
            filebrowserUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload',
            filebrowserImageUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload',
            filebrowserFlashUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload'
        });
       
       });  
  

</script>