<section class="content">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Edit Event</h3>
        </div>
        <?php if ($this->flashMessenger()->hasCurrentErrorMessages()) { ?>
            <div class="box box-solid alert-error">
                <div class="box-tools pull-right">
                    <button data-widget="remove" class="btn btn-box-tool text-gray"><i class="fa fa-times"></i></button>                    
                </div>
                <div class="box-body"><?php echo $this->flashMessenger()->render('error'); ?></div>
            </div>
        <?php } ?>
        <form data-toggle="validator" role="form" method="post" class="form-horizontal register_employer_form" enctype="multipart/form-data" >
            <div class="box-body">
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Event Title:<span class="valid_star"> * </span></label>
                    <div class="col-sm-5 col-md-5">
                        <input type="text" class="form-control" id="event_title" name="event_title" placeholder="Event Title" value="<?php echo $this->event->event_title; ?>" required />
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Event Conduct By:</label>
                    <div class="col-sm-5 col-md-5">
                        <input type="text" class="form-control" id="event_conduct" name="event_conduct_by" placeholder="Event Conduct By"  value="<?php echo $this->event->event_conduct_by; ?>">
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 col-md-2 control-label"> Details:</label>
                    <div class="col-sm-10 col-md-10">
                        <textarea id="details" name="details" rows="8" cols="80"><?php echo $this->event->details; ?></textarea>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 col-md-2 control-label"> Objectives / Benefits :</label>
                    <div class="col-sm-10 col-md-10">
                        <textarea id="benefits" name="benefits" rows="8" cols="80"><?php echo $this->event->benefits; ?></textarea>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Event Logo:</label>
                    <div class="col-sm-5 col-md-5">
                        <input type="file" id="event_logo" name="event_logo" value="<?php echo $this->event->event_logo; ?>"> <span>Maximum upload file size: width:900px and height:100px. File types allowed: jpg, jpeg, gif only.</span>               
                    </div>
                    <div class="clearfix"></div>
                </div>
                <!--        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Event Banner:</label>
                            <div class="col-sm-5 col-md-5">
                                <input type="file" id="event_banner" name="event_banner" value="<?php echo $this->event->event_banner; ?>">                
                            </div>
                            <div class="clearfix"></div>
                        </div>-->
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">URL:</label>
                    <div class="col-sm-5 col-md-5">
                        <input type="text" class="form-control" id="url" name="url" placeholder="URL" value="<?php echo $this->event->url; ?>" />
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 col-md-2 control-label"> Program Type: <span class="valid_star"> * </span></label>
                    <div class="col-sm-5 col-md-5">
                        <input type="text" class="form-control" id="program_type" name="program_type" placeholder="Program Type" required value="<?php echo $this->event->program_type; ?>">
                    </div>
                    <div class="clearfix"></div>
                </div>

                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">  Venue : <span class="valid_star"> * </span></label>
                    <div class="col-sm-5 col-md-5">
                        <input type="text" class="form-control" id="venue" name="venue" placeholder="Venue" required value="<?php echo $this->event->venue; ?>">
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 col-md-2 control-label"> Event Date:</label>
                    <div class="col-sm-5 col-md-5">
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-calendar"></i>
                            </div>
                            <input type="text" name="event_date" value="<?php echo $this->event->event_date; ?>" class="form-control" data-inputmask="'alias': 'yyyy-mm-dd'" data-mask/>
                        </div>                
                    </div>

                    <div class="clearfix"></div>
                </div>
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 col-md-2 control-label"> Event Expire Date:</label>
                    <div class="col-sm-5 col-md-5">
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-calendar"></i>
                            </div>
                            <input type="text" name="event_expire_date" value="<?php echo $this->event->event_expire_date; ?>" class="form-control" data-inputmask="'alias': 'yyyy-mm-dd'" data-mask/>
                        </div>                
                    </div>

                    <div class="clearfix"></div>
                </div>
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 col-md-2 control-label"> Event Last Registration Date:</label>
                    <div class="col-sm-5 col-md-5">
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-calendar"></i>
                            </div>
                            <input type="text" name="lastRegiDate" value="<?php echo $this->event->lastRegiDate; ?>" class="form-control" data-inputmask="'alias': 'yyyy-mm-dd'" data-mask/>
                        </div>                
                    </div>

                    <div class="clearfix"></div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 col-md-2 control-label">Is Active?</label>
                    <div class="col-sm-5 col-md-5">
                        <label>
                            <input type="radio" name="status" value="1"  class="minimal" <?php echo ($this->event->status == "1") ? 'checked' : ''; ?>  />Yes
                        </label>
                        <label>
                            <input type="radio" name="status" value="0" class="minimal" <?php echo ($this->event->status == "0") ? 'checked' : ''; ?> />No
                        </label>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Update</button>
                    <a class="btn btn-default" href="<?php echo $this->serverUrl() . "/admin/event"; ?>" role="button">Back</a>
                </div>
            </div>
        </form>
    </div>
</section>

<script type="text/javascript">

    $(function () {

        //Datemask dd/mm/yyyy
        $("#datemask").inputmask("dd/mm/yyyy", {"placeholder": "dd/mm/yyyy"});
        //Datemask2 mm/dd/yyyy
        $("#datemask2").inputmask("dd/mm/yyyy", {"placeholder": "dd/mm/yyyy"});
        //Money Euro
        $("[data-mask]").inputmask();
        // Replace the <textarea id="editor1"> with a CKEditor
        // instance, using default configuration.
        CKEDITOR.replace('details');
        CKEDITOR.replace('benefits');
        //$(".textarea").wysihtml5();


        CKEDITOR.replace('details', {
            filebrowserBrowseUrl: '/ckfinder/ckfinder.html',
            filebrowserImageBrowseUrl: '/ckfinder/ckfinder.html',
            filebrowserFlashBrowseUrl: '/ckfinder/ckfinder.html',
            filebrowserUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload',
            filebrowserImageUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload',
            filebrowserFlashUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload'
        });

    });


</script>