<section class="content">
<div class="govt_job_ad_form_container box box-default admin_form_bg">
    <form name='newjobpost' role="form" data-toggle="validator" class="form-horizontal register_employer_form" method="post" enctype="multipart/form-data">

        <h1>Add/Edit Job</h1>
        
            <?php 
            if (count($this->error_messages) > 0) { ?>
            <div class="alert alert-danger">
                <?php                                 
                foreach ($this->error_messages as $messageId => $message) {                        
                        echo "<p>  $message </p>";           
                }
                ?>   
            </div> 
            <?php } ?>

            <?php if (count($this->success_messages) > 0) { ?>
            <div class="alert alert-success">
                <?php
                foreach ($this->success_messages as $messageId => $message) {
                    echo "<p>  $message </p>";
                }
                ?>   
            </div>
            <?php } ?>
        
        <div class="form-group">
            <label for="job_title" class="col-sm-2 col-md-2 control-label">Job Title:<span class="valid_star"> *</span></label>
            <div class="col-sm-5 col-md-5">
                <input type="text" class="form-control" id="job_title" name="job_title" required placeholder="Job title" value="<?php echo ($this->post_data["job_title"] != "") ? $this->post_data["job_title"] : $this->results->job_title; ?>" autofocus />
            </div>
            <div class="clearfix"></div>
        </div>
        
        <div class="form-group">
            <label for="no_of_vacencies" class="col-sm-2 col-md-2 control-label">   No of Vacancies: </label>
            <div class="col-sm-5 col-md-5">
                <input type="text" class="form-control" id="no_of_vacencies" name="no_of_vacencies" placeholder="Enter Number of vacancies" value="<?php echo ($this->post_data["no_of_vacencies"] != "") ? $this->post_data["no_of_vacencies"] : $this->results->no_of_vacencies; ?>">
            </div>
            <div class="clearfix"></div>
        </div>
        
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Job Location:<span class="valid_star"> *</span> </label>
            <div class="col-sm-5 col-md-5">
                <label><input type="radio" required name="job_location" value="Within Bangladesh" class="iradio_minimal-blue minimal" style="background-color: #006dcc !important" onclick="return show_location();" id="jobLocation_1" <?php echo ($this->post_data["job_location"] == "Within Bangladesh") ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["job_location"]) && ($this->results->job_location == "Within Bangladesh")) ? 'checked=""' : ''; ?> checked/>Within Bangladesh</label>
                <label><input type="radio" required name="job_location" value="Outside Bangladesh" class="iradio_minimal-blue minimal" onclick="return  show_location();" id="jobLocation_2" <?php echo ($this->post_data["job_location"] == "Outside Bangladesh") ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["job_location"]) && ($this->results->job_location == "Outside Bangladesh")) ? 'checked=""' : ''; ?> />Outside Bangladesh</label>
                <label><input type="radio" required name="job_location" value="Other" class="iradio_minimal-blue minimal" onclick="return show_location();" id="jobLocation_3" <?php echo ($this->post_data["job_location"] == "Other") ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["job_location"]) && ($this->results->job_location == "Other")) ? 'checked=""' : ''; ?> />Other</label>
            </div>
            <div class="clearfix"></div>
        </div>
        
        <div class="form-group" id="division_country">
            <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">&nbsp; </label>
            <div class="col-sm-10 col-md-10">
                <div class="check_box_scroller_container">                    
                    <div id="tbljobdivision">
                        <ul class="job_country">
                        <?php
                        foreach($division as $div)
                        {
                            ?>
                            <li><input type="checkbox" class="minimal" name="division_id[]" value="<?php echo $div["id"]; ?>" <?php echo (!isset($this->post_data["division_id"]) && in_array($div["id"], $selected_division_id)) ? 'checked="checked"' : '' ?> <?php echo (isset($this->post_data["division_id"]) && in_array($div["id"], $this->post_data["division_id"])) ? 'checked="checked"' : '' ?> /> <?php echo $div["name"]; ?></li>
                            <?php
                        }
                        ?>
                    </ul>
                    </div>
                    
                    <div id="tbljobcountry" style="display: none;">
                        <ul class="job_country">
                        <?php
                        foreach($country as $con)
                        {
                            ?>
                            <li><input type="checkbox" class="iradio_minimal-blue minimal" name="country_id[]" value="<?php echo $con["id"]; ?>"<?php echo (!isset($this->post_data["country_id"]) && in_array($con["id"], $selected_country_id)) ? 'checked="checked"' : '' ?> <?php echo (isset($this->post_data["country_id"]) && in_array($con["id"], $this->post_data["country_id"])) ? 'checked="checked"' : '' ?> /> <?php echo $con["name"]; ?></li>
                            <?php
                        }
                        ?>
                    </ul>
                    </div>                    
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
        
        <div class="form-group" id="tbljobotherlocation" style="display: none;">
            <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">&nbsp; </label>
            <div class="col-sm-5 col-md-5">
                <input type="text" class="form-control" id="other_location" name="other_location" placeholder="Other location" value="<?php echo ($this->post_data["other_location"] != "") ? $this->post_data["other_location"] : $this->results->other_location; ?>" />             
            </div>
            <div class="clearfix"></div>
        </div>
        
        
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Job Category:<span class="valid_star"> *</span> </label>
            <div class="col-sm-10 col-md-10">
                <div class="check_box_scroller_container">
                    <?php
                    foreach($this->job_category as $category)
                    {
                       ?>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" id="checkboxSuccess" name="job_category_id[]" value="<?php echo $category["id"]; ?>" <?php echo (!isset($this->post_data["job_category_id"]) && in_array($category["id"], $selected_categories_id)) ? 'checked="checked"' : '' ?> <?php echo (isset($this->post_data["job_category_id"]) && in_array($category["id"], $this->post_data["job_category_id"])) ? 'checked="checked"' : '' ?> />
                                <?php echo $category["name"]; ?>
                            </label>
                         </div>
                       <?php
                    }    
                    ?>                
                    
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
        
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Job Industry: </label>
            <div class="col-sm-10 col-md-10">
                <div class="check_box_scroller_container">
                    <?php
                    foreach($this->job_industry as $industry)
                    {
                       ?>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" id="checkboxSuccess" name="job_industry_id[]" value="<?php echo $industry["id"]; ?>" <?php echo (!isset($this->post_data["job_industry_id"]) && in_array($industry["id"], $selected_industry_id)) ? 'checked="checked"' : '' ?> <?php echo (isset($this->post_data["job_industry_id"]) && in_array($industry["id"], $this->post_data["job_industry_id"])) ? 'checked="checked"' : '' ?> />
                                <?php echo $industry["name"]; ?>
                            </label>
                         </div>
                       <?php
                    }    
                    ?>                  
                    
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
        
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">&nbsp;</label>
            <div class="col-sm-5 col-md-5">
                <input type="checkbox" id="online_cv_received" name="online_cv_received" value="OnlineCVReceived" <?php echo ($this->post_data["online_cv_received"] == "OnlineCVReceived") ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["online_cv_received"]) && ($this->results->online_cv_received == "OnlineCVReceived")) ? 'checked=""' : ''; ?> /> Online CV Received
            </div>
            <div class="clearfix"></div>
        </div>
        
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">&nbsp;</label>            
            <div class="col-sm-5 col-md-10">
                <input type="checkbox" id="email_cv" name="email_cv" value="EmailCV" <?php echo ($this->post_data["email_cv"] == "EmailCV") ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["email_cv"]) && ($this->results->email_cv_received != "")) ? 'checked=""' : ''; ?> /> Email CV Received
            </div>
            <div class="col-sm-5 col-md-5 email_cv_box"style="margin:5px 0px 0px; display: none;">
                <input type="text" class="form-control" id="email_cv_received" name="email_cv_received" placeholder="Email" value="<?php echo ($this->post_data["email_cv_received"] != "") ? $this->post_data["email_cv_received"] : $this->results->email_cv_received; ?>" />                
            </div>
            <div class="col-sm-5 col-md-5 email_cv_box" style="margin:10px 0px 0px; display: none;">
                <input type="checkbox" id="corporateEmail" name="corporateEmail"> Use Corporate Email
            </div>
            <div class="clearfix"></div>
        </div>
        
        
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">&nbsp;</label>
            <div class="col-sm-5 col-md-5">
                <input type="checkbox" id="hardcopy" name="hardcopy" value="hardcopy" <?php echo ($this->post_data["hardcopy"] == "hardcopy") ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["hardcopy"]) && ($this->results->hardcopy_cv_received != "")) ? 'checked=""' : ''; ?> /> Hardcopy CV Received
            </div>
            <div class="col-sm-10 col-md-10" id="hardcopy_cv_box" style="margin:5px 0px 0px; display: none;">
                <textarea name="hardcopy_cv_received" id="hardcopy_cv_received" rows="8" cols="80"><?php echo ($this->post_data["hardcopy_cv_received"] != "") ? $this->post_data["hardcopy_cv_received"] : $this->results->hardcopy_cv_received; ?></textarea>
            </div>            
            <div class="clearfix"></div>
        </div>
        
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Age Limit: </label>            
            <div class="age_limit_box col-sm-2 col-md-2"> 
                <select name="age_limit_to" class="form-control">
                    <option value=''>To</option>
                    <?php               
                    for($i= 18; $i<= 80; $i++) {

                        ?>
                        <option value="<?php echo $i; ?>" <?php echo (!isset($this->post_data["age_limit_to"]) && ($this->results->age_limit_to == $i)) ? 'selected=""' : '' ?>  <?php echo (isset($this->post_data["age_limit_to"]) && ($this->post_data["age_limit_to"] == $i)) ? 'selected=""' : '' ?>><?php echo $i; ?></option>
                        <?php
                    }
                    ?>
                </select>
            </div>
            
            <div class="age_limit_box col-sm-2 col-md-2"> 
                <select name="age_limit_from" class="form-control">
                    <option value=''>From</option>
                    <?php               
                    for($i= 18; $i<= 80; $i++) {

                        ?>
                        <option value="<?php echo $i; ?>" <?php echo (!isset($this->post_data["age_limit_from"]) && ($this->results->age_limit_from == $i)) ? 'selected=""' : '' ?>  <?php echo (isset($this->post_data["age_limit_from"]) && ($this->post_data["age_limit_from"] == $i)) ? 'selected=""' : '' ?>><?php echo $i; ?></option>
                        <?php
                    }
                    ?>
                </select>
            </div>
            
            <div class="age_limit_other_box col-sm-2 col-md-2" style="display:none;"> 
                <input type="text" class="form-control" id="age_limit_other" name="age_limit_other" placeholder="Type Age" value="<?php echo ($this->post_data["age_limit_other"] != "") ? $this->post_data["age_limit_other"] : $this->results->age_limit_other; ?>">
            </div>
            
            <div class="col-sm2 col-md-2">
                <input type="checkbox" id="type_age" name="type_age" value="type_age" <?php echo ($this->post_data["type_age"] == "type_age") ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["type_age"]) && ($this->results->age_limit_other != "")) ? 'checked=""' : ''; ?> /> Type Age
            </div>
            <div class="clearfix"></div>
        </div>
        
        <?php               
        $selected_job_level = explode(",", $this->results->job_level);        
        ?>
        
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Job Level: </label>
            <div class="col-sm-10 col-md-10">
                <div class="check_box_scroller_container">
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="job_level[]" id="job_level" value="Entry" <?php echo (!isset($this->post_data["job_level"]) && in_array("Entry", $selected_job_level)) ? 'checked="checked"' : '' ?> <?php echo (isset($this->post_data["job_level"]) && in_array("Entry", $this->post_data["job_level"])) ? 'checked="checked"' : '' ?> />
                            Entry
                        </label>
                    </div>

                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="job_level[]"  id="job_level" value="Mid" <?php echo (!isset($this->post_data["job_level"]) && in_array("Mid", $selected_job_level)) ? 'checked="checked"' : '' ?>  <?php echo (isset($this->post_data["job_level"]) && in_array("Mid", $this->post_data["job_level"])) ? 'checked="checked"' : '' ?> />
                            Mid
                        </label>
                    </div> 

                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="job_level[]"  id="job_level" value="Top" <?php echo (!isset($this->post_data["job_level"]) && in_array("Top", $selected_job_level)) ? 'checked="checked"' : '' ?>  <?php echo (isset($this->post_data["job_level"]) && in_array("Top", $this->post_data["job_level"])) ? 'checked="checked"' : '' ?> />
                           Top
                        </label>
                    </div>

                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
        
        <?php
        $selected_job_type = explode(",", $this->results->job_type);        
        ?>
        
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Job Type: </label>
            <div class="col-sm-10 col-md-10">
                <div class="check_box_scroller_container">
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" id="job_type" name="job_type[]" value="Full Time" <?php echo (!isset($this->post_data["job_type"]) && in_array("Full Time", $selected_job_type)) ? 'checked="checked"' : '' ?>  <?php echo (isset($this->post_data["job_type"]) && in_array("Full Time", $this->post_data["job_type"])) ? 'checked="checked"' : '' ?> />
                            Full Time
                        </label>
                    </div>

                    <div class="checkbox">
                        <label>
                            <input type="checkbox" id="job_type" name="job_type[]"  value="Part Time" <?php echo (!isset($this->post_data["job_type"]) && in_array("Part Time", $selected_job_type)) ? 'checked="checked"' : '' ?> <?php echo (isset($this->post_data["job_type"]) && in_array("Part Time", $this->post_data["job_type"])) ? 'checked="checked"' : '' ?> />
                            Part Time
                        </label>
                    </div> 

                    <div class="checkbox">
                        <label>
                            <input type="checkbox" id="job_type" name="job_type[]"  value="Contractual" <?php echo (!isset($this->post_data["job_type"]) && in_array("Contractual", $selected_job_type)) ? 'checked="checked"' : '' ?> <?php echo (isset($this->post_data["job_type"]) && in_array("Contractual", $this->post_data["job_type"])) ? 'checked="checked"' : '' ?> />
                            Contractual
                        </label>
                    </div> 
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" id="job_type" name="job_type[]" value="Intern" <?php echo (!isset($this->post_data["job_type"]) && in_array("Intern", $selected_job_type)) ? 'checked="checked"' : '' ?> <?php echo (isset($this->post_data["job_type"]) && in_array("Intern", $this->post_data["job_type"])) ? 'checked="checked"' : '' ?> />
                            Intern
                        </label>
                    </div>

                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
        
        
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Posting date:</label>
            <div class="col-sm-5 col-md-5">
                <div class="input-group">
                    <div class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                    </div>
                    <?php                   
                    if(($this->results->posting_date !="") && ($this->results->posting_date !="0000-00-00"))
                    {
                        $posting_date = $this->results->posting_date;
                    }
                    elseif(isset($this->post_data["posting_date"]))
                    {
                        $posting_date = $this->post_data["posting_date"];
                    }
                    else{
                        $posting_date = date("Y-m-d");
                    }
                    ?>
                    <input type="text" name="posting_date" required value="<?php echo $posting_date; ?>" class="form-control" data-inputmask="'alias': 'yyyy-mm-dd'" data-mask/>
                </div>                
            </div>
            
            <div class="clearfix"></div>
        </div>
        
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Apply Deadline:<span class="valid_star"> *</span></label>
            <div class="col-sm-5 col-md-5">
                <div class="input-group">
                    <div class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                    </div>
                    <?php
                    if(($this->results->job_deadline !="") && ($this->results->job_deadline !="0000-00-00"))
                    {
                        $job_deadline = $this->results->job_deadline;
                    }
                    elseif(isset($this->post_data["job_deadline"]))
                    {
                        $job_deadline = $this->post_data["job_deadline"];
                    }
                    else{
                        $job_deadline = "";
                    }
                    ?>
                    <input type="text" name="job_deadline" required value="<?php echo $job_deadline; ?>" class="form-control" data-inputmask="'alias': 'yyyy-mm-dd'" data-mask/>
                </div>                
            </div>
            
            <div class="clearfix"></div>
        </div>
        
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Educational Qualification: <span class="valid_star"> *</span></label>
            <div class="col-sm-10 col-md-10">
                <textarea id="job_education" name="job_education" required rows="8" cols="80"><?php echo ($this->post_data["job_education"] != "") ? $this->post_data["job_education"] : $this->results->job_education; ?></textarea>
            </div>
            <div class="clearfix"></div>
        </div>
        
        <div class="form-group">
            <label for="salary_range" class="col-sm-2 col-md-2 control-label">Salary:</label>
            <div class="col-sm-5 col-md-5">
                <select name="salary_range" class="form-control">
                    <option value="">Select</option>
                    <option value="8000-12000" <?php echo (!isset($this->post_data["salary_range"]) && ($this->results->salary_range == '8000-12000')) ? 'selected=""' : '' ?>  <?php echo (isset($this->post_data["salary_range"]) && ($this->post_data["salary_range"] == "8000-12000")) ? 'selected=""' : ''; ?>>8000 - 12000</option>
                    <option value="13000-25000" <?php echo (!isset($this->post_data["salary_range"]) && ($this->results->salary_range == '13000-25000')) ? 'selected=""' : '' ?>  <?php echo (isset($this->post_data["salary_range"]) && ($this->post_data["salary_range"] == "13000-25000")) ? 'selected=""' : ''; ?>>13000 - 25000</option>
                    <option value="20000-40000" <?php echo (!isset($this->post_data["salary_range"]) && ($this->results->salary_range == '20000-40000')) ? 'selected=""' : '' ?>  <?php echo (isset($this->post_data["salary_range"]) && ($this->post_data["salary_range"] == "20000-40000")) ? 'selected=""' : ''; ?>>20000 - 40000</option>
                    <option value="40000-60000" <?php echo (!isset($this->post_data["salary_range"]) && ($this->results->salary_range == '40000-60000')) ? 'selected=""' : '' ?>  <?php echo (isset($this->post_data["salary_range"]) && ($this->post_data["salary_range"] == "40000-60000")) ? 'selected=""' : '';; ?>>40000 - 60000</option>
                    <option value="60000-80000" <?php echo (!isset($this->post_data["salary_range"]) && ($this->results->salary_range == '60000-80000')) ? 'selected=""' : '' ?>  <?php echo (isset($this->post_data["salary_range"]) && ($this->post_data["salary_range"] == "60000-80000")) ? 'selected=""' : '' ?>>60000 - 80000</option>
                    <option value="Negotiable" <?php echo (!isset($this->post_data["salary_range"]) && ($this->results->salary_range == 'Negotiable')) ? 'selected=""' : '' ?>  <?php echo (isset($this->post_data["salary_range"]) && ($this->post_data["salary_range"] == "Negotiable")) ? 'selected=""' : ''; ?>>Negotiable</option>
                </select>
            </div>
            <div class="clearfix"></div>
        </div>
        
        
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Other Benefits</label>
            <div class="col-sm-10 col-md-10">
                <textarea id="other_benefits" name="other_benefits" rows="8" cols="80"><?php echo ($this->post_data["other_benefits"] != "") ? $this->post_data["other_benefits"] : $this->results->other_benefits; ?></textarea>
            </div>
            <div class="clearfix"></div>
        </div>
        
        <div class="form-group">
            <label for="job_experienced" class="col-sm-2 col-md-2 control-label">Job Experienced:<span class="valid_star"> *</span> </label>
            <div class="col-sm-5 col-md-5">
                <select class="form-control" name="job_experienced">
                    <option value="">Select Years</option>
                    <?php
                    for ($group = 1; $group <= 10; $group ++) {
                        ?>
                        <option value="<?php echo $group; ?>" <?php echo (!isset($this->post_data["job_experienced"]) && ($this->results->job_experienced == $group)) ? 'selected=""' : '' ?> <?php echo (isset($this->post_data["job_experienced"]) && ($this->post_data["job_experienced"] == $group)) ? 'selected=""' : '' ?>><?php echo $group; ?></option>
                        <?php
                    }
                    ?>
                </select>
            </div>
            <div class="clearfix"></div>
        </div>
                        
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Preferred Role: </label>
            <div class="col-sm-10 col-md-10">
                <div class="check_box_scroller_container">
                    <ul style="margin: 3px 0px 0px 3px; padding: 0px;">
                        <div class="msg_list">
                        <?php
                        foreach($this->department as $dtype)
                        {
                           ?>
                            <p class="msg_head"><?php echo $dtype["name"]; ?></p>
                            <div class="msg_body" style="display: none;">
                            <?php
                            foreach($this->preferred_role[$dtype["id"]] as $role)
                            {
                               ?>                                
                               <li>
                               <input type="checkbox" id="checkboxSuccess" name="preferred_role_id[]" value="<?php echo $role["id"]; ?>" <?php echo (!isset($this->post_data["preferred_role_id"]) && in_array($role["id"], $selected_preferred_role_id)) ? 'checked="checked"' : '' ?> <?php echo (isset($this->post_data["preferred_role_id"]) && in_array($role["id"], $this->post_data["preferred_role_id"])) ? 'checked="checked"' : '' ?> />
                               <?php echo $role["name"]; ?>
                               </li>
                               <?php
                            }
                            ?> 
                            </div> 
                            <?php
                        }    
                        ?>
                        </div>
                    </ul>    
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
        
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Preferred Business: </label>
            <div class="col-sm-10 col-md-10">
                <div class="check_box_scroller_container">
                    <?php
                    foreach($this->business_type as $btype)
                    {
                       ?>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" id="checkboxSuccess" name="business_type_id[]" value="<?php echo $btype["id"]; ?>" <?php echo (!isset($this->post_data["business_type_id"]) && in_array($btype["id"], $selected_business_type_id)) ? 'checked="checked"' : '' ?>  <?php echo (isset($this->post_data["business_type_id"]) && in_array($btype["id"], $this->post_data["business_type_id"])) ? 'checked="checked"' : '' ?> />
                                <?php echo $btype["name"]; ?>
                            </label>
                         </div>
                       <?php
                    }    
                    ?> 
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
        
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Job Requirement: </label>
            <div class="col-sm-10 col-md-10">
                <textarea id="job_requirement" name="job_requirement" rows="8" cols="80"><?php echo ($this->post_data["job_requirement"] != "") ? $this->post_data["job_requirement"] : $this->results->job_requirement; ?></textarea>
            </div>
            <div class="clearfix"></div>
        </div>
        
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Job Description: </label>
            <div class="col-sm-10 col-md-10">
                <textarea id="job_description" name="job_description" rows="8" cols="80"><?php echo ($this->post_data["job_description"] != "") ? $this->post_data["job_description"] : $this->results->job_description; ?></textarea>
            </div>
            <div class="clearfix"></div>
        </div>
        
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Is Spotlight. Job? </label>
            <div class="col-sm-5 col-md-5">  
                <label> 
                    <input type="radio" name="spot_light_used" id="splUsed" onclick="spotLightJob(1);" value="1"  class="iradio_minimal-blue minimal" <?php echo ($this->post_data["spot_light_used"] == "1") ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["spot_light_used"]) && ($this->results->spot_light_used == "1")) ? 'checked=""' : ''; ?> />Yes
                </label>
                <label>
                    <input type="radio" name="spot_light_used" id="splNUsed" onclick="spotLightJob(0);" value="0" class="iradio_minimal-blue minimal"  <?php echo ($this->post_data["spot_light_used"] == "0") ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["spot_light_used"]) && ($this->results->spot_light_used == "0")) ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["spot_light_used"]) && ($this->results->spot_light_used == "")) ? 'checked=""' : ''; ?>  />No
                </label>
            </div>
            <div class="clearfix"></div>
        </div>
        
        <div class="spot_light_used_box">  
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Spotlight Job Content</label>
                <div class="col-sm-10 col-md-10">
                    <textarea id="editor1" name="spotlight_job_content" rows="10" cols="80"><?php echo ($this->post_data["spotlight_job_content"] != "") ? $this->post_data["spotlight_job_content"] : $this->results->spotlight_job_content; ?></textarea>
                </div>
                <div class="clearfix"></div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Spotlight Logo</label>
                <div class="col-sm-10 col-md-10">

                    <input type="file" name="spotlight_job_logo" id="spotlight_job_logo">
                </div>
                <?php
                if($this->results->spotlight_job_logo !="")
                {    
                    ?>
                    <div class="col-sm-10 col-md-10">                   
                        <img width="150" src="<?php echo "/upload/job/".$this->results->spotlight_job_logo; ?>" alt="spotlight logo" title="spotlight loho" />
                    </div>
                <?php
                }
                ?>
                <div class="clearfix"></div>
            </div>
            
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Spotlight Order</label>
                <div class="col-sm-3 col-md-3">                    
                    <select class="form-control" name="spotlight_job_order">
                        <option value="">Select order</option>
                        <?php
                        for ($order = 1; $order <= 10; $order ++) {
                            ?>
                            <option value="<?php echo $order; ?>" <?php echo (!isset($this->post_data["spotlight_job_order"]) && ($this->results->spotlight_job_order == $order)) ? 'selected=""' : '' ?>  <?php echo (isset($this->post_data["spotlight_job_order"]) && ($this->post_data["spotlight_job_order"] == $order)) ? 'selected=""' : '' ?>><?php echo $order; ?></option>
                            <?php
                        }
                        ?>
                    </select>
                </div>
                <div class="clearfix"></div>
            </div>
            
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Spotlight Group</label>
                <div class="col-sm-3 col-md-3">                    
                    <select class="form-control" name="spotlight_job_gorup">
                        <option value="">Select group</option>
                        <?php
                        for ($group = 1; $group <= 10; $group ++) {
                            ?>
                            <option value="<?php echo $group; ?>" <?php echo (!isset($this->post_data["spotlight_job_gorup"]) && ($this->results->spotlight_job_gorup == $group)) ? 'selected=""' : '' ?> <?php echo (isset($this->post_data["spotlight_job_gorup"]) && ($this->post_data["spotlight_job_gorup"] == $group)) ? 'selected=""' : '' ?>><?php echo $group; ?></option>
                            <?php
                        }
                        ?>
                    </select> 
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
        
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 col-md-2 control-label"> Hide Company Address and Phone?? </label>
            <div class="col-sm-5 col-md-5">                
                <label>
                    <input type="radio" name="show_company_status" value="Yes"  class="iradio_minimal-blue minimal" <?php echo ($this->post_data["show_company_status"] == "Yes") ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["show_company_status"]) && ($this->results->show_company_status == "Yes")) ? 'checked=""' : ''; ?> />Yes
                </label>
                <label>                    
                    <input type="radio" name="show_company_status" value="No" class="iradio_minimal-blue minimal"   <?php echo ($this->post_data["show_company_status"] == "No") ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["show_company_status"]) && ($this->results->show_company_status == "No")) ? 'checked=""' : ''; ?>  />No
                </label>
            </div>
            <div class="clearfix"></div>
        </div>

        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Is Active?</label>
            <div class="col-sm-5 col-md-5">
                <label>
                    <input type="radio" name="status" value="1"  class="iradio_minimal-blue minimal" <?php echo ($this->post_data["status"] == "1") ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["status"]) && ($this->results->status == "1")) ? 'checked=""' : ''; ?> checked/>Yes
                </label>
                <label>                    
                    <input type="radio" name="status" value="0" class="iradio_minimal-blue minimal"  <?php echo ($this->post_data["status"] == "0") ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["status"]) && ($this->results->status == "0")) ? 'checked=""' : ''; ?> />No
                </label>
            </div>
            <div class="clearfix"></div>
        </div>     
        

        <div class="form-group">
            <div class=" col-xs-12 col-sm-6 col-md-6 col-sm-offset-2 col-md-offset-2 btn_submit">                
                <input type="submit" name="save" value="Save" class="btn btn-primary" /> &nbsp;
                <?php
                if($this->results->id =="")
                {    
                    ?>
                    <input type="submit" name="preview" value="Preview" class="btn btn-primary" /> &nbsp;
                    <?php
                }
                ?>                
                <a class="btn btn-default" href="<?php echo $this->serverUrl()."/admin/company/jobs/".$company_id; ?>" role="button">Back</a>
            </div>                                            
        </div>            
        <div class="clearfix"></div>        
    </form>



</div>
    
</section>

<script type="text/javascript">
    function show_location()
    {        
        if(document.newjobpost.jobLocation_1.checked)
        {
            document.getElementById('division_country').style.display='block';
            
            document.getElementById('tbljobdivision').style.display='block';
            document.getElementById('tbljobcountry').style.display='none';
            document.getElementById('tbljobotherlocation').style.display='none';
        }
        else if(document.newjobpost.jobLocation_2.checked)
        {
            document.getElementById('division_country').style.display='block';
            
            document.getElementById('tbljobdivision').style.display='none';
            document.getElementById('tbljobcountry').style.display='block';
            document.getElementById('tbljobotherlocation').style.display='none';
        }            
        else if(document.newjobpost.jobLocation_3.checked)
        {
            document.getElementById('tbljobotherlocation').style.display='block';
            document.getElementById('division_country').style.display='none';            
        }
    }
    
    
    
    function show_email()
    {        
        if(document.newjobpost.online_cv_received.checked)
        {
            document.getElementsByClassName('email_cv_box').style.display='block';
        }
        else
        {
            document.getElementsByClassName('email_cv_box').style.display='none';
        }
    }
    
    function spotLightJob(val)
    {        
        if(val == 1)
        {    
             $(".spot_light_used_box").show();
        }     
        else
        {    
             $(".spot_light_used_box").hide();
        }    
    }
    
    
    
    $(document).ready(function(){
        
        //for spotlight job
        if(document.getElementById('splUsed').checked)
        {
            spotLightJob(1);          
        }   
        
        if(document.getElementById('splNUsed').checked)
        {
            spotLightJob(0);
        }
        
        if(document.getElementById('email_cv').checked)
        {
            $(".email_cv_box").show();
        }
        
        if(document.getElementById('hardcopy').checked)
        {
            $("#hardcopy_cv_box").show();
        } 
        
           
        $('input[type="checkbox"][name="hardcopy"]').on('ifChanged', function(event){            
            if (this.checked) {
               $("#hardcopy_cv_box").show();
            }
            else
            {
               $("#hardcopy_cv_box").hide();
            }
        });
                
        $('input[type="checkbox"][name="corporateEmail"]').on('ifChanged', function(event){            
            if (this.checked) {
               $("#email_cv_received").val("jobs@prothom-alo.info");
            }
            else
            {
               $("#email_cv_received").val("");
            }
        });
      
        $('input[type="checkbox"][name="email_cv"]').on('ifChanged', function(event){
            
            if (this.checked) {
               $(".email_cv_box").show();
            }
            else
            {
               $(".email_cv_box").hide();
            }
        });
        
        
        //Type age
        if(document.getElementById('type_age').checked)
        {
            $(".age_limit_box").hide();
            $(".age_limit_other_box").show();  
        } 
        
           
        $('input[type="checkbox"][name="type_age"]').on('ifChanged', function(event){
            if (this.checked) {
               $(".age_limit_box").hide();
               $(".age_limit_other_box").show();
            }
            else
            {
               $(".age_limit_box").show();
               $(".age_limit_other_box").hide();
            }
        });
        
        //Money Euro
        $("[data-mask]").inputmask();
        
        CKEDITOR.replace('hardcopy_cv_received');
        CKEDITOR.replace('other_benefits');
        CKEDITOR.replace('job_education');
      //  CKEDITOR.replace('job_requirement');
        //CKEDITOR.replace('job_description');
        
        
        //$(".textarea").wysihtml5();
        
         CKEDITOR.replace('job_requirement', {
            customConfig: '/plugins/ckeditor/custom_config.js'
        });
        CKEDITOR.replace('job_description',
                {
                    customConfig: '/plugins/ckeditor/custom_config.js',
                    filebrowserBrowseUrl: '/ckfinder/ckfinder.html',
                    filebrowserImageBrowseUrl: '/ckfinder/ckfinder.html'
                });

        //$(".textarea").wysihtml5();

        CKEDITOR.replace('editor1', {
            customConfig: '/plugins/ckeditor/custom_config.js',
            filebrowserBrowseUrl: '/ckfinder/ckfinder.html',
            filebrowserImageBrowseUrl: '/ckfinder/ckfinder.html',
            // filebrowserFlashBrowseUrl: '/ckfinder/ckfinder.html',
            filebrowserUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload',
            filebrowserImageUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload'
            //filebrowserFlashUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload'
        });
        
        
        
                
    });
    
    $(document).ready(function()
    {
        show_location();
        
        //hide the all of the element with class msg_body
        $(".msg_body").hide();

        //toggle the componenet with class msg_body
        $(".msg_head").click(function()
        {
            $(this).next(".msg_body").slideToggle(600);
        });
    });  
</script>

<style type="text/css">
    ul.job_country{
        list-style-type: none;
        padding:3px 0px 0px 5px;
        margin: 0px;
    }
</style>
