<?php

use Carbon\Carbon; ?>
<div class="box box-primary">
    <div class="box-header">
        <h1 class="page-heading">Employer's Name : <?php echo $this->results->full_name;?></h1>
    </div><!-- /.box-header -->
    <!-- form start -->
    <?php if (count($this->error_messages) > 0) { ?>
    <div class="alert alert-danger">
        <?php
        foreach ($this->error_messages as $messageId => $message) {
            echo "<p>  $message </p>";
        }
        ?>   
    </div> 
    <?php } ?>
    
        
        <?php
        if ($this->flashMessenger()->hasCurrentSuccessMessages()) {
            ?>
            <div class="box box-success box-solid alert-success">
                <div class="box-tools pull-right">
                    <button data-widget="remove" class="btn btn-box-tool text-gray"><i class="fa fa-times"></i></button>                    
                </div><!-- /.box-tools -->

                <div class="box-body">
                    <?php
                    //$flashMessenger = $this->flashMessenger();
                    //if ($flashMessenger->hasMessages()) {     
                    echo $this->flashMessenger()
                            ->setMessageOpenFormat('<strong>')
                            ->setMessageCloseString('</strong>')
                            ->render('success');
                    //} 
                    ?> 
                </div><!-- /.box-body -->
            </div><!-- /.box -->
            <?php
        }
        ?>
    
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">User Profile</a></li>
            <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Company Information</a></li>
            <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Settings</a></li>
            <li role="presentation"><a href="#invoice" aria-controls="settings" role="tab" data-toggle="tab">Invoice</a></li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="profile">
                <div class="row">
                    <div class="col-md-6">
                        <form data-toggle="validator" role="form" method="post" >
                            <div class="box-body">
                                <div class="form-group">
                                  <label for="full_name">Full name</label>
                                  <input type="text" name="full_name" required="" value="<?php echo $this->results->full_name; ?>" placeholder="Full name" id="full_name" class="form-control" autofocus>
                                </div>

                                <div class="form-group">
                                  <label for="email">Email address</label>
                                  <input type="email" name="email" value="<?php echo $this->results->email; ?>" placeholder="Enter email" id="email" class="form-control">
                                </div>

                                <div class="form-group">
                                    <label for="is_top_employer">Is top employer?</label>
                                    <select class="form-control" name="is_top_employer" id="is_top_employer">
                                        <option value="1" <?php echo (!isset($_POST["is_top_employer"]) && ($this->employer_profile[0]["is_top_employer"] == "1")) ? "selected" : ""; ?> <?php echo ($this->post_data["is_top_employer"] != "" && $this->post_data["is_top_employer"] == "1") ? "selected" : ""; ?>>Yes</option>
                                        <option value="0" <?php echo (!isset($_POST["is_top_employer"]) && ($this->employer_profile[0]["is_top_employer"] == "0")) ? "selected" : ""; ?> <?php echo ($this->post_data["is_top_employer"] != "" && $this->post_data["is_top_employer"] == "0") ? "selected" : ""; ?>>No</option>                   
                                    </select>
                                </div>
                                
                                <div class="form-group">
                                    <label for="is_top_employer">Sliding option</label>
                                    <select class="form-control" name="sliding_option" id="sliding_option">
                                        <option value="slide" <?php echo (!isset($_POST["sliding_option"]) && ($this->employer_profile[0]["sliding_option"] == "slide")) ? "selected" : ""; ?> <?php echo ($this->post_data["sliding_option"] != "" && $this->post_data["sliding_option"] == "slide") ? "selected" : ""; ?>>Slide</option>
                                        <option value="happy" <?php echo (!isset($_POST["sliding_option"]) && ($this->employer_profile[0]["sliding_option"] == "happy")) ? "selected" : ""; ?> <?php echo ($this->post_data["sliding_option"] != "" && $this->post_data["sliding_option"] == "happy") ? "selected" : ""; ?>>Happy</option>                   
                                    </select>
                                </div>
                                
                                <div class="form-group">
                                    <label for="top_employer_order">Order</label>                                                        
                                    <select class="form-control" name="top_employer_order">
                                        <option value="">Select order</option>
                                        <?php
                                        for ($order = 1; $order <= 10; $order ++) {
                                            ?>
                                            <option value="<?php echo $order; ?>" <?php echo (!isset($this->post_data["top_employer_order"]) && ($this->employer_profile[0]["top_employer_order"] == $order)) ? 'selected=""' : '' ?>  <?php echo (isset($this->post_data["top_employer_order"]) && ($this->post_data["top_employer_order"] == $order)) ? 'selected=""' : '' ?>><?php echo $order; ?></option>
                                            <?php
                                        }
                                        ?>
                                    </select>                                    
                                </div>

                                <div class="form-group">
                                    <label for="user_status">Status: </label>
                                    <select class="form-control" name="user_status" id="user_status">
                                        <option value="active"   <?php echo (!isset($_POST["user_status"]) && ($this->results->user_status == "admin")) ? "selected" : ""; ?>     <?php echo ($this->post_data["user_status"] != "" && $this->post_data["user_status"] == "active") ? "selected" : ""; ?>>Active</option>
                                        <option value="inactive" <?php echo (!isset($_POST["user_status"]) && ($this->results->user_status == "inactive")) ? "selected" : ""; ?>  <?php echo ($this->post_data["user_status"] != "" && $this->post_data["user_status"] == "inactive") ? "selected" : ""; ?>>Inactive</option>
                                        <option value="banned" <?php echo (!isset($_POST["user_status"]) && ($this->results->user_status == "banned")) ? "selected" : ""; ?>  <?php echo ($this->post_data["user_status"] != "" && $this->post_data["user_status"] == "banned") ? "selected" : ""; ?>>Banned</option>
                                        <option value="need_activation" <?php echo (!isset($_POST["user_status"]) && ($this->results->user_status == "need_activation")) ? "selected" : ""; ?>  <?php echo ($this->post_data["user_status"] != "" && $this->post_data["user_status"] == "need_activation") ? "selected" : ""; ?>>Need activation</option>
                                    </select>
                                </div>
                                
                                <div class="form-group">
                                    <label for="user_status">User role: </label>
                                    <select class="form-control" name="user_role" id="user_role">
                                        <option value="observe"   <?php echo (!isset($_POST["user_role"]) && ($this->results->user_role == "observe"))   ? "selected" : ""; ?>  <?php echo ($this->post_data["user_role"] != "" && $this->post_data["user_role"] == "active")    ? "selected" : ""; ?>>Observe</option>
                                        <option value="permitted" <?php echo (!isset($_POST["user_role"]) && ($this->results->user_role == "permitted")) ? "selected" : ""; ?>  <?php echo ($this->post_data["user_role"] != "" && $this->post_data["user_role"] == "permitted") ? "selected" : ""; ?>>Permitted</option>                   
                                    </select>
                                </div>
                                
                                <div class="box-footer">
                                    <input type="submit" name="user_profile" value="Update" class="btn btn-primary" />&nbsp;
                                    <a class="btn btn-default" href="<?php echo $this->serverUrl()."/admin/company"; ?>" role="button">Back</a>
                                </div> 
                            </div><!-- /.box-body -->
                        </form>                                          
                    </div>
                </div>
            </div>
            <div role="tabpanel" class="tab-pane" id="messages">            
                <div class="row">
                    <div class="col-md-12">
                        <form data-toggle="validator" role="form" method="post" enctype="multipart/form-data">
                            <div class="box-body">                                
                                <div class="form-group">
                                    <label for="company_url" class="col-sm-2 col-md-2 control-label">Company URL: </label>
                                    <div class="col-sm-5 col-md-5">
                                        <input type="text" class="form-control" id="company_url" name="company_url" placeholder="www.url.com" value="<?php echo ($this->post_data["company_url"] != "") ? $this->post_data["company_url"] : $this->employer_profile[0]["company_url"]; ?>">
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                                
                                <div class="form-group">
                                    <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Company Information: </label>
                                    <div class="col-sm-10 col-md-10">
                                        <textarea id="company_description" name="company_description" rows="8" cols="80"><?php echo ($this->post_data["company_description"] != "") ? $this->post_data["company_description"] : $this->employer_profile[0]["company_description"]; ?></textarea>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                                                                
                                <div class="form-group">
                                    <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Services:</label>
                                    <div class="col-sm-10 col-md-10">
                                        <textarea id="company_service" name="company_service" rows="10" cols="80"><?php echo ($this->post_data["company_service"] != "") ? $this->post_data["company_service"] : $this->employer_profile[0]["company_service"]; ?></textarea>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>

                                <div class="form-group">
                                    <label for="company_banner" class="col-sm-2 col-md-2 control-label">Banner:</label>
                                    <div class="col-sm-10 col-md-10">
                                        <input type="file" name="company_banner" id="company_banner">
                                    </div>                                    
                                    <div class="clearfix"></div>
                                </div>
                                
                                <?php
                                if($this->employer_profile[0]["company_banner"] !="")
                                {    
                                    ?>
                                    <div class="form-group">
                                        <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">&nbsp;</label> 
                                            <div class="col-sm-10 col-md-10">                       
                                                <img width="150" src="<?php echo "/upload/client/".$this->employer_profile[0]["company_banner"]; ?>" alt="company_banner" title="company_banner" />
                                            </div>                                    
                                        <div class="clearfix"></div>
                                    </div>
                                    <?php
                                }
                                ?>                                

                                <div class="form-group">
                                   <label for="company_logo" class="col-sm-2 col-md-2 control-label">Logo:</label>
                                   <div class="col-sm-10 col-md-10">
                                       <input type="file" name="company_logo" id="company_logo">
                                   </div>                                   
                                   <div class="clearfix"></div>
                                </div>
                                
                                <?php
                                if($this->employer_profile[0]["company_logo"] !="")
                                {    
                                    ?>
                                    <div class="form-group">
                                        <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">&nbsp;</label> 
                                            <div class="col-sm-10 col-md-10">                       
                                                <img width="150" src="<?php echo "/upload/client/".$this->employer_profile[0]["company_logo"]; ?>" alt="company_banner" title="company_banner" />
                                            </div>                                    
                                        <div class="clearfix"></div>
                                    </div>
                                    <?php
                                }
                                ?>
                                
                                <div class="box-footer">
                                    <input type="submit" name="company_information" value="Update" class="btn btn-primary" />&nbsp;
                                    <a class="btn btn-default" href="<?php echo $this->serverUrl()."/admin/company"; ?>" role="button">Back</a>
                                </div>        

                            </div><!-- /.box-body -->
                        </form>                                       
                    </div>
                </div>            
            </div>
            <div role="tabpanel" class="tab-pane" id="settings">
                <div class="row">
                    <div class="col-md-6">
                        <form data-toggle="validator" role="form" method="post" >
                            <div class="box-body">
                                
                                <div class="form-group">
                                  <label for="password">User Name:</label>
                                  <input type="text" readonly  value="<?php echo $this->results->user_name;?>"  class="form-control">
                                </div>
                                <div class="form-group">
                                  <label for="password">Email:</label>
                                  <input type="text" readonly  value="<?php echo $this->results->email;?>"  class="form-control">
                                </div>
                                <div class="form-group">
                                  <label for="password">New password:</label>
                                  <input type="password" id="password" name="password" value="" placeholder="New password" id="newpassword" class="form-control" required="">
                                </div>

                                 <div class="form-group">
                                  <label for="repassword">Confirm password:</label>
                                  <input type="password" placeholder="Retype Password" id="repassword" class="form-control" data-match="#password" name="re-password" required="">                                  
                                </div>
                                <div class="box-footer">
                                    <input type="submit" name="settings" value="Update" class="btn btn-primary" />&nbsp;
                                    <a class="btn btn-default" href="<?php echo $this->serverUrl()."/admin/company"; ?>" role="button">Back</a>
                                </div>
                            </div><!-- /.box-body -->
                        </form>                                            
                    </div>
                </div>
            </div>
            <div role="tabpanel" class="tab-pane" id="invoice">
                <div class="row">
                    <div class="col-md-6">
                        <form data-toggle="validator" role="form" method="post" enctype="multipart/form-data">
                            <div class="box-body">
                                <div class="form-group">
                                  <label for="invoice_logo">Invoice:</label>
                                  <input type="file" name="invoice_name" id="invoice_logo" required />
                                </div>
                                
                                <div class="form-group">
                                  <label for="invoice_date">Invoice date:</label>
                                  <input type="text" name="invoice_date" required value="" class="form-control" id="invoice_date" data-inputmask="'alias': 'yyyy-mm-dd'" data-mask/>
                                </div>

                                <div class="box-footer">
                                    <input type="submit" name="invoice" value="Update" class="btn btn-primary" />&nbsp;
                                    <a class="btn btn-default" href="<?php echo $this->serverUrl()."/admin/company"; ?>" role="button">Back</a>
                                </div>
                            </div><!-- /.box-body -->
                        </form>                                            
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <table id="example111" class="table table-bordered table-striped table-condensed">
                            <thead>
                                <tr>                         
                                    <th>Date</th>                                    
                                    <th>Action</th>
                                </tr>
                            </thead>

                            <tbody>
                                <?php
                                foreach ($this->invoice as $row) {
                                    ?>
                                    <tr>
                                        <td>
                                        <a target="_blank" href="/upload/client/<?php echo $row["file_name"];?>">    
                                        <?php
                                        $dt = Carbon::createFromFormat('Y-m-d', $row["invoice_date"]);
                                        echo $dt->toFormattedDateString();
                                        ?>
                                        </a>    
                                        </td>
                                           
                                        <td>
                                            <form method="POST" action="<?php echo "/admin/company/deleteinvoice/". $row["id"]; ?>" accept-charset="UTF-8" style="display:inline">                                      
                                                <button class="btn btn-xs btn-danger" type="button" data-toggle="modal" data-target="#confirmDelete" data-title="Delete Invoice" data-message="Are you sure you want to delete this invoice? ">
                                                    <i class="glyphicon glyphicon-ok-circle"></i> Delete
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                <?php }
                                ?>
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </form>

</div><!-- /.box -->

<script src="/js/validator.js"></script>

<script type="text/javascript">
    $(function(){
        //$("#example111").dataTable();
        
        $('#example111').dataTable({
            /* Disable initial sort */
            "aaSorting": []
        });
        
        //date
        $("[data-mask]").inputmask();
        
        CKEDITOR.replace('company_description');
        CKEDITOR.replace('company_service');
        
    });
</script>
