 <section class="content">
    <!-- Default box -->
    <div class="box box-default">
        <div class="box-header with-border">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="pull-left">
                        <h1 class="page-heading">Total Jobs : <?php echo count($this->jobs);?></h1>
                    </div>
                    <div class="pull-right">
                        <div class="btn-group">
                            <a class="btn btn-success"  href="<?php echo "/admin/company/addjob/".$company_id; ?>"><i class="fa fa-plus"></i> Add New</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="box-body">
            <?php
            if ($this->flashMessenger()->hasCurrentSuccessMessages()) {
                ?>
                <div class="box box-success box-solid alert-success">
                    <div class="box-tools pull-right">
                        <button data-widget="remove" class="btn btn-box-tool text-gray"><i class="fa fa-times"></i></button>                    
                    </div><!-- /.box-tools -->

                    <div class="box-body">
                        <?php
                        //$flashMessenger = $this->flashMessenger();
                        //if ($flashMessenger->hasMessages()) {     
                        echo $this->flashMessenger()
                                ->setMessageOpenFormat('<strong>')
                                ->setMessageCloseString('</strong>')
                                ->render('success');
                        //} 
                        ?> 
                    </div><!-- /.box-body -->
                </div><!-- /.box -->
                <?php
            }
            ?>

            <table id="example1" class="table table-bordered table-striped table-condensed">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Job Title</th>
                        <th>View</th>
                        <th>Company name</th>
                        <th>Deadline</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                   <?php foreach ($this->jobs as $row):?>
                    <tr>
                        <td><?php echo $id=$row['id'];?></td>
                        <td><?php echo $row['job_title']; ?> </td>
                        <td><?php echo $row['view']; ?> </td>
                        <td><?php echo $row['company_name']; ?></td>
                        <td><?php echo $row['job_deadline']; ?></td>
                        <td>
                        <div class="btn-group">                                
                            <a class="btn btn-primary btn-xs" href="<?php echo "/admin/company/editjob/".$row["employer_id"]."/".$id; ?>"><i class="fa fa-edit"></i> Edit</a>                                
                        </div>
                            <a target="_blank" class="btn btn-primary btn-xs" href="<?php echo "/job/show/".$id; ?>"><i class="fa fa-edit"></i> Details</a>
                        </td>
                    </tr>
                    <?php endforeach;?>

                </tbody>
                <tfoot>
                    <tr>
                        <th>ID</th>
                        <th>Job Title</th>
                        <th>View</th>
                        <th>Company name</th>
                        <th>Deadline</th>
                        <th>Action</th>
                    </tr>
                </tfoot>
            </table>
        </div><!-- /.box-body -->
        
        <div class="box-footer">
            Footer
        </div><!-- /.box-footer-->
    </div><!-- /.box -->
</section><!-- /.content -->

<script type="text/javascript">
    $(function () {
        $("#example1").dataTable();
    });
</script>                