<section class="content">
    <div class="box box-primary">
        <div class="box-header">
            <h1 class="page-heading border-bottom">Edit Business Type</h1>
        </div><!-- /.box-header -->
        <!-- form start -->
        <form data-toggle="validator" role="form" method="post" >
            <div class="box-body">
                <div class="form-group" class="col-md-4">
                    <label for="btype">Edit Business Type</label> <span class="valid_star">*</span>
                    <input type="text" name="bname" class="form-control" id="btype" value="<?php echo $this->btypes->name; ?>" placeholder="Buisness Type" autofocus required>
                </div>
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Update</button>
                    <a class="btn btn-default" href="<?php echo $this->serverUrl()."/admin/btype";?>" role="button">Back</a>
                </div>
            </div>
        </form>
    </div><!-- /.box -->
</section>