<div class="box box-primary">
    <div class="box-header">
        <h1 class="page-heading border-bottom">Add Institute/University</h1>
    </div><!-- /.box-header -->
    <!-- form start -->
    <form data-toggle="validator" role="form" method="post" enctype="multipart/form-data" >
        <div class="box-body">
<?php   if(count($error_messages)){?>
            <div class="box box-solid alert-error">
                <div class="box-tools pull-right">
                    <button data-widget="remove" class="btn btn-box-tool text-gray"><i class="fa fa-times"></i></button>                    
                </div>
                <div class="box-body">
<?php
                foreach($error_messages as $msg)
                    echo $msg;
?>
                </div>
            </div>
<?php   }?>
            <div class="form-group">
                <label for="iname" class="col-sm-2 col-md-2 control-label">Institute/University name: <span class="valid_star">*</span></label>
                <div class="col-sm-10 col-md-5">
                    <input type="text" name="iname" class="form-control" id="iname" value="<?php echo ($this->post_data->iname ? $this->post_data->iname : "");?>" placeholder="Institute/University name" autofocus required>
                    <div id="inst-check"></div>
                </div>
                <div class="clearfix"></div>
            </div>
            
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">About Courses: </label>
                <div class="col-sm-10 col-md-10">
                    <textarea id="about_courses" name="about_courses" rows="10" cols="80"><?php echo ($post_data['about_courses'] ? $post_data['about_courses'] : "");?></textarea>
                </div>
                <div class="clearfix"></div>
            </div>
            
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Is top Institute/University? </label>
                <div class="col-sm-5 col-md-5">                
                    <label>
                        <input type="radio" name="is_top" value="Yes"  class="iradio_minimal-blue minimal" <?php echo ($this->post_data["is_top"] == "Yes") ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["is_top"]) && ($this->results->is_top == "Yes")) ? 'checked=""' : ''; ?> />Yes
                    </label>
                    <label>                    
                        <input type="radio" name="is_top" value="No" class="iradio_minimal-blue minimal"  <?php echo ($this->post_data["is_top"] == "No") ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["is_top"]) && ($this->results->is_top == "No")) ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["is_top"]) && ($this->results->is_top == "")) ? 'checked=""' : ''; ?>  />No
                    </label>
                </div>
                <div class="clearfix"></div>
            </div>
            
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Is Institute/University? </label>
                <div class="col-sm-5 col-md-5">                
                    <label>
                        <input type="radio" name="organigation_status" value="Institute"  class="iradio_minimal-blue minimal" <?php echo ($this->post_data["organigation_status"] == "Institute") ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["organigation_status"]) && ($this->results->organigation_status == "Institute")) ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["organigation_status"]) && ($this->results->organigation_status == "")) ? 'checked=""' : ''; ?> />Institute
                    </label>
                    <label>                    
                        <input type="radio" name="organigation_status" value="University" class="iradio_minimal-blue minimal"  <?php echo ($this->post_data["organigation_status"] == "University") ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["organigation_status"]) && ($this->results->organigation_status == "University")) ? 'checked=""' : ''; ?> />University
                    </label>

                </div>
                <div class="clearfix"></div>
            </div>
            
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Image Upload</label>
                <div class="col-sm-5 col-md-5">                
                    <input type="file" name="image_upload" />

                </div>
                <div class="clearfix"></div>
            </div>
            
            
            

            <div class="box-footer">
                <button type="submit" class="btn btn-primary">Add</button>&nbsp;
                <a class="btn btn-default" href="<?php echo $this->serverUrl()."/admin/institute"; ?>" role="button">Back</a>
            </div>
        </div>
    </form>
</div><!-- /.box -->
<script>
    $(document).ready(function(){
        $("#iname").focusout(function(e){
            var postData=$("#iname").val();
            if(postData!==""){
                var URL="/admin/institute/instcheck";
                $.ajax({
                    url:URL,
                    type:"POST",
                    data:{inst:postData},
                    success:function(data,textStatus,jqXHR){
                        $("#inst-check").show();
                        if(data.success){
                            $("#inst-check").css("color","red");
                            $("#inst-check").html("This Institute already exists");
                            e.preventDefault();
                        }
                        if(!data.success){
                            $("#inst-check").css("color","green");
                            $("#inst-check").html("Institute available");
                        }
                    }
                });
                e.preventDefault();
            }else
                $("#inst-check").hide();
        });
        CKEDITOR.replace('about_courses');
    });
</script>