<div class="box box-primary">
    <div class="box-header">
        <h1 class="page-heading border-bottom">Edit Institute/University</h1>
    </div><!-- /.box-header -->
    <!-- form start -->
    <form data-toggle="validator" role="form" method="post" enctype="multipart/form-data" >
        <div class="box-body">
            <div class="form-group">
                <label for="iname" class="col-sm-2 col-md-2 control-label">Institute/University name: <span class="valid_star">*</span></label>
                <div class="col-sm-10 col-md-5">
                    <input type="text" name="iname" class="form-control" id="iname" value="<?php echo ($this->post_data["iname"] != "") ? $this->post_data["iname"] : $this->results->name; ?>" placeholder="Institute/University name" autofocus required>
                </div>
                <div class="clearfix"></div>
            </div>
            
            <div class="form-group">                
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">About Courses: </label>
                <div class="col-sm-10 col-md-10">
                    <textarea id="about_courses" name="about_courses" rows="10" cols="80"><?php echo ($this->post_data["about_courses"] != "") ? $this->post_data["about_courses"] : $this->results->about_courses; ?></textarea>
                </div>
                <div class="clearfix"></div>
            </div>
            
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Is top Institute/University? </label>
                <div class="col-sm-5 col-md-5">                
                    <label>
                        <input type="radio" name="is_top" value="Yes"  class="iradio_minimal-blue minimal" <?php echo ($this->post_data["is_top"] == "Yes") ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["is_top"]) && ($this->results->is_top == "Yes")) ? 'checked=""' : ''; ?> />Yes
                    </label>
                    <label>                    
                        <input type="radio" name="is_top" value="No" class="iradio_minimal-blue minimal"  <?php echo ($this->post_data["is_top"] == "No") ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["is_top"]) && ($this->results->is_top == "No")) ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["is_top"]) && ($this->results->is_top == "")) ? 'checked=""' : ''; ?>  />No
                    </label>

                </div>
                <div class="clearfix"></div>
            </div>
            
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Is Institute/University? </label>
                <div class="col-sm-5 col-md-5">                
                    <label>
                        <input type="radio" name="organigation_status" value="Institute"  class="iradio_minimal-blue minimal" <?php echo ($this->post_data["organigation_status"] == "Institute") ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["organigation_status"]) && ($this->results->organigation_status == "Institute")) ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["organigation_status"]) && ($this->results->organigation_status == "")) ? 'checked=""' : ''; ?> />Institute
                    </label>
                    <label>                    
                        <input type="radio" name="organigation_status" value="University" class="iradio_minimal-blue minimal"  <?php echo ($this->post_data["organigation_status"] == "University") ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["organigation_status"]) && ($this->results->organigation_status == "University")) ? 'checked=""' : ''; ?> />University
                    </label>

                </div>
                <div class="clearfix"></div>
            </div>
            
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Image Upload</label>
                <div class="col-sm-5 col-md-5">                
                    <input type="file" name="image_upload" />
                    
                    <?php if($this->results->institute_logo !=''){?>
                    <img width="150" height="150" src="<?php echo $this->results->institute_logo ?>" />
                    <?php }?>
                </div>
                <div class="clearfix"></div>
            </div>
            

            <div class="box-footer">
                <button type="submit" class="btn btn-primary">Update</button>&nbsp;
                <a class="btn btn-default" href="<?php echo $this->serverUrl()."/admin/institute"; ?>" role="button">Back</a>
            </div>
        </div>
    </form>
</div><!-- /.box -->

<script type="text/javascript">
    $(document).ready(function(){
        CKEDITOR.replace('about_courses');
    });
</script>