<section class="content">

    <div class="box box-primary">
        <div class="box-header">
            <h1 class="page-heading border-bottom">Add Job Circular Type</h1>
        </div><!-- /.box-header -->
        <!-- form start -->
        <form data-toggle="validator" role="form" method="post" >
<?php   if(count($error_messages)){?>
            <div class="box box-solid alert-error">
                <div class="box-tools pull-right">
                    <button data-widget="remove" class="btn btn-box-tool text-gray"><i class="fa fa-times"></i></button>                    
                </div>
                <div class="box-body">
<?php
                foreach($error_messages as $msg)
                    echo $msg;
?>
                </div>
            </div>
<?php }?>
            <div class="box-body">
                <div class="form-group">
                    <label for="jcircular">Job Circular Type</label>
                    <input type="text" name="jsname" class="form-control" id="jcircular" value="<?php echo (!empty($post_data['jsname'])) ? $post_data['jsname'] : '';?>" placeholder="Job Circular type" autofocus required>
                </div>
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Add</button>
                    <a class="btn btn-default" href="<?php echo $this->serverUrl()."/admin/circularType";?>" role="button">Back</a>
                </div>    
            </div><!-- /.box -->
        </form>
    </div>
</section>