<div class="box box-primary">
    <div class="box-header">
        <h1 class="page-heading border-bottom">Add Education Degree</h1>
    </div><!-- /.box-header -->
    <!-- form start -->
    <form data-toggle="validator" role="form" method="post" >
        <div class="box-body">
<?php   if(count($error_messages)){?>
            <div class="box box-solid alert-error">
                <div class="box-tools pull-right">
                    <button data-widget="remove" class="btn btn-box-tool text-gray"><i class="fa fa-times"></i></button>                    
                </div>
                <div class="box-body">
<?php
                foreach($error_messages as $msg)
                    echo $msg;
?>
                </div>
            </div>
<?php   }?>
            <div class="form-group">
                <label for="edegree">Degree name</label> <span class="valid_star">*</span>
                <input type="text" name="dname" class="form-control" id="edegree" value="<?php echo ($this->post_data->dname ? $this->post_data->dname : "");?>" placeholder="Degree name" autofocus required>
                <div id="edegree-check"></div>
            </div>

            <div class="box-footer">
                <button type="submit" class="btn btn-primary">Add</button>
                <a class="btn btn-default" href="<?php echo $this->serverUrl()."/admin/edegree";?>" role="button">Back</a>
            </div>
        </div>
    </form>
</div><!-- /.box -->
<script>
    $(document).ready(function(){
        $("#edegree").focusout(function(e){
            var postData=$("#edegree").val();
            if(postData!==""){
                var URL="/admin/edegree/edegreecheck";
                $.ajax({
                    url:URL,
                    type:"POST",
                    data:{edegree:postData},
                    success:function(data,textStatus,jqXHR){
                        $("#edegree-check").show();
                        if(data.success){
                            $("#edegree-check").css("color","red");
                            $("#edegree-check").html("This Education Degree already exists");
                            e.preventDefault();
                        }
                        if(!data.success){
                            $("#edegree-check").css("color","green");
                            $("#edegree-check").html("Education Degree available");
                        }
                    }
                });
                e.preventDefault();
            }else
                $("#edegree-check").hide();
        });
        $('input').on('ifChecked', function(event){
            alert(event.type + ' callback');
        });
    });
</script>