<div class="box box-primary">
    <div class="box-header">
        <h1 class="page-heading border-bottom">Edit Education Degree</h1>
    </div><!-- /.box-header -->
    <!-- form start -->
    <form data-toggle="validator" role="form" method="post" >
      <div class="box-body">
        <div class="form-group">
          <label for="edegree">Degree name</label> <span class="valid_star">*</span>
          <input type="text" name="degree_name" class="form-control" id="edegree" value="<?php echo $this->edegree->name; ?>" placeholder="Buisness Type" autofocus required>
        </div>
        <div class="box-footer">
          <button type="submit" class="btn btn-primary">Update</button>
          <a class="btn btn-default" href="<?php echo $this->serverUrl()."/admin/edegree";?>" role="button">Back</a>
        </div>
      </div>
    </form>
</div><!-- /.box -->