<?php
namespace Application\Form;

use Zend\Form\Form;
use Zend\InputFilter\Factory;

class EventForm extends Form{
    public $inputFilter;

    function __construct($name=null){
        parent::__construct("Event Form");

        $factory=new Factory();
        $this->inputFilter=$factory->createInputFilter(array(
            'event_id'=>array(
                'name'=>'event_id',
                'required'=>true,
                'filters'=>array(array('name'=>'Int')),
                'validators'=>array(array('name'=>'not_empty'))
            ),
            'name'=>array(
                'name'=>'name',
                'required'=>true,
                'filters'=>array(
                    array('name'=>'StripTags'),
                    array('name'=>'StringTrim')
                ),
                'validators'=>array(
                    array(
                        'name'=>'StringLength',
                        'options'=>array(
                            'encoding'=>'UTF-8',
                            'min'=>1,
                            'max'=>255
                        )
                    ),
                    array('name'=>'not_empty')
                )
            ),
            'company_name'=>array(
                'name'=>'company_name',
                'required'=>true,
                'filters'=>array(
                    array('name'=>'StripTags'),
                    array('name'=>'StringTrim'),
                ),
                'validators'=>array(
                    array(
                        'name'=>'StringLength',
                        'options'=>array(
                            'encoding'=>'UTF-8',
                            'min'=>1,
                            'max'=>255
                        )
                    ),
                    array('name'=>'not_empty')
                )
            ),
            'address'=>array(
                'name'=>'address',
                'required'=>true,
                'filters'=>array(
                    array('name'=>'StripTags'),
                    array('name'=>'StringTrim'),
                ),
                'validators'=>array(
                    array(
                        'name'=>'StringLength',
                        'options'=>array(
                            'encoding'=>'UTF-8',
                            'min'=>1,
                            'max'=>255
                        )
                    ),
                    array('name'=>'not_empty')
                )
            ),
            'email'=>array(
                'name'=>'email',
                'required'=>true,
                'filters'=>array(
                    array('name'=>'StripTags'),
                    array('name'=>'StringTrim'),
                ),
                'validators'=>array(
                    array(
                        'name'=>'StringLength',
                        'options'=>array(
                            'encoding'=>'UTF-8',
                            'min'=>1,
                            'max'=>255
                        )
                    ),
                    array('name'=>'not_empty')
                )
            ),
            'website'=>array(
                'name'=>'website',
                'required'=>true,
                'filters'=>array(
                    array('name'=>'StripTags'),
                    array('name'=>'StringTrim'),
                ),
                'validators'=>array(
                    array(
                        'name'=>'StringLength',
                        'options'=>array(
                            'encoding'=>'UTF-8',
                            'min'=>1,
                            'max'=>255
                        )
                    ),
                    array('name'=>'not_empty')
                )
            ),
            'contact_no'=>array(
                'name'=>'contact_no',
                'required'=>true,
                'filters'=>array(
                    array('name'=>'StripTags'),
                    array('name'=>'StringTrim'),
                ),
                'validators'=>array(
                    array(
                        'name'=>'StringLength',
                        'options'=>array(
                            'encoding'=>'UTF-8',
                            'min'=>1,
                            'max'=>255
                        )
                    ),
                    array('name'=>'not_empty')
                )
            ),
            'note'=>array(
                'name'=>'note',
                'required'=>true,
                'filters'=>array(
                    array('name'=>'StripTags'),
                    array('name'=>'StringTrim'),
                ),
                'validators'=>array(
                    array(
                        'name'=>'StringLength',
                        'options'=>array(
                            'encoding'=>'UTF-8',
                            'min'=>1,
                            'max'=>255
                        )
                    ),
                    array('name'=>'not_empty')
                )
            )
        ));

        return $this;
    }
}