<div class="box box-primary">
    <div class="box-header">
        <h1 class="page-heading border-bottom">Add Functional Category</h1>
    </div><!-- /.box-header -->
    <!-- form start -->

    <form data-toggle="validator" role="form" method="post" >
        <div class="box-body">
<?php       if($this->flashMessenger()->hasCurrentErrorMessages()){?>
                <div class="box box-solid alert-error">
                    <div class="box-tools pull-right">
                        <button data-widget="remove" class="btn btn-box-tool text-gray"><i class="fa fa-times"></i></button>                    
                    </div>
                    <div class="box-body"><?php echo $this->flashMessenger()->setMessageOpenFormat('<strong>')->setMessageCloseString('</strong>')->render('error');?></div>
                </div>
<?php       }?>
            <div class="form-group">
                <label for="jcat">Functional category</label>
                <input type="text" name="jname" class="form-control" id="jcat" value="" placeholder="Functional Category" autofocus required>
                <div id="jcat-check"></div>
            </div>


            <div class="box-footer">
                <button type="submit" class="btn btn-primary">Add</button>
                <a class="btn btn-default" href="<?php echo $this->serverUrl()."/admin/jcategory";?>" role="button">Back</a>
            </div>
        </div>
    </form>
</div>
<script type="text/javascript">
    $(function(){
        $("#jcat").focusout(function(e){
            var postData=$("#jcat").val();
            if(postData!==""){
                var URL="/admin/jcategory/jobCategorycheck";
                $.ajax({
                    url:URL,
                    type:"POST",
                    data:{jcat:postData},
                    success:function(data,textStatus,jqXHR){
                        $("#jcat-check").show();
                        if(data.success){
                            $("#jcat-check").css("color","red");
                            $("#jcat-check").html("This Category already exists");
                            e.preventDefault();
                        }
                        if(!data.success){
                            $("#jcat-check").css("color","green");
                            $("#jcat-check").html("Category available");
                        }
                    }
                });
                e.preventDefault();
            }else
                $("#jcat-check").hide();
        });
    });
</script>