<?php

use Carbon\Carbon;

$req_route = $this->seeker_helper();
$seeker_message_notification = $req_route['seeker_message_notification'];
$seeker_all_unread_message = $req_route['seeker_all_unread_message'];

$req_route_notification = $this->notification_helper();
$total_notification = $req_route_notification['total_notification'];
$all_notification = $req_route_notification['all_notification'];
$home_helper = $this->home_helper();
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Chakri.com</title>
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico')) ?>
        <link rel="stylesheet" href="<?php echo $this->basePath('/bootstrap/css/bootstrap.min.css'); ?>">         
        <link rel="stylesheet" href="<?php echo $this->basePath('css/style.css'); ?>">
        <link rel="stylesheet" href="<?php echo $this->basePath('css/font-awesome.min.css') ?>">
        <link rel="stylesheet" href="<?php echo $this->basePath('css/jquery.custom-scrollbar.css'); ?>">

<!--        <style>
            .iframe_srapper{
                overflow:hidden;
                width:120px; 
                height:600px;
            }
            .verticle_div_wrapper{
                width: 120px;
                height: 600px;                
                position: fixed;
                left: 0;
                top: 0;
                margin-top: 53px;
            }
            .verticle_div_wrapper.right{
                right: 0;
                left: auto;
            }
            .close{
                background-color: #333;
                cursor: pointer;
                float: right;
                font-size: 12px;
                height: 15px;
                line-height: 13px;
                text-align: center;
                width: 15px;
                position: absolute;
                right: 0;
                z-index: 9999;
                color: #fff;
                right: 105px;
                top: 1px;
            }
            .left{
                top: 0px  !important;
            }
            #widget_27843, #widget_27843 .content div, #widget_27843 .widget, #widget_27843 .p_d_p {
                overflow: visible;
            }
            @media screen and (max-width: 1179px) {
                .desktoponlyview{
                    display:none;
                }
            }
        </style> -->        


        <script src="<?php echo $this->basePath('js/jquery.min.js'); ?>"></script>  


        <!--        DFP Script for Advertisement-->
        <script type='text/javascript'>
            var googletag = googletag || {};
            googletag.cmd = googletag.cmd || [];
            (function() {
                var gads = document.createElement('script');
                gads.async = true;
                gads.type = 'text/javascript';
                var useSSL = 'https:' == document.location.protocol;
                gads.src = (useSSL ? 'https:' : 'http:') +
                        '//www.googletagservices.com/tag/js/gpt.js';
                var node = document.getElementsByTagName('script')[0];
                node.parentNode.insertBefore(gads, node);
            })();
        </script>

        <script type='text/javascript'>
            googletag.cmd.push(function() {
                googletag.defineSlot('/85406138/Chakri_HP_Sky_120x600_Lft', [120, 600], 'div-gpt-ad-1440666403853-0').addService(googletag.pubads());
                googletag.defineSlot('/85406138/Chakri_HP_Sky_120x600_Rgt', [120, 600], 'div-gpt-ad-1440666477982-0').addService(googletag.pubads());
                googletag.defineSlot('/85406138/Chakri_HP_Middle_970x90', [[970, 90], [728, 90]], 'div-gpt-ad-1440659257413-0').addService(googletag.pubads());
                googletag.defineSlot('/85406138/Chakri_HP_B2_970x90', [[970, 90], [728, 90]], 'div-gpt-ad-1440659522814-0').addService(googletag.pubads());                
                googletag.pubads().enableSingleRequest();
                googletag.enableServices();
            });
        </script>
        
        <script>
            $(document).ready(function(){
                $('.category_job_listing_scroll').scroll(function(){
                    $('this').css('display', 'none');
                });
            });
        </script>
        
        
<!-- ================================SKYSCRAPPER SCRIPT============================================================
        <script type="application/javascript">
            $(document).ready(function() {

            var totalWidth = $('.verticle_div_wrapper.left').width() + $('.verticle_div_wrapper.right').width() + $('.whole_wrapper').width();
            //  alert(totalWidth); totalWidth == 1280 &&
            if( $('body').width() > 1282){ 
            //$('.verticle_div_wrapper').fadeIn("slow");
            _position();
            }

            $('.close').click(function(){
            $('.verticle_div_wrapper').hide();
            });

            $(window).resize(function(){
            totalWidth = $('.verticle_div_wrapper.left').width() + $('.verticle_div_wrapper.right').width() + $('.wrapper').width();
            if(totalWidth > 1280){
            $('.verticle_div_wrapper').hide();
            }else{
            $('.close').click(function(){
            $('.verticle_div_wrapper').hide();
            });
            }
            _position();
            });
            });

            $(window).bind("resize", function(){
            if($('body').width() < 1280){
            $('.verticle_div_wrapper').hide();
            }else{
            $('.verticle_div_wrapper').show();
            _position();
            }
            });	

            function _position(){
            var gap_right = ((document.body.clientWidth-970)/2)-$('.verticle_div_wrapper.right').width();
            $('.verticle_div_wrapper.right').css('right', gap_right + 'px');

            var gap_left = ((document.body.clientWidth-970)/2)-$('.verticle_div_wrapper.left').width();
            $('.verticle_div_wrapper.left').css('left', gap_left + 'px');
            $('.verticle_div_wrapper').show();
            }

            function pclk_hide(){
            $('.verticle_div_wrapper').hide();
            };
        </script>-->
        <!--  Close  DFP Script for Advertisement-->

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container-fluid menu_home">
                <div class="container">
                    <div class="row header_specl_class">

                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>                           
                        </div>

                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav menu_left">
                                <?php
                                if ($user = $this->identity()) {

                                    switch ($user->user_type) {
                                        case 2 :
                                            $my_chakri = '/admin';
                                            break;
                                        case 3:
                                            $my_chakri = '/seeker';
                                            break;
                                        case 4:
                                            $my_chakri = '/employer';
                                            break;
                                    }
                                    ?>
                                    <li class="active"><a href="<?php echo $my_chakri; ?>">My Chakri<span class="sr-only">(current)</span></a></li>
                                <?php } ?>
                                <li><a href="/job">Jobs</a></li>                                
                                <li role="presentation" class="dropdown">
                                    <a class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                                        Resources <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu">


                                        <li><a href="/articles">Home</a></li>
                                        <li><a href=<?php echo "/articles/4"; ?>>Career Articles</a></li>
                                        <li><a href=<?php echo "/articles/3"; ?>>Interview Tips</a></li>
                                        <li><a href=<?php echo "/articles/6"; ?>>Expert Opinion</a></li>


                                    </ul>
                                </li>
                                <li><a href="#">Workshop</a></li>
                                <li><a href="/job?job_type=Intern">Internship</a></li>
                                <li><a href="/contact">Contact us</a></li>                                

                            </ul>

                            <?php
                            if (!$this->identity()) {
                                ?>
                                <ul class="nav navbar-nav navbar-right menu_right">
                                    <li><a href="/login">Login</a></li> 
                                    <li><a href="/registration">Register</a></li>
                                    <!-- <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">English <span class="caret"></span></a>
                                        <ul class="dropdown-menu" role="menu">
                                            <li><a href="#">Bangla</a></li>
                                            <li><a href="#">Another action</a></li>                                        
                                        </ul>
                                    </li> -->
                                    <li class="last_menu_btn"><a href="/employer-registration"><button type="button" class="btn btn-primary btn-sm nav_right_btn">For Employers</button></a></li>


                                </ul>
                            <?php } ?>

                            <!--After  Login -->
                            <?php
                            if ($this->identity()) {
                                ?>

                                <ul class="nav navbar-nav navbar-right menu_right logged_in_menu">
                                    <?php if ($this->identity()->user_type == 3) { ?>
                                        <li class="dropdown messages-menu">
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                                <i class="fa fa-envelope-o"></i>
                                                <span class="label label-success"><?php echo $seeker_message_notification; ?></span>
                                            </a>
                                            <ul class="dropdown-menu">
                                                <li class="header">You have <span class="tolal_notification"><?php echo $seeker_message_notification; ?></span> message.</li>
                                                <li>
                                                    <!-- inner menu: contains the actual data -->
                                                    <ul class="logged_in">
                                                        <?php
                                                        foreach ($seeker_all_unread_message as $row) {
                                                            ?>
                                                            <li>
                                                                <a href="#">    
                                                                    <div><small class="pull-left"><?php echo substr($row["description"], 0, 30) . "..."; ?></small><?php echo ($row["created_at"] != "0000-00-00 00:00:00") ? '<small class="pull-right"><i class="fa fa-clock-o"></i> ' . Carbon::parse($row["created_at"])->diffForHumans() . '</small>' : ""; ?></div>    
                                                                    <div class="clear"></div>
                                                                </a>
                                                            </li>
                                                            <?php
                                                        }
                                                        ?>                                                    
                                                    </ul>
                                                </li>
                                                <li class="footer"><a href="/seeker/mailBox">See All Messages</a></li>
                                            </ul>
                                        </li>
                                    <?php } ?>
                                    <!-- Notifications: style can be found in dropdown.less -->
                                    <li class="dropdown notifications-menu">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                            <i class="fa fa-bell-o"></i>
                                            <span class="label label-warning tolal_notification"><?php echo $total_notification; ?></span>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li class="header">You have <span class="tolal_notification"><?php echo $total_notification; ?></span> notifications</li>
                                            <li>
                                                <!-- inner menu: contains the actual data -->
                                                <ul class="logged_in all_notification">
                                                    <?php foreach ($all_notification as $val) { ?>
                                                        <li>
                                                            <a href="javscript:void(0);">
                                                                <i class="fa fa-users text-aqua"></i> <?php echo $val["subject"]; ?>
                                                            </a>
                                                        </li>
                                                    <?php } ?>
                                                </ul>
                                            </li>
                                            <?php if ($total_notification != 0) { ?>
                                                <li class="footer all_notification"><a onclick href="javascript:void(0);" id="notification_mark">Mark all read</a></li>
                                            <?php } ?>
                                        </ul>
                                    </li>
                                    <li class="dropdown user user-menu">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                            <!--<img src="<?php echo $this->basePath('/dist/img/user2-160x160.jpg'); ?>" class="user-image" alt="User Image"/>-->
                                            <?php
                                            if ($this->identity()) {
                                                ?>

                                                <span class="hidden-xs"><?php
                                                    echo $this->identity()->full_name;
                                                    ?></span>
                                            <?php } ?>
                                        </a>
                                        <ul class="dropdown-menu dropdown-menu_image">

                                            <!-- User image -->
                                            <li class="user-header">
                                                <img src="<?php echo ($this->identity()->profile_image != '') ? $this->identity()->profile_image : $this->basePath('/dist/img/user2-160x160.jpg'); ?>" class="img-circle" alt="User Image" />                                                
                                                <p>
                                                    <?php echo $this->identity()->full_name; ?>

                                                    <?php
                                                    if ($this->identity()->last_login != "" && $this->identity()->last_login != "Y-m-d H:i:s") {
                                                        $dt = Carbon::createFromFormat('Y-m-d H:i:s', $this->identity()->last_login);
                                                        echo "<br><small>Last Logged in " . $dt->toFormattedDateString() . "</small>";
                                                    }
                                                    ?>                                                  
                                                </p>
                                            </li>
                                            <!-- Menu Footer-->
                                            <li class="user-footer">
                                                <div class="pull-left">                                                    
                                                    <a href="<?php echo $my_chakri; ?>/settings" class="btn btn-default btn-flat">Settings</a>
                                                </div>
                                                <div class="pull-right">
                                                    <a href="/logout" class="btn btn-default btn-flat">Log out</a>
                                                </div>
                                                <div class="clearfix"></div>

                                            </li>
                                        </ul>
                                    </li>
                                </ul>

                            <?php } ?>                           


                        </div><!-- /.navbar-collapse -->

                    </div>
                </div> <!-- End of Container-->
            </div><!-- /.container-fluid -->
        </nav>  

        <!-- Home_Skyscraper_Left_120x600 -->
<!--        <div class="verticle_div_wrapper left desktoponlyview">
            <div id='div-gpt-ad-1428567183104-0' style='height:600px; width:120px;'>
                <script type='text/javascript'>
                    googletag.cmd.push(function() {
                        googletag.display('div-gpt-ad-1428567183104-0');
                    });
                </script>
            </div>
        </div>

         Home_Skyscraper_Right_120x600             

        <div class="verticle_div_wrapper right desktoponlyview">
            <div class="close">x</div>
            <div id='div-gpt-ad-1428567055967-0' style='height:600px; width:120px;'>
                <script type='text/javascript'>
                    googletag.cmd.push(function() {
                        googletag.display('div-gpt-ad-1428567055967-0');
                    });
                </script>
            </div>

        </div> -->

        <div class="container-fluid banner_full_bg">

            <div class="container">
                <div class="row banner_middle_bg">                    
                    <a href="/">
                        <img src="/images/chakri.png" alt="chakri" class="logo center-block img-responsive" />
                    </a>

                    <div class="col-xs-12 col-sm-6 col-md-4 pull-right find_your_job_container">
                        <div class="col-xs-6 col-sm-8 col-md-8 no_padding_left no_padding_right mobile_less_360">
                            <h2>Find your Perfect Job</h2>
                            <p>Choose from <?php echo $home_helper['total_jobs']; ?> jobs.<br />
                                Let employers find you online.<br />
                                Receive matching jobs by email                           
                            </p>
                            <p class="big">Easy &amp; 100% free.</p>
                        </div>
                        <div class="col-xs-6 col-sm-4 col-md-4 no_padding_left no_padding_right mobile_less_360">
                            <a href="/registration"><button type="button" class="btn post_cv_btn">Post Resume</button></a>
                        </div>                        
                        <div class="clearfix"></div>
                    </div>                    

                    <div class="col-xs-12 col-sm-12 col-md-12 logo_search_container">
                        <div class="row">

                            <div class="col-xs-12 col-sm-10 col-md-10 col-sm-offset-1 col-md-offset-1 search_container">
                                <form id="" method="get" action ="/job">
                                    <div class="input-group"> 
                                        <div class="col-xs-12 col-sm-4 col-md-4 no_padding_left no_padding_right border_right">
                                            <input name="job_title" type="text" class="form-control search_textbox" aria-label="..." placeholder="Designations, Companies">

                                        </div>
                                        <div class="col-xs-12 col-sm-3 col-md-4 no_padding_left no_padding_right border_right">

                                            <select id="banner_search" class="form-control" name="loc">
                                                <option value="">Location</option>

                                                <?php foreach ($home_helper['division'] as $division) { ?>
                                                    <option value="<?php echo $division['id']; ?>"><?php echo $division['name']; ?></option>
                                                 <!--<input type="text" class="form-control search_textbox" aria-label="..." placeholder="Location">-->
                                                <?php } ?>
                                            </select> 
                                        </div>
                                        <div class="col-xs-12 col-sm-3 col-md-3 no_padding_left no_padding_right">

                                            <select class="form-control" name="experienced" id="banner_search">
                                                <option value="">Experience </option>
                                                <?php
                                                for ($group = 1; $group <= 70; $group ++) {
                                                    ?>
                                                    <option value="<?php echo $group; ?>" ><?php echo $group; ?></option>
                                                    <?php
                                                }
                                                ?>
                                            </select>
                                        </div>  
                                        <div class="col-xs-6 col-md-1 col-sm-2 home_search_btn_container no_padding_left no_padding_right">
                                            <input type="submit" value="Search" class="btn home_search_btn center-block" />
                                        </div>

                                        <p class="advanced_search"><a href="/advancedsearch">Advanced Search</a></p>
                                    </div><!-- /input-group -->
                                </form>
                            </div><!-- /.col-lg-6 -->

                            <div class="col-xs-12 col-sm-10 col-md-10 col-sm-offset-1 col-md-offset-1 browse_jobs_container no_padding_left">
                                <p>Browse Jobs</p>
                                <div class="browse_jobs_item">
                                    <ul>
                                        <li><a href="/job?jtype=newjob">Newly Posted Jobs</a></li>
                                        <li><a href="/companies">Jobs by Company</a></li>
                                        <li><a href="/job?circular_type=govtjob">Govt. Jobs</a></li>
                                        <li><a href="/job?circular_type=newspaper">Newspaper Jobs</a></li>
                                        <li><a href="/job?circular_type=walkinjob">Walk in Interview </a></li>
                                        <li><a href="/job?jtype=deadline_tomorrow">Deadline Tomorrow</a></li>
                                        <div class="clearfix"></div>
                                    </ul>  
                                </div>                           

                            </div>
                        </div>
                    </div> 
                </div> <!-- End of Row -->
            </div> <!-- End of Container -->
        </div> <!-- End of Container fluid -->

        <?php // }  ?>  


        <div class="container-fluid content_full_bg">                           
            <div class="container"> 
                <div class="row">                

                    <script type="text/javascript">
                        $("body").on("click", "#notification_mark", function(e) {

                            e.preventDefault();
                            //console.log($(this).serialize());
                            $.ajax({
                                url: '/chkapi/api/updateSeekerNotification',
                                type: 'post',
                                dataType: 'json',
                                data: {type: 'save'},
                                success: function(data) {
                                    $(".tolal_notification").html("0");
                                    $(".all_notification").remove();
                                }
                            });

                        });
                    </script>
                    <?php echo $this->content; ?>
                    <?php echo $this->render('footer'); ?>