<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Chakri.com</title>
        <link rel="stylesheet" href="<?php echo $this->basePath('css/bootstrap.min.css');?>">        
        <link rel="stylesheet" href="<?php $this->basePath('css/font-awesome.min.css')?>">
        <link rel="stylesheet" href="<?php echo $this->basePath('css/style.css');?>">  
        
        
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
<nav class="navbar navbar-default navbar-fixed-top">
            <div class="container-fluid menu">
                <div class="container">
                    <div class="row">

                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>                           
                        </div>

                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav menu_left">
                                <li class="active"><a href="#">Home<span class="sr-only">(current)</span></a></li>
                                <li><a href="#">About</a></li>
                                <li><a href="#">Specialities</a></li>
                                <li><a href="#">Salaries</a></li>
                                <li><a href="#">Resources</a></li>
                                <li><a href="#">Contact us</a></li>

                            </ul>

                            <ul class="nav navbar-nav navbar-right menu_right">
                                <li><a href="#">Login</a></li> 
                                <li><a href="auth/registration">Register</a></li>
                                <!-- <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">English <span class="caret"></span></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="#">Bangla</a></li>
                                        <li><a href="#">Another action</a></li>                                        
                                    </ul>
                                </li> -->
                                <li class="last_menu_btn"><a href="#"><button type="button" class="btn btn-primary btn-sm nav_right_btn">For Employers</button></a></li>
                            </ul>

                        </div><!-- /.navbar-collapse -->

                    </div>
                </div> <!-- End of Container-->
            </div><!-- /.container-fluid -->
        </nav>   



        <div class="container-fluid content_full_bg">                           
                <div class="container"> 
                    <div class="row">
                            <?php echo $this->content; ?>

                                  </div>
    </div>
</div>

<div class="container-fluid footer_top_full_container">
    <div class="container footer_top_middle_container">
        <div class="row">
            <h4>Find Jobs</h4>
            <div class="footer_top_list">
                <div class="col-xs-12 col-sm-6 col-md-3">
                    <ul>
                        <li><a href="#">Accounting/Banking/Finance Jobs <span class="total_job">(235)</span></a></li>
                        <li><a href="#">Administration Jobs <span class="total_job">(235)</span></a></li>
                        <li><a href="#">Art/Design/Creative Jobs <span class="total_job">(235)</span></a></li>
                        <li><a href="#">Customer Service Jobs</a></li>
                        <li><a href="#">Education/Training Job</a></li>                       
                    </ul>
                </div>

                <div class="col-xs-12 col-sm-6 col-md-3">
                    <ul>
                        <li><a href="#">Accounting/Banking/Finance Jobs <span class="total_job">(235)</span></a></li>
                        <li><a href="#">Administration Jobs <span class="total_job">(235)</span></a></li>
                        <li><a href="#">Art/Design/Creative Jobs <span class="total_job">(235)</span></a></li>
                        <li><a href="#">Customer Service Jobs</a></li>
                        <li><a href="#">Education/Training Job</a></li>                       
                    </ul>
                </div>

                <div class="col-xs-12 col-sm-6 col-md-3">
                    <ul>
                        <li><a href="#">Accounting/Banking/Finance Jobs <span class="total_job">(235)</span></a></li>
                        <li><a href="#">Administration Jobs <span class="total_job">(235)</span></a></li>
                        <li><a href="#">Art/Design/Creative Jobs <span class="total_job">(235)</span></a></li>
                        <li><a href="#">Customer Service Jobs</a></li>
                        <li><a href="#">Education/Training Job</a></li>                       
                    </ul>
                </div>

                <div class="col-xs-12 col-sm-6 col-md-3">
                    <ul>
                        <li><a href="#">Accounting/Banking/Finance Jobs <span class="total_job">(235)</span></a></li>
                        <li><a href="#">Administration Jobs <span class="total_job">(235)</span></a></li>
                        <li><a href="#">Art/Design/Creative Jobs <span class="total_job">(235)</span></a></li>
                        <li><a href="#">Customer Service Jobs</a></li>
                        <li><a href="#">Education/Training Job</a></li>                       
                    </ul>
                </div>
                <div class="clear"></div>
            </div> <!--End of row-->

            <div class="row">
                <div class="about_chakri_container">
                    <div class="hidden-xs col-sm-6 col-md-6">
                        <div class="about_first_container">
                            <h4> About Chakri.com</h4>
                            <p>Chakri.com is the leading job site in the Gulf and Middle East, connecting job seekers with employers looking to hire. Every day, thousands of new job vacancies are listed on the award-winning platform from the region's top employers.</p>

                        </div>
                    </div>

                    <div class="hidden-xs col-sm-2 col-md-2">
                        <div class="about_first_container">
                            <h4> Company</h4>
                            <ul>
                                <li><a href="#">About us</a></li>
                                <li><a href="#">Contact us</a></li>
                                <li><a href="#">Careers</a></li>
                                <li><a href="#">Careers</a></li>
                                <li><a href="#">Careers</a></li>

                            </ul>
                        </div>
                    </div>

                    <div class="hidden-xs col-sm-2 col-md-2">
                        <div class="about_first_container">
                            <h4>Quick Links</h4>
                            <ul>
                                <li><a href="#">About us</a></li>
                                <li><a href="#">Contact us</a></li>
                                <li><a href="#">Careers</a></li>
                                <li><a href="#">Careers</a></li>
                                <li><a href="#">Careers</a></li>                       
                            </ul>
                        </div>
                    </div>

                    <div class="hidden-xs col-sm-2 col-md-2">                                
                        <h4>Follow</h4>
                        <ul class="fa-ul">
                            <li><i class="fa fa-google-plus-square"></i> Google+</li>
                            <li><i class="fa fa-facebook-square"></i> Facebook</li>
                            <li><i class="fa fa-twitter-square"></i> Twitter</li>
                            <li><i class="fa fa-youtube-square"></i> Youtube</li>
                        </ul>             

                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>

</div>


<div class="container-fluid footer_full_container">
    <div class="container">
        <div class="row">
            <div class="footer_middle_container">
                <p><b>&copy; 2000-2015, chakri.com.</b> All rights reserved. <a href="#">Terms of use</a>&nbsp;&nbsp;<a href="#">Privacy Statement</a></p>  
                <p>Reproduction of material of any chakri.com pages without written permission is strictly prohibited.</p>
            </div>
        </div>
    </div>

</div>
<!-- Bootstrap -->
        
       
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
 <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>

<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
</body>
</html>