<section class="content">
<div class="box box-primary">
    <div class="box-header">
        <h1 class="page-heading border-bottom">Add Job Industry</h1>
    </div><!-- /.box-header -->
    <!-- form start -->
    <form data-toggle="validator" role="form" method="post" >
        <div class="box-body">
<?php   if(count($error_messages)){?>
            <div class="box box-solid alert-error">
                <div class="box-tools pull-right">
                    <button data-widget="remove" class="btn btn-box-tool text-gray"><i class="fa fa-times"></i></button>                    
                </div>
                <div class="box-body">
<?php
                foreach($error_messages as $msg)
                    echo $msg;
?>
             </div>
            </div>
<?php   }?>
            <div class="form-group">
                <label for="exampleInputEmail1">Job Industry</label>
                <input type="name" name="jcname" class="form-control" id="name" value="<?php echo (!empty($post_data['jcname']) ? $post_data['jcname'] : '');?>" placeholder="Job Industry" autofocus required>
            </div>
            <div class="box-footer">
                <button type="submit" class="btn btn-primary">Add</button>
                <a class="btn btn-default" href="<?php echo $this->serverUrl()."/admin/Jobindustry";?>" role="button">Back</a>
            </div>
        </div>
    </form>
</div><!-- /.box -->
</section>