<?php use Carbon\Carbon; ?>
<section class="content">

    <!-- Default box -->
    <div class="box box-default">
        <div class="box-header with-border">

            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <h3 class="box-title pull-left page-heading">Job Industry</h3>
                    <div class="pull-right">
                        <div class="btn-group">
                            <a class="btn btn-success"  href="<?php echo "/admin/Jobindustry/add"; ?>" ><i class="fa fa-plus"></i> Add New</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="box-body">           

            <?php
            if ($this->flashMessenger()->hasCurrentSuccessMessages()) {
                ?>
                <div class="box box-success box-solid alert-success">
                    <div class="box-tools pull-right">
                        <button data-widget="remove" class="btn btn-box-tool text-gray"><i class="fa fa-times"></i></button>                    
                    </div><!-- /.box-tools -->

                    <div class="box-body">
                        <?php   
                        echo $this->flashMessenger()
                                ->setMessageOpenFormat('<strong>')
                                ->setMessageCloseString('</strong>')
                                ->render('success');
                        ?> 
                    </div><!-- /.box-body -->
                </div><!-- /.box -->
                <?php
            }
            ?>

            <table id="example1" class="table table-bordered table-striped table-condensed">
                <thead>
                    <tr>
                        <th>SN.</th>
                        <th>Industry Name </th>
                        <th>Modified By </th>
                        <th>Updated at </th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->industryTypes as $key=>$industryType): ?>
                        <tr>
                            <td><?php echo $key+1;?></td>
                            <td><?php echo $industryType['name']; ?></td>                            
                            <td><?php echo $industryType['full_name']; ?></td>
                            <td>
                              <?php
                                $dt = Carbon::createFromFormat('Y-m-d H:i:s',$industryType['updated_at']);
                                echo $dt->toFormattedDateString();
                              ?>
                            </td>

                            <td>
                                <div class="btn-group">
                                    <a class="btn btn-primary btn-xs" href='<?php echo "/admin/Jobindustry/edit/".$industryType['id'];?>' target="_blank"><i class="fa fa-edit"></i> Edit</a>
                                    <form method="POST" action="<?php echo "/admin/Jobindustry/delete/".$industryType['id']; ?>" accept-charset="UTF-8" style="display:inline">
                                            <button style="border-bottom-left-radius:0;border-top-left-radius:0;" class="btn btn-xs btn-danger" type="button" data-toggle="modal" data-target="#confirmDelete" data-title="Delete Industry" data-message="Are you sure you want to delete this Industry ?">
                                                <i class="glyphicon glyphicon-trash"></i> Delete
                                            </button>
                                        </form>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
                <tfoot>
                    <tr>
                        <th>SN.</th>
                        <th>Industry Name </th>
                        <th>Modified By </th>
                        <th>Updated at </th>
                        <th>Action</th>
                    </tr>
                </tfoot>
            </table>
        </div><!-- /.box-body -->

    </div><!-- /.box -->

</section><!-- /.content -->





<script type="text/javascript">

    var objectId;
    $(function() {
        $("#example1").dataTable();

        //triggered when modal is about to be shown
        $('#del-popup').on('show.bs.modal', function(e) {
            objectId = $(e.relatedTarget).data('id');
            $(e.currentTarget).find('input[name="dataId"]').val(objectId);
        });

        $('#del-popup').find('#btn_save').on('click', function(e) {
            var id = $("#dataId").val();
          var del_url = '/jcategory/delete/' + id;
            window.location.replace(del_url);

        });


    });
</script>