<section class="content">
    <div class="box box-default admin_form_bg">
        <?php if($this->flashMessenger()->hasCurrentErrorMessages()){?>
        <div class="box box-solid alert-error">
            <div class="box-tools pull-right">
                <button data-widget="remove" class="btn btn-box-tool text-gray"><i class="fa fa-times"></i></button>                    
            </div>
            <div class="box-body"><?php echo $this->flashMessenger()->render('error');?></div>
        </div>
        <?php }?>
        
        <?php if (count($this->error_messages) > 0) { ?>
            <div class="alert alert-danger">
                <?php           
                foreach ($this->error_messages as $messageId => $message) {
                    echo "<p>  $message </p>";
                }
                ?>   
            </div> 
        <?php } ?>
        
        <form role="form" data-toggle="validator" class="form-horizontal register_employer_form" method="post" enctype="multipart/form-data">
            <h1 class="page-heading border-bottom">Add New page content</h1>
            
            <div class="form-group">
                <label for="title" class="col-sm-2 col-md-2 control-label">Page title:</label>
                <div class="col-sm-5 col-md-5">
                    <input type="text" class="form-control" id="title" name="title" value="<?php echo ($this->post_data["title"] != "") ? $this->post_data["title"] : $this->result["title"]; ?>" placeholder="Page Title" />
                </div>
                <div class="clearfix"></div>
            </div>
            
            <div class="form-group">
                <label for="title" class="col-sm-2 col-md-2 control-label">Page alias:</label>
                <div class="col-sm-5 col-md-5">
                    <input type="text" class="form-control" id="title" name="alias" value="<?php echo ($this->post_data["alias"] != "") ? $this->post_data["alias"] : $this->result["alias"]; ?>" placeholder="Page alias" />
                </div>
                <div class="clearfix"></div>
            </div>
            
            <div class="form-group">
                <label for="title" class="col-sm-2 col-md-2 control-label">Page meta key:</label>
                <div class="col-sm-5 col-md-5">
                    <textarea class="form-control" name="meta_key" placeholder="Page meta key"><?php echo ($this->post_data["meta_key"] != "") ? $this->post_data["meta_key"] : $this->result["meta_key"]; ?></textarea>                    
                </div>
                <div class="clearfix"></div>
            </div>
            
            <div class="form-group">
                <label for="title" class="col-sm-2 col-md-2 control-label">Page meta description:</label>
                <div class="col-sm-5 col-md-5">
                    <textarea class="form-control" name="meta_description" placeholder="Page meta description"><?php echo ($this->post_data["meta_description"] != "") ? $this->post_data["meta_description"] : $this->result["meta_description"]; ?></textarea>                    
                </div>
                <div class="clearfix"></div>
            </div>
            
            <div class="form-group">
                <label class="col-sm-2 col-md-2 control-label">Page content:</label>
                <div class="col-sm-10 col-md-10">
                    <textarea id="short-description" name="content" rows="10" cols="80" required><?php echo ($this->post_data["content"] != "") ? $this->post_data["content"] : $this->result["content"]; ?></textarea>
                </div>
                <div class="clearfix"></div>
            </div>            
           
            <div class="form-group">
                <div class=" col-xs-12 col-sm-6 col-md-6 col-sm-offset-2 col-md-offset-2 btn_submit">
                    <button type="submit" class="btn btn-primary pull-left">Submit</button>&nbsp;
                    <a class="btn btn-default" href="<?php echo $this->serverUrl()."/admin/cms"; ?>" role="button">Back</a>
                </div>
            </div>            
            <div class="clearfix"></div>
        </form>
    </div>
</section>
<script type="text/javascript">
    $(function(){
        $("[data-mask]").inputmask();
        CKEDITOR.replace('short-description');
        CKEDITOR.replace('description');

        //iCheck for checkbox and radio inputs
        $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
            checkboxClass: 'icheckbox_minimal-blue',
            radioClass: 'iradio_minimal-blue'
        });
    });
</script>