<?php use Carbon\Carbon; ?>
<section class="content">

    <!-- Default box -->
    <div class="box box-default">
        <div class="box-header with-border">

            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <h1 class="pull-left page-heading">CMS</h1>
                    <div class="pull-right">
                        <div class="btn-group">
                            <a class="btn btn-success"  href="<?php echo "/admin/cms/add"; ?>" ><i class="fa fa-plus"></i> Add New</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <?php
        if ($this->flashMessenger()->hasCurrentSuccessMessages()) {
            ?>
            <div class="box box-success box-solid alert-success">
                <div class="box-tools pull-right">
                    <button data-widget="remove" class="btn btn-box-tool text-gray"><i class="fa fa-times"></i></button>                    
                </div><!-- /.box-tools -->

                <div class="box-body">
                    <?php
                    //$flashMessenger = $this->flashMessenger();
                    //if ($flashMessenger->hasMessages()) {     
                    echo $this->flashMessenger()
                            ->setMessageOpenFormat('<strong>')
                            ->setMessageCloseString('</strong>')
                            ->render('success');
                    //} 
                    ?> 
                </div><!-- /.box-body -->
            </div><!-- /.box -->
            <?php
        }
        ?>
        
        
        <div class="box-body">
            <table id="example1" class="table table-bordered table-striped table-condensed">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Page title</th>
                        <th>Alias</th>                        
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->results as $btype): ?>

                        <tr>
                            <td><?php echo $id = $btype["id"]; ?></td>
                            <td><?php echo $btype["title"]; ?></td>                            
                            <td><?php echo $pageName = $btype["alias"]; ?></td>                            
                            <td>
                                <div class="btn-group">
                                    <a class="btn btn-success btn-xs" href='<?php echo "/page/$pageName"; ?>' target="_blank"><i class="fa fa-eye"></i> Preview</a>
                                    <a class="btn btn-primary btn-xs" href='<?php echo "/admin/cms/edit/$id"; ?>' target="_blank"><i class="fa fa-edit"></i> Edit</a>
                                    <!--<a class="btn btn-danger btn-xs" href="<?php echo "/admin/btype/delete/$id"; ?>"  data-id="<?php echo $id; ?>" data-target="#del-popup" onclick="return(confirm('Are you sure you want to delete this?'));"> <i class="fa fa-remove"></i> Delete</a>-->
                                    <form method="POST" action="<?php echo "/admin/cms/delete/$id"; ?>" accept-charset="UTF-8" style="display:inline">                                      
                                        <button style="border-bottom-left-radius:0;border-top-left-radius:0;" class="btn btn-xs btn-danger" type="button" data-toggle="modal" data-target="#confirmDelete" data-title="Delete Content" data-message="Are you sure you want to delete this content ?">
                                            <i class="glyphicon glyphicon-trash"></i> Delete
                                        </button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach; ?>

                </tbody>
                <tfoot>
                    <tr>
                        <th>ID</th>
                        <th>Page title</th>
                        <th>Alias</th>                        
                        <th>Action</th>
                    </tr>
                </tfoot>
            </table>
        </div><!-- /.box-body -->

    </div><!-- /.box -->

</section><!-- /.content -->





<script type="text/javascript">

    var objectId;
    $(function() {
        //$("#example1").dataTable();
        $('#example1').dataTable( {
            "order": [[ 0, "desc" ]]
        });

        //triggered when modal is about to be shown
        /*
        $('#del-popup').on('show.bs.modal', function(e) {
            //get data-id attribute of the clicked element
            objectId = $(e.relatedTarget).data('id');
            //populate the textbox
            $(e.currentTarget).find('input[name="dataId"]').val(objectId);
        });

        $('#del-popup').find('#btn_save').on('click', function(e) {
            var id = $("#dataId").val();
            var del_url = '/btype/delete/' + id;
            //alert (del_url);
            //window.location = del_url;
            // similar behavior as an HTTP redirect
            window.location.replace(del_url);

        });
        */


    });
</script>