<div class="box box-primary">
    <div class="box-header">
        <h1 class="page-heading border-bottom">Add Department Type</h1>
    </div><!-- /.box-header -->
    <!-- form start -->
    <form data-toggle="validator" role="form" method="post" >
        <div class="box-body">
<?php   if(count($error_messages)){?>
            <div class="box box-solid alert-error">
                <div class="box-tools pull-right">
                    <button data-widget="remove" class="btn btn-box-tool text-gray"><i class="fa fa-times"></i></button>                    
                </div>
                <div class="box-body">
<?php
                foreach($error_messages as $msg)
                    echo $msg;
?>
                </div>
            </div>
<?php   }?>
            <div class="form-group">
                <label for="dname">Department Type</label> <span class="valid_star">*</span>
                <input type="text" name="dname" class="form-control" id="dname" value="<?php echo ($this->post_data->dname ? $this->post_data->dname : "");?>" placeholder="Department Type" autofocus required>
                <div id="dname-check"></div>
            </div>
            <!--
            <div class=" form-group">
                <label>
                    <input type="checkbox"> Active
                </label>
            </div>
            -->


            <div class="box-footer">
                <button type="submit" class="btn btn-primary">Add</button>
                <a class="btn btn-default" href="<?php echo $this->serverUrl()."/admin/department";?>" role="button">Back</a>
            </div>
        </div>
    </form>
</div>
<script>
    $(function(){
        $("#dname").focusout(function(e){
            var postData=$("#dname").val();
            if(postData!==""){
                var URL="/admin/department/dnamecheck";
                $.ajax({
                    url:URL,
                    type:"POST",
                    data:{dname:postData},
                    success:function(data,textStatus,jqXHR){
                        $("#dname-check").show();
                        if(data.success){
                            $("#dname-check").css("color","red");
                            $("#dname-check").html("This Department Type already exists");
                            e.preventDefault();
                        }
                        if(!data.success){
                            $("#dname-check").css("color","green");
                            $("#dname-check").html("Department Type available");
                        }
                    }
                });
                e.preventDefault();
            }else
                $("#dname-check").hide();
        });
    });
</script>