<div class="box box-primary">
    <div class="row">
    <div class="col-md-5">
        <div class="box-header">
            <h1 class="page-heading border-bottom">Edit Preferred role</h1>
        </div><!-- /.box-header -->
        <!-- form start -->
        <form data-toggle="validator" role="form" method="post" >
            <div class="box-body">   
                <div class="form-group">
                    <label for="exampleInputEmail1">Function <span class="valid_star">*</span></label>
                    <select class="form-control" name="department_id" required>
                        <option value="" >Select function</option>
                        <?php
                        foreach($functions as $row)
                        {
                           ?>
                            <option value="<?php echo $row["id"]?>" <?php echo (($this->results->department_id == $row["id"])) ? 'selected=""' : ''; ?>><?php echo $row["name"]; ?></option>
                           <?php
                        }
                        ?>
                    </select>
                </div>

                <div class="form-group">
                    <label for="exampleInputEmail1">Role Name <span class="valid_star">*</span></label>
                    <input type="text" name="rname" class="form-control" id="rname" value="<?php echo ($this->results->name !="") ? $this->results->name : ""; ?>" placeholder="Role Name" required>
                </div>

                <div class="form-group"> 
                    <label for="Staus">Status</label>
                    <input type="radio" name="status" value="1" class="minimal" <?php echo ($this->results->status == "1") ? 'checked=""' : ''; ?> checked />ACTIVE                
                    <input type="radio" name="status" value="0" class="minimal" <?php echo ($this->results->status == "0") ? 'checked=""' : ''; ?> />INACTIVE
                </div>

                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Update</button>
                    <a class="btn btn-default" href="<?php echo $this->serverUrl()."/admin/department/jobrole";?>" role="button">Back</a>
                </div>
            </div>
        </form>
    </div>
    </div>
</div><!-- /.box -->


<script type="text/javascript">    
      $(function(){                  
        
        //iCheck for checkbox and radio inputs
        $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
          checkboxClass: 'icheckbox_minimal-blue',
          radioClass: 'iradio_minimal-blue'
        }); 
      });
</script>