<div class="box box-primary">
    <div class="box-header">
        <h1 class="page-heading border-bottom">Edit Department Type</h1>
    </div><!-- /.box-header -->
    <!-- form start -->
    <form data-toggle="validator" role="form" method="post" >
        <div class="box-body">
            <div class="form-group">
                <label for="dname">Department Type</label> <span class="valid_star">*</span>
                <input type="text" name="dname" class="form-control" id="dname" value="<?php echo $this->dtypes->name; ?>" placeholder="Department Type" autofocus required>
            </div>
            
            <!--
            <div class=" form-group">
                <label>
                    <input type="checkbox"> Active
                </label>
            </div>
            -->


            <div class="box-footer">
                <button type="submit" class="btn btn-primary">Update</button>
                <a class="btn btn-default" href="<?php echo $this->serverUrl()."/admin/department";?>" role="button">Back</a>
            </div>
        </div>
    </form>
</div><!-- /.box -->