<?php use Carbon\Carbon; ?>
<section class="content">
    <!-- Default box -->
    <div class="box box-default">
        <div class="box-header with-border">
<?php   if($this->flashMessenger()->hasCurrentSuccessMessages()){?>
            <div class="box box-solid alert-success">
                <div class="box-tools pull-right">
                    <button data-widget="remove" class="btn btn-box-tool text-gray"><i class="fa fa-times"></i></button>
                </div>
                <div class="box-body"><?php echo $this->flashMessenger()->render('success');?></div>
            </div>
<?php   }?>
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 reports_date">
                    <div class="pull-left"><h4>Total Contact Queries : <?php echo $this->total_contact;?> | Total Resolved Queries : <?php echo $this->resolved;?> | Total Pending Queries : <?php echo $this->pending;?></h4></div>
                    <div class="btn-group reports_download_btn">
                        <a href="<?php echo $this->url($this->route, array('action'=>'downloadcsv'), array('query' => $params)); ?><?php echo (count($params)>0) ? "&" :"?"; ?>page=<?php echo $currentpage;?>&type=spotlightjob" class="btn btn-primary"><i class="fa fa-download"></i> Download</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="box-body">
            <table id="example1" class="table table-bordered table-striped table-condensed table-responsive">
                <thead>
                    <tr>
                        <th>SN.</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Phone No.</th>
                        <th>Resolved By</th>
                        <th>Type</th>
                        <th>Updated at</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
<?php           foreach ($this->contacts as $key=>$contact):?>
                    <tr>
                        <td><?php echo $key+1;?></td>
                        <td><?php echo $contact["name"];?></td>
                        <td><?php echo $contact["email"];?></td>
                        <td><?php echo $contact["phone"];?></td>
                        <td><?php echo $contact["full_name"];?></td>
                        <td><?php echo $contact["issue"];?></td>
                        <td>
<?php
                            $dt = Carbon::createFromFormat('Y-m-d H:i:s',$contact["updated_at"]);
                            echo $dt->toFormattedDateString();
?>
                        </td>
                        <td><?php echo ($contact['view_status']==0)?"Pending":"Resolved";?></td>
                        <td>
                            <div class="btn-group">
                                <a class="btn btn-primary btn-xs" href='<?php echo "/admin/contact/show/$contact[id]"; ?>' target="_blank"><i class="fa fa-edit"></i> Show</a>
                                <!--<a class="btn btn-danger btn-xs" href="<?php echo "/admin/btype/delete/$contact[id]"; ?>"  data-id="<?php echo $id; ?>" data-target="#del-popup" onclick="return(confirm('Are you sure you want to delete this?'));"> <i class="fa fa-remove"></i> Delete</a>-->
                                <form method="POST" action="<?php echo "/admin/contact/delete/$contact[id]"; ?>" accept-charset="UTF-8" style="display:inline">
                                    <button style="border-bottom-left-radius:0;border-top-left-radius:0;" class="btn btn-xs btn-danger" type="button" data-toggle="modal" data-target="#confirmDelete" data-title="Delete contact query" data-message="Are you sure you want to delete this query ?">
                                        <i class="glyphicon glyphicon-trash"></i> Delete
                                    </button>
                                </form>
                            </div>
                        </td>
                    </tr>
<?php           endforeach;?>
                </tbody>
                <tfoot>
                    <tr>
                        <th>SN.</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Phone No.</th>
                        <th>Message</th>
                        <th>Type</th>
                        <th>Posting Date</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </tfoot>
            </table>
        </div><!-- /.box-body -->
    </div><!-- /.box -->
</section><!-- /.content -->

<script type="text/javascript">
    var objectId;
    $(function() {
        $('#example1').dataTable( {
            "order": [[ 6, "dec" ]]
        });

        //triggered when modal is about to be shown
        /*
        $('#del-popup').on('show.bs.modal', function(e) {
            //get data-id attribute of the clicked element
            objectId = $(e.relatedTarget).data('id');
            //populate the textbox
            $(e.currentTarget).find('input[name="dataId"]').val(objectId);
        });

        $('#del-popup').find('#btn_save').on('click', function(e) {
            var id = $("#dataId").val();
            var del_url = '/btype/delete/' + id;
            //alert (del_url);
            //window.location = del_url;
            // similar behavior as an HTTP redirect
            window.location.replace(del_url);

        });
        */


    });
</script>