<section class="content">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="page-heading border-bottom">Add Article Category</h3>
        </div>
        <form data-toggle="validator" role="form" method="post" >
            <div class="box-body">
<?php       if(count($error_messages)){?>
                <div class="box box-solid alert-error">
                    <div class="box-tools pull-right">
                        <button data-widget="remove" class="btn btn-box-tool text-gray"><i class="fa fa-times"></i></button>
                    </div>
                    <div class="box-body">
<?php
                    foreach($error_messages as $msg)
                        echo $msg;
?>
                    </div>
                </div>
<?php       }?>
                <div class="form-group col-sm-12 col-md-4 no-padding">
                    <label for="title">Title</label> <span class="valid_star">*</span>
                    <input type="text" name="title" class="form-control" id="title" value="<?php echo (!empty($post_data['title']) ? $post_data['title'] : "");?>" placeholder="Category Title" autofocus required />
                    <div id="title-check"></div>
                </div>
                <div class="clearfix"></div>
                <div class="form-group no-padding">
                    <label class="col-sm-1 col-md-1 control-label">Is Active?</label>
                    <div class="col-sm-5 col-md-5">
                        <label><input type="radio" name="status" value="1" class="minimal" checked />Yes</label>
                        <label><input type="radio" name="status" value="0" class="minimal" />No</label>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Add</button>
                    <a class="btn btn-default" href="<?php echo $this->serverUrl()."/admin/articleCategory";?>" role="button">Back</a>
                </div>
            </div>
        </form>
    </div>
</section>
<script type="text/javascript">
    $(function(){
        $("#title").focusout(function(e){
            var postData=$("#title").val();
            if(postData!==""){
                var URL="/admin/articleCategory/titlecheck";
                $.ajax({
                    url:URL,
                    type:"POST",
                    data:{title:postData},
                    success:function(data,textStatus,jqXHR){
                        $("#title-check").show();
                        if(data.success){
                            $("#title-check").css("color","red");
                            $("#title-check").html("This Category already exists");
                            e.preventDefault();
                        }
                        if(!data.success){
                            $("#title-check").css("color","green");
                            $("#title-check").html("Category available");
                        }
                    }
                });
                e.preventDefault();
            }else
                $("#title-check").hide();
        });
    });
</script>