<section class="content">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="page-heading border-bottom">Edit Article Category</h3>
        </div>
        <form data-toggle="validator" role="form" method="post" >
            <div class="box-body">
<?php       if($this->flashMessenger()->hasCurrentErrorMessages()){?>
                <div class="box box-solid alert-error">
                    <div class="box-tools pull-right">
                        <button data-widget="remove" class="btn btn-box-tool text-gray"><i class="fa fa-times"></i></button>                    
                    </div>
                    <div class="box-body"><?php echo $this->flashMessenger()->setMessageOpenFormat('<strong>')->setMessageCloseString('</strong>')->render('error');?></div>
                </div>
<?php       }?>
                <div class="form-group col-sm-12 col-md-4 no-padding">
                    <label for="title">Title</label> <span class="valid_star">*</span>
                    <input type="text" name="title" id="title" class="form-control" value="<?php echo $cat['title'];?>" placeholder="Category Title" autofocus required />
                </div>
                <div class="clearfix"></div>

                <div class="form-group no-padding">
                    <label class="col-sm-1 col-md-1 control-label">Is Active?</label>
                    <div class="col-sm-5 col-md-5">
                        <label><input type="radio" name="status" value="1" class="minimal" <?php echo ($cat['status']==1)?"checked":""?> />Yes</label>
                        <label><input type="radio" name="status" value="0" class="minimal" <?php echo ($cat['status']==0)?"checked":""?> />No</label>
                    </div>
                    <div class="clearfix"></div>
                </div>

                <div class="form-group">
                    <input type="submit" class="btn btn-primary" value="Update" />
                    <a class="btn btn-default" href="<?php echo $this->serverUrl()."/admin/articleCategory";?>" role="button">Back</a>
                </div>
                <div class="clearfix"></div>
            </div>
        </form>
    </div>
</section>