<div class="box box-primary">
    <div class="box-header">
        <h1 class="page-heading border-bottom">Add Admin User</h1>
    </div>
    <form data-toggle="validator" role="form" method="post" >
        <div class="box-body">
<?php   if($this->flashMessenger()->hasCurrentErrorMessages()){?>
            <div class="box box-solid alert-error">
                <div class="box-tools pull-right">
                    <button data-widget="remove" class="btn btn-box-tool text-gray"><i class="fa fa-times"></i></button>
                </div>
                <div class="box-body"><?php echo $this->flashMessenger()->setMessageOpenFormat('<strong>')->setMessageCloseString('</strong>')->render('error');?></div>
            </div>
<?php   }?>
            <div class="form-group">
                <label for="btype">Full Name</label>
                <input type="text" name="full_name" class="form-control" id="full_name" value="<?php echo ($this->post_data["full_name"] != "") ? $this->post_data["full_name"] : ""; ?>" placeholder="Full name" required>
            </div>
            
            <div class="form-group">
                <label for="btype">User Name</label>
                <input type="text" name="user_name" class="form-control" id="user_name" value="<?php echo ($this->post_data["user_name"] != "") ? $this->post_data["user_name"] : ""; ?>" placeholder="Username" required>
            </div>
            
            <div class="form-group">
                <label for="btype">Email</label>
                <input type="email" name="email" class="form-control" id="email" value="<?php echo ($this->post_data["email"] != "") ? $this->post_data["email"] : ""; ?>" placeholder="Email" required>
                <div id="email-check"></div>
            </div>
            
            <div class="form-group">
                <label for="btype">Mobile No.</label>
                <input type="text" name="mobile_no" class="form-control" id="mobile_no" value="<?php echo ($this->post_data["mobile_no"] != "") ? $this->post_data["mobile_no"] : ""; ?>" placeholder="Mobile no" >
            </div>
            
            <div class="form-group">
                <label for="btype">Password</label>
                <input type="password" name="password" class="form-control" id="password" value="" placeholder="Password" required>
            </div>
            
            <div class="form-group col-md-5 no-padding">
                <label>User Role</label>
                <select name="user_role" class="form-control ">
                    <?php
                    foreach($this->chk_roles as $val)
                    {
                        ?>
                        <option value="<?php echo $val["role_name"]; ?>" <?php echo ($this->post_data["user_role"] != "" && $this->post_data["user_role"] == $val["role_name"]) ? "selected" : ""; ?>><?php echo $val["role_name"]; ?></option>
                        <?php
                    }
                    ?>
                </select>                
            </div>
            <div class="clearfix"></div>
            
            <div class="form-group col-md-5 no-padding">
                <label>Status</label>
                <select name="user_status" class="form-control ">                    
                    <option value="active"   <?php echo ($this->post_data["user_status"] != "" && $this->post_data["user_status"] == "active") ? "selected" : ""; ?>>Active</option>
                    <option value="inactive" <?php echo ($this->post_data["user_status"] != "" && $this->post_data["user_status"] == "inactive") ? "selected" : ""; ?>>Inactive</option>                   
                
                </select>
            </div>
            <div class="clearfix"></div>            

            <div class="box-footer">
                <button type="submit" class="btn btn-primary">Add</button>
                <a class="btn btn-default" href="<?php echo $this->serverUrl()."/admin/adminuser";?>" role="button">Back</a>
            </div>
        </div>
    </form>
</div>
<script type="text/javascript">
    $(function(){
        $("#email").focusout(function(e){
            var postData=$("#email").val();
            if(postData!==""){
                var URL="/admin/emailcheck";
                $.ajax({
                    url:URL,
                    type:"POST",
                    data:{email:postData},
                    success:function(data,textStatus,jqXHR){
                        $("#email-check").show();
                        if(data.success){
                            $("#email-check").css("color","red");
                            $("#email-check").html("This Email address already exists");
                            e.preventDefault();
                        }
                        if(!data.success){
                            $("#email-check").css("color","green");
                            $("#email-check").html("Email address available");
                        }
                    }
                });
                e.preventDefault();
            }else
                $("#email-check").hide();
        });
    });
    $('input').on('ifChecked', function(event){
        alert(event.type + ' callback');
    });
</script>
