<?php use Carbon\Carbon;  ?> 
<section class="content">

    <!-- Default box -->
    <div class="box box-success">
        <div class="box-header with-border">

            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="pull-left"><h1 class="page-heading">Total Admin User : <?php echo count($this->user);?></h1></div>
                    <div class="pull-right">
                        <div class="btn-group">
                            <a class="btn btn-success"  href="<?php echo "/admin/addadmin"; ?>"><i class="fa fa-plus"></i> Add New</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="box-body">
            <?php
            if ($this->flashMessenger()->hasCurrentSuccessMessages()) {
                ?>
                <div class="box box-success box-solid alert-success">
                    <div class="box-tools pull-right">
                        <button data-widget="remove" class="btn btn-box-tool text-gray"><i class="fa fa-times"></i></button>                    
                    </div><!-- /.box-tools -->

                    <div class="box-body">
                        <?php
                        //$flashMessenger = $this->flashMessenger();
                        //if ($flashMessenger->hasMessages()) {     
                        echo $this->flashMessenger()
                                ->setMessageOpenFormat('<strong>')
                                ->setMessageCloseString('</strong>')
                                ->render('success');
                        //} 
                        ?> 
                    </div><!-- /.box-body -->
                </div><!-- /.box -->
                <?php
            }
            ?>

            <table id="example1" class="table table-bordered table-striped table-condensed">
                <thead>
                    <tr>
                        <th>SN.</th>
                        <th>Full Name</th>
                        <th>User Name</th>
                        <th>User Role</th>
                        <th>Status</th>
                        <th>Email</th>
                        <th>Last Login</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                   <?php foreach ($this->user as $key=>$row):?>
                    <tr>
                        <td><?php echo $key+1;?></td>
                        <td><?php echo $row['full_name'];?></td>                                        
                        <td><?php echo $row['user_name'];?></td>
                        <td><?php echo $row['user_role'];?></td>
                        <td><?php echo $row['user_status'];?></td>
                        <td><?php echo $row['email'];?></td>
                        <td><?php
                                if ($row['updated_at'] !=NULL)
                                {
                                    $dt = Carbon::createFromFormat('Y-m-d H:i:s',$row['updated_at']);
                                    echo $dt->toFormattedDateString();
                                }
                              ?></td>
                        <td>
                            <div class="btn-group">                                                
                                <a class="btn btn-primary btn-xs" href="<?php echo "/admin/editadmin/".$row['id'];?>" target="_blank"><i class="fa fa-edit"></i> Edit</a>
                                <!--<a class="btn btn-danger btn-xs" href="#"><i class="fa fa-remove"></i> Delete</a>-->

                                <form method="POST" action="<?php echo "/admin/deleteadmin/".$row['id'];?>" accept-charset="UTF-8" style="display:inline">
                                    <button style="border-bottom-left-radius:0;border-top-left-radius:0;" class="btn btn-xs btn-danger" type="button" data-toggle="modal" data-target="#confirmDelete" data-title="Admin user" data-message="Are you sure you want to delete this ?">
                                        <i class="glyphicon glyphicon-trash"></i> Delete
                                    </button>
                                </form>
                            </div>
                        </td>
                    </tr>
                    <?php endforeach;?>

                </tbody>
                <tfoot>
                    <tr>
                        <th>SN.</th>
                        <th>Full Name</th>
                        <th>User Name</th>
                        <th>User Role</th>
                        <th>Status</th>
                        <th>Email</th>
                        <th>Action</th>
                    </tr>
                </tfoot>
            </table>
        </div><!-- /.box-body -->

    </div><!-- /.box -->

</section><!-- /.content -->
<script type="text/javascript">
    $(function () {
        $("#example1").dataTable();
    });
</script>                