<div class="box box-primary">
    <div class="box-header">
        <h1 class="page-heading border-bottom">Edit Admin User</h1>
    </div><!-- /.box-header -->
    <!-- form start -->
    <?php if (count($this->error_messages) > 0) { ?>
        <div class="alert alert-danger">
            <?php
            foreach ($this->error_messages as $messageId => $message) {
                echo "<p>  $message </p>";
            }
            ?>   
        </div> 
    <?php } ?>
    
    <form data-toggle="validator" role="form" method="post" >
        <div class="box-body">
                        
            <div class="form-group">
                <label for="btype">Full Name</label>
                <input type="text" name="full_name" class="form-control" id="full_name" value="<?php echo ($this->post_data["full_name"] != "") ? $this->post_data["full_name"] : $this->results->full_name; ?>" placeholder="Full name" required>
            </div>
            
            <div class="form-group">
                <label for="btype">User Name</label>
                <input type="text" name="user_name" class="form-control" id="user_name" value="<?php echo ($this->post_data["user_name"] != "") ? $this->post_data["user_name"] : $this->results->user_name; ?>" placeholder="Username" required>
            </div>
            
            <div class="form-group">
                <label for="btype">Email</label>
                <input type="text" name="email" class="form-control" id="email" value="<?php echo ($this->post_data["email"] != "") ? $this->post_data["email"] : $this->results->email; ?>" placeholder="Email" required>
            </div>
            
            <div class="form-group">
                <label for="btype">Mobile No.</label>
                <input type="text" name="mobile_no" class="form-control" id="mobile_no" value="<?php echo ($this->post_data["mobile_no"] != "") ? $this->post_data["mobile_no"] : $this->results->mobile_no; ?>" placeholder="Mobile no" >
            </div>
            
            <div class="form-group">
                <label for="btype">Password</label>
                <input type="password" name="password" class="form-control" id="password" value="" placeholder="Password" >
            </div>
            
            <div class="form-group col-md-5 no-padding">
                <label>User Role</label>
                <select name="user_role" class="form-control ">
                    <?php
                    foreach($this->chk_roles as $val)
                    {
                        ?>
                        <option value="<?php echo $val["role_name"]; ?>" <?php echo (!isset($_POST["user_role"]) && ($this->results->user_role == $val["role_name"])) ? "selected" : ""; ?> <?php echo ($this->post_data["user_role"] != "" && $this->post_data["user_role"] == $val["role_name"]) ? "selected" : ""; ?>><?php echo $val["role_name"]; ?></option>
                        <?php
                    }
                    ?>
                </select>                
            </div>
            <div class="clearfix"></div>                       
            
            <div class="form-group col-md-5 no-padding">
                <label>Status</label>
                <select name="user_status" class="form-control ">                    
                    <option value="active"   <?php echo (!isset($_POST["user_status"]) && ($this->results->user_status == "admin")) ? "selected" : ""; ?>     <?php echo ($this->post_data["user_status"] != "" && $this->post_data["user_status"] == "active") ? "selected" : ""; ?>>Active</option>
                    <option value="inactive" <?php echo (!isset($_POST["user_status"]) && ($this->results->user_status == "inactive")) ? "selected" : ""; ?>  <?php echo ($this->post_data["user_status"] != "" && $this->post_data["user_status"] == "inactive") ? "selected" : ""; ?>>Inactive</option>
                
                </select>
            </div>
            <div class="clearfix"></div>  


            <div class="box-footer">
                <button type="submit" class="btn btn-primary">Update</button>
                <a class="btn btn-default" href="<?php echo $this->serverUrl()."/admin/adminuser";?>" role="button">Back</a>
            </div>    
           
        </div><!-- /.box -->
     </form>
</div>
