<div class="box box-primary">
    <div class="box-header">
        <h3 class="box-title">Employer user </h3>
    </div><!-- /.box-header -->
    <!-- form start -->
    <?php if (count($this->error_messages) > 0) { ?>
        <div class="alert alert-danger">
            <?php
            foreach ($this->error_messages as $messageId => $message) {
                echo "<p>  $message </p>";
            }
            ?>   
        </div> 
    <?php } ?>
    
    <form data-toggle="validator" role="form" method="post" >
        <div class="box-body">
            
            <div class="form-group">
                <label for="btype">Full name: </label>
                <?php echo $this->results->full_name; ?>
            </div>
            
            <div class="form-group">
                <label for="btype">Email: </label>
                <?php echo $this->results->email; ?>
            </div>
            
            <div class="form-group">
                <label for="user_status">Status: </label>
                <select name="user_status">
                    <option value="active"   <?php echo (!isset($_POST["user_status"]) && ($this->results->user_status == "admin")) ? "selected" : ""; ?>     <?php echo ($this->post_data["user_status"] != "" && $this->post_data["user_status"] == "active") ? "selected" : ""; ?>>Active</option>
                    <option value="inactive" <?php echo (!isset($_POST["user_status"]) && ($this->results->user_status == "inactive")) ? "selected" : ""; ?>  <?php echo ($this->post_data["user_status"] != "" && $this->post_data["user_status"] == "inactive") ? "selected" : ""; ?>>Inactive</option>                   
                </select>
            </div>


            <div class="box-footer">
                <button type="submit" class="btn btn-primary">Update</button>
                <a class="btn btn-default" href="<?php echo $prev_url; ?>" role="button">Back</a>
            </div>
    </form>
</div><!-- /.box -->