<div class="box box-primary">
    <div class="box-header">
        <h3 class="box-title">Admin User Info </h3>
    </div><!-- /.box-header -->
    <!-- form start -->
    
    <?php
        $flash = $this->flashMessenger();
        echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger'));
        echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info'));
        echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
        echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success')); 
    ?>
    
    <?php if (count($this->error_messages) > 0) { ?>
        <div class="alert alert-danger">
            <?php           
            foreach ($this->error_messages as $messageId => $message) {
                echo "<p>  $message </p>";
            }
            ?>   
        </div> 
    <?php } ?>
    
    <form data-toggle="validator" role="form" method="post" >
        <div class="box-body">                        
            <div class="form-group">                
                <label for="btype">Username</label>
                <input type="text" name="user_name" class="form-control" id="user_name" value="<?php echo ($this->post_data["user_name"] != "") ? $this->post_data["user_name"] : $this->login_user[0]["user_name"]; ?>" placeholder="Username" />
            </div>                    
            
            <div class="form-group">
                <label for="btype">Old Password</label>
                <input type="password" name="old_password" class="form-control" id="old_password" value="" placeholder="Password" />
            </div>
            
            <div class="form-group">
                <label for="btype">New Password</label>
                <input type="password" name="new_password" class="form-control" id="new_password" value="" placeholder="Password" />
            </div>
            
            <div class="form-group">
                <label for="btype">Confirm Password</label>
                <input type="password" name="con_password" class="form-control" id="con_password" value="" placeholder="Password" />
            </div>
            
            <div class="box-footer">
                <button type="submit" class="btn btn-primary">Update</button>
            </div>
        </div>
    </form>
</div><!-- /.box -->
<script>
    $('input').on('ifChecked', function(event){
        alert(event.type + ' callback');
});
</script>
