<section class="content">

    <!-- Default box -->
    <div class="box box-default">
        <div class="box-header with-border">

            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <h1 class="page-heading">Top Employer</h1>
                    <div class="pull-right">
                        
                    </div>
                </div>
            </div>
        </div>
        <div class="box-body">
            <div class="box box-success box-solid alert-success" style="display: none;">
                <div class="box-tools pull-right">
                    <button data-widget="remove" class="btn btn-box-tool text-gray"><i class="fa fa-times"></i></button>                    
                </div><!-- /.box-tools -->

                <div class="box-body">
                    <strong> Success Message </strong>
                </div><!-- /.box-body -->
            </div><!-- /.box -->


            <div id="user_data_tables">
                
            </div>
            <table id="users-table" class="table table-bordered table-striped table-condensed">
                <thead>
                    <tr>
                        <th>Full name</th>
                        <th>Email</th>
                        <th>User role</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Full name</th>
                        <th>Email</th>
                        <th>User role</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
	           </tfoot>
            </table>
        </div><!-- /.box-body -->

    </div><!-- /.box -->

</section><!-- /.content -->

<script type="text/javascript">
    $(document).ready(function() {
        
        $('#users-table').DataTable({
            processing: true,
            serverSide: true,
            ajax: {
                url: '/chkapi/api/topemployer',
                type: 'post'
            },
            columns: [
                {data: 'full_name', name: 'full_name'},
                {data: 'email', name: 'email'},
                {data: 'user_role', name: 'user_role'},
                {data: 'user_status', name: 'user_status'},                
                {data: 'action', name: 'action', orderable: false, searchable: false}
            ],
           initComplete: function () {
            this.api().columns().every(function () {
                var column = this;
                var input = document.createElement("input");
                $(input).appendTo($(column.footer()).empty())
                .on('change', function () {
                    var val = $.fn.dataTable.util.escapeRegex($(this).val());

                    column.search(val ? val : '', true, false).draw();
                });
            });
        }
        

        });
        
        
        
        /*
        $('#user_data_tables').DataTable({
            processing: true,
            serverSide: true,
            ajax: '/chkapi/api/users'
        });
        */
        
        
        /*
        $.ajax({
            url: '/chkapi/api/sumon',
            data: {
               format: 'json'
            },
            error: function() {
               $('#info').html('<p>An error has occurred</p>');
            },
            dataType: 'jsonp',
            success: function(data) {
              alert(data);
            },
            type: 'POST'
         });
         
         */
       
    });
</script>