    <div>
    <?php
        $flash = $this->flashMessenger();
        echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger'));
        echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info'));
        echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
        echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
    ?>
    </div> 

<section class="content">    
    <div class="govt_job_ad_form_container box box-default admin_form_bg"> 
        <form role="form" data-toggle="validator" class="form-horizontal register_employer_form" method="post" enctype="multipart/form-data">
            <h1>Add New Government Job</h1>          
            
            <?php 
            if (count($this->error_messages) > 0) { ?>
            <div class="alert alert-danger">
                <?php                                 
                foreach ($this->error_messages as $messageId => $message) {                        
                        echo "<p>  $message </p>";           
                }
                ?>   
            </div> 
            <?php } ?>

            <?php if (count($this->success_messages) > 0) { ?>
            <div class="alert alert-success">
                <?php
                foreach ($this->success_messages as $messageId => $message) {
                    echo "<p>  $message </p>";
                }
                ?>   
            </div>
            <?php } ?>
            
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Company name:</label>
                <div class="col-sm-5 col-md-5">                    
                    <input type="text" class="form-control" id="job_company_name" name="job_company_name" placeholder="Company Name" value="<?php echo ($this->post_data["job_company_name"] != "") ? $this->post_data["job_company_name"] : $this->results->job_company_name; ?>" required />
                </div>
                <div class="clearfix"></div>
            </div>
            
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Office:</label>
                <div class="col-sm-5 col-md-5">                    
                    <input type="text" class="form-control" id="inputEmail3" name="office_name" placeholder="office Name" value="<?php echo ($this->post_data["office_name"] != "") ? $this->post_data["office_name"] : $this->results->job_location; ?>" required />
                </div>
                <div class="clearfix"></div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Position:</label>
                <div class="col-sm-5 col-md-5">
                    <input type="text" class="form-control" id="inputPassword3" name="position" placeholder="position" value="<?php echo ($this->post_data["position"] != "") ? $this->post_data["position"] : $this->results->job_level; ?>" required />
                </div>
                <div class="clearfix"></div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Education:</label>
                <div class="col-sm-10 col-md-10">
                    <textarea id="editor2" name="job_education" rows="10" cols="80"><?php echo ($this->post_data["job_education"] != "") ? $this->post_data["job_education"] : $this->results->job_education; ?></textarea>
                </div>
                <div class="clearfix"></div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Job Industry:</label>
                <div class="col-sm-10 col-md-10">
                    <div class="check_box_scroller_container">
                        <?php
                        //$job_industry_id = $this->results->job_industry_id;
                        //$job_industry    = explode(",", $job_industry_id);
                        
                        foreach($this->job_industry as $industry)
                        {
                           ?>
                            <div class="checkbox">
                                <label>                          
                                    <input type="checkbox" id="checkboxSuccess" name="job_industry_id[]" value="<?php echo $industry["id"];?>" <?php echo (! isset($this->post_data["job_industry_id"]) && in_array($industry["id"], $selected_industry_id)) ? 'checked="checked"' : '' ?> <?php echo (isset($this->post_data["job_industry_id"]) && in_array($industry["id"], $this->post_data["job_industry_id"])) ? 'checked="checked"' : '' ?> />
                                    <?php echo $industry["name"]; ?>
                                </label>
                             </div>
                           <?php
                        }    
                        ?>
                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>  

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Job Category:</label>
                <div class="col-sm-10 col-md-10">
                    <div class="check_box_scroller_container">
                        <?php
                        //$job_category_id = $this->results->job_category_id;
                        //$job_category    = explode(",", $job_category_id);
                        
                        foreach($this->job_category as $category)
                        {                           
                            ?>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" id="checkboxSuccess" name="job_category_id[]" value="<?php echo $category["id"]; ?>" <?php echo (! isset($this->post_data["job_category_id"]) && in_array($category["id"], $selected_categories_id)) ? 'checked="checked"' : '' ?>  <?php echo (isset($this->post_data["job_category_id"]) && in_array($category["id"], $this->post_data["job_category_id"])) ? 'checked="checked"' : '' ?> />
                                    <?php echo $category["name"]; ?>
                                </label>
                                </label>
                             </div>
                           <?php
                        }    
                        ?>                   

                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Published In:</label>
                <div class="col-sm-5 col-md-5">
                    <select class="form-control" name="published">
                        <option value="The Daily Prothom Alo" <?php echo (!isset($this->post_data["published"]) && ($this->results->published == 'The Daily Prothom Alo')) ? 'selected=""' : '' ?>  <?php echo (isset($this->post_data["published"]) && ($this->post_data["published"] == "The Daily Prothom Alo")) ? 'selected=""' : '' ?>>The Daily Prothom Alo</option>
                        <option value="The Daily Star" <?php echo (!isset($this->post_data["published"]) && ($this->results->published == 'The Daily Star')) ? 'selected=""' : '' ?>  <?php echo (isset($this->post_data["published"]) && ($this->post_data["published"] == "The Daily Star")) ? 'selected=""' : '' ?>>The Daily Star</option>
                        <option value="The Financial Express" <?php echo (!isset($this->post_data["published"]) && ($this->results->published == 'The Financial Express')) ? 'selected=""' : '' ?>  <?php echo (isset($this->post_data["published"]) && ($this->post_data["published"] == "The Financial Express")) ? 'selected=""' : '' ?>>The Financial Express</option>
                        <option value="The Daily Naya Diganta" <?php echo (!isset($this->post_data["published"]) && ($this->results->published == 'The Daily Naya Diganta')) ? 'selected=""' : '' ?>  <?php echo (isset($this->post_data["published"]) && ($this->post_data["published"] == "The Daily Naya Diganta")) ? 'selected=""' : '' ?>>The Daily Naya Diganta</option>
                        <option value="The Independent" <?php echo (!isset($this->post_data["published"]) && ($this->results->published == 'The Independent')) ? 'selected=""' : '' ?>  <?php echo (isset($this->post_data["published"]) && ($this->post_data["published"] == "The Independent")) ? 'selected=""' : '' ?>>The Independent</option>
                        <option value="The Daily Jugantor" <?php echo (!isset($this->post_data["published"]) && ($this->results->published == 'The Daily Jugantor')) ? 'selected=""' : '' ?>  <?php echo (isset($this->post_data["published"]) && ($this->post_data["published"] == "The Daily Jugantor")) ? 'selected=""' : '' ?>>The Daily Jugantor</option>
                        <option value="The Daily Ittefaq" <?php echo (!isset($this->post_data["published"]) && ($this->results->published == 'The Daily Ittefaq')) ? 'selected=""' : '' ?>  <?php echo (isset($this->post_data["published"]) && ($this->post_data["published"] == "The Daily Ittefaq")) ? 'selected=""' : '' ?>>The Daily Ittefaq</option>
                        <option value="Samakal" <?php echo (!isset($this->post_data["published"]) && ($this->results->published == 'Samakal')) ? 'selected=""' : '' ?>  <?php echo (isset($this->post_data["published"]) && ($this->post_data["published"] == "Samakal")) ? 'selected=""' : '' ?>>Samakal</option>
                        <option value="Others" <?php echo (!isset($this->post_data["published"]) && ($this->results->published == 'Others')) ? 'selected=""' : '' ?>  <?php echo (isset($this->post_data["published"]) && ($this->post_data["published"] == "Others")) ? 'selected=""' : '' ?>>Others</option>
                    </select>
                </div>
                <div class="clearfix"></div>
            </div>


            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Published Date:</label>
                <div class="col-sm-5 col-md-5">
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-calendar"></i>
                        </div>
                        <?php
                        if(($this->results->posting_date !="") && ($this->results->posting_date !="0000-00-00"))
                        {
                            $posting_date = $this->results->posting_date;
                        }
                        else{
                            $posting_date = date("Y-m-d");
                        }
                        ?>
                        
                        <input type="text" name="published_date" value="<?php echo ($this->post_data["published_date"] != "") ? $this->post_data["published_date"] : $posting_date; ?>" class="form-control" data-inputmask="'alias': 'yyyy-mm-dd'" data-mask required />
                    </div>                
                </div>

                <div class="clearfix"></div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Deadline:</label>
                <div class="col-sm-5 col-md-5">
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-calendar"></i>
                        </div>
                        <?php
                        if(($this->results->job_deadline !="") && ($this->results->job_deadline !="0000-00-00"))
                        {
                            $job_deadline = $this->results->job_deadline;
                        }
                        else{
                            $job_deadline = "";
                        }
                        ?>
                        <input type="text" name="job_deadline" value="<?php echo ($this->post_data["job_deadline"] != "") ? $this->post_data["job_deadline"] : $job_deadline; ?>" class="form-control" data-inputmask="'alias': 'yyyy-mm-dd'" data-mask required/>
                    </div>                
                </div>

                <div class="clearfix"></div>
            </div>            
            
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Picture:</label>
                <div class="col-sm-5 col-md-5">
                    <input type="file" id="image-file" name="image-file" required />
                </div>
                <?php
                if($this->results->job_image !="")
                {    
                    ?>
                    <div class="col-sm-10 col-md-10">                   
                        <img width="150" src="<?php echo "/upload/job/".$this->results->job_image; ?>" alt="spotlight logo" title="spotlight loho" />
                    </div>
                    <?php
                }
                ?>
                <div class="clearfix"></div>
            </div>
            
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Is Spotlight. Job? </label>
                <div class="col-sm-5 col-md-5">                
                    <label>                    
                        <input type="radio" name="spot_light_used" id="splUsed" onclick="spotLightJob(1);" value="1"  class="minimal" <?php echo ($this->post_data["spot_light_used"] == "1") ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["spot_light_used"]) && ($this->results->spot_light_used == "1")) ? 'checked=""' : ''; ?> />Yes
                    </label>
                    <label>                    
                        <input type="radio" name="spot_light_used" id="splNUsed" onclick="spotLightJob(0);" value="0" class="minimal"  <?php echo ($this->post_data["spot_light_used"] == "0") ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["spot_light_used"]) && ($this->results->spot_light_used == "0")) ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["spot_light_used"]) && ($this->results->spot_light_used == "")) ? 'checked=""' : ''; ?>  />No
                    </label>

                </div>
                <div class="clearfix"></div>
            </div>
            
            <div class="spot_light_used_box">  
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Spotlight Job Content</label>
                    <div class="col-sm-10 col-md-10">
                        <textarea id="editor1" name="spotlight_job_content" rows="10" cols="80"><?php echo ($this->post_data["spotlight_job_content"] != "") ? $this->post_data["spotlight_job_content"] : $this->results->spotlight_job_content; ?></textarea>
                    </div>
                    <div class="clearfix"></div>
                </div>

                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Spotlight Logo</label>
                    <div class="col-sm-10 col-md-10">

                        <input type="file" name="spotlight_job_logo" id="spotlight_job_logo">
                    </div>
                    <?php
                    if($this->results->spotlight_job_logo !="")
                    {    
                        ?>
                        <div class="col-sm-10 col-md-10">                   
                            <img width="150" src="<?php echo "/upload/job/".$this->results->spotlight_job_logo; ?>" alt="spotlight logo" title="spotlight logo" />
                        </div>
                    <?php
                    }
                    ?>
                    <div class="clearfix"></div>
                </div>

                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Spotlight Order</label>
                    <div class="col-sm-3 col-md-3">                    
                        <select class="form-control" name="spotlight_job_order">
                            <option value="">Select order</option>
                            <?php
                            for ($order = 1; $order <= 10; $order ++) {
                                ?>
                                <option value="<?php echo $order; ?>" <?php echo (!isset($this->post_data["spotlight_job_order"]) && ($this->results->spotlight_job_order == $order)) ? 'selected=""' : '' ?>  <?php echo (isset($this->post_data["spotlight_job_order"]) && ($this->post_data["spotlight_job_order"] == $order)) ? 'selected=""' : '' ?>><?php echo $order; ?></option>
                                <?php
                            }
                            ?>
                        </select>
                    </div>
                    <div class="clearfix"></div>
                </div>

                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Spotlight Group</label>
                    <div class="col-sm-3 col-md-3">                    
                        <select class="form-control" name="spotlight_job_gorup">
                            <option value="">Select group</option>
                            <?php
                            for ($group = 1; $group <= 10; $group ++) {
                                ?>
                                <option value="<?php echo $group; ?>" <?php echo (!isset($this->post_data["spotlight_job_gorup"]) && ($this->results->spotlight_job_gorup == $group)) ? 'selected=""' : '' ?> <?php echo (isset($this->post_data["spotlight_job_gorup"]) && ($this->post_data["spotlight_job_gorup"] == $group)) ? 'selected=""' : '' ?>><?php echo $group; ?></option>
                                <?php
                            }
                            ?>
                        </select> 
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Is Active?</label>
                <div class="col-sm-5 col-md-5">
                    <label>
                        <input type="radio" name="status" value="1" class="minimal" <?php echo ($this->post_data["status"] == "1") ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["status"]) && ($this->results->status == "1")) ? 'checked=""' : ''; ?> checked/>Yes
                    </label>
                    <label>
                        <input type="radio" name="status" value="0" class="minimal" <?php echo ($this->post_data["status"] == "0") ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["status"]) && ($this->results->status == "0")) ? 'checked=""' : ''; ?> />No
                    </label>

                </div>
                <div class="clearfix"></div>
            </div>     


            <div class="form-group">
                <div class=" col-xs-12 col-sm-6 col-md-6 col-sm-offset-2 col-md-offset-2 btn_submit">
                    <button type="submit" class="btn btn-primary pull-left">Submit</button>&nbsp;
                    <a class="btn btn-default" href="<?php echo $this->serverUrl()."/admin/job/govtjob"; ?>" role="button">Back</a>
                </div>                                            
            </div>            
            <div class="clearfix"></div>
            
        </form>
    </div>    
</section>

<script type="text/javascript">
    
    function spotLightJob(val)
    {        
        if(val == 1)
        {    
             $(".spot_light_used_box").show();
        }     
        else
        {    
             $(".spot_light_used_box").hide();
        }    
    }
      
    
    $(function(){
        
        $("[data-mask]").inputmask();
        
        CKEDITOR.replace('editor2');
        
        //for spotlight job
        if(document.getElementById('splUsed').checked)
        {
            spotLightJob(1);          
        }   
        
        if(document.getElementById('splNUsed').checked)
        {
            spotLightJob(0);
        }
        
        CKEDITOR.replace('editor1', {
            filebrowserBrowseUrl: '/ckfinder/ckfinder.html',
            filebrowserImageBrowseUrl: '/ckfinder/ckfinder.html',
            filebrowserFlashBrowseUrl: '/ckfinder/ckfinder.html',
            filebrowserUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload',
            filebrowserImageUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload',
            filebrowserFlashUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload'
        });
        
      });

</script>