<section class="content">
    <div class="govt_job_ad_form_container box box-default admin_form_bg">
        <form role="form" data-toggle="validator" class="form-horizontal register_employer_form" method="post" enctype="multipart/form-data">
            <?php
            if ($header) {
                echo "<h1>" . $header . "</h1>";
            } else {
                ?>
                <h1>Add Newspaper Job</h1>
            <?php } ?>


            <?php if (count($this->error_messages) > 0) { ?>
                <div class="alert alert-danger">
                    <?php
                    foreach ($this->error_messages as $messageId => $message) {
                        echo "<p>  $message </p>";
                    }
                    ?>   
                </div> 
            <?php } ?>

            <?php if (count($this->success_messages) > 0) { ?>
                <div class="alert alert-success">
                    <?php
                    foreach ($this->success_messages as $messageId => $message) {
                        echo "<p>  $message </p>";
                    }
                    ?>   
                </div>
            <?php } ?>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Company Name:</label>
                <div class="col-sm-5 col-md-5">
                    <input type="text" class="form-control" id="job_company_name" name="job_company_name" placeholder="Company Name" value="<?php echo ($this->post_data["job_company_name"] != "") ? $this->post_data["job_company_name"] : $this->results->job_company_name; ?>" required />
                </div>
                <div class="clearfix"></div>
            </div>        

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label"> Company Information:</label>
                <div class="col-sm-10 col-md-10">
                    <textarea id="company_description" name="company_description" rows="8" cols="80"><?php echo ($this->post_data["company_description"] != "") ? $this->post_data["company_description"] : $this->results->company_description; ?></textarea>
                </div>
                <div class="clearfix"></div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label"> Job Title/ Position:</label>
                <div class="col-sm-5 col-md-5">
                    <input type="text" class="form-control" id="job_title" name="job_title" placeholder="position" required value="<?php echo ($this->post_data["job_title"] != "") ? $this->post_data["job_title"] : $this->results->job_title; ?>">
                </div>
                <div class="clearfix"></div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label"> Industrial Category: </label>
                <div class="col-sm-10 col-md-10">
                    <div class="check_box_scroller_container">
                        <?php
                        foreach ($this->job_industry as $industry) {
                            ?>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" id="checkboxSuccess" name="job_industry_id[]" value="<?php echo $industry["id"]; ?>" <?php echo (!isset($this->post_data["job_industry_id"]) && in_array($industry["id"], $selected_industry_id)) ? 'checked="checked"' : '' ?> <?php echo (isset($this->post_data["job_industry_id"]) && in_array($industry["id"], $this->post_data["job_industry_id"])) ? 'checked="checked"' : '' ?> />
    <?php echo $industry["name"]; ?>
                                </label>
                            </div>
    <?php
}
?>
                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>  

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label"> Functional Category: </label>
                <div class="col-sm-10 col-md-10">
                    <div class="check_box_scroller_container">
<?php
foreach ($this->job_category as $category) {
    ?>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" id="checkboxSuccess" name="job_category_id[]" value="<?php echo $category["id"]; ?>" <?php echo (!isset($this->post_data["job_category_id"]) && in_array($category["id"], $selected_categories_id)) ? 'checked="checked"' : '' ?>  <?php echo (isset($this->post_data["job_category_id"]) && in_array($category["id"], $this->post_data["job_category_id"])) ? 'checked="checked"' : '' ?> />
    <?php echo $category["name"]; ?>
                                </label>
                            </div>
                                    <?php
                                }
                                ?>                  

                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>

<?php
//$selected_job_level = explode(",", $this->results->job_level);        
?>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Job Level: </label>
                <div class="col-sm-10 col-md-10">
                    <div class="check_box_scroller_container">
                        <div class="checkbox">
                            <label>
                                <input type="radio" name="job_level" id="job_level" value="Entry" <?php echo (!isset($this->post_data["job_level"]) && ($this->results->job_level == "Entry")) ? 'checked="checked"' : '' ?> <?php echo (isset($this->post_data["job_level"]) && ($this->post_data["job_level"] == "Entry")) ? 'checked="checked"' : '' ?> />
                                Entry
                            </label>
                        </div>

                        <div class="checkbox">
                            <label>
                                <input type="radio" name="job_level"  id="job_level" value="Mid" <?php echo (!isset($this->post_data["job_level"]) && ($this->results->job_level == "Mid")) ? 'checked="checked"' : '' ?>  <?php echo (isset($this->post_data["job_level"]) && ($this->post_data["job_level"] == "Mid")) ? 'checked="checked"' : '' ?> />
                                Mid
                            </label>
                        </div> 

                        <div class="checkbox">
                            <label>
                                <input type="radio" name="job_level"  id="job_level" value="Top" <?php echo (!isset($this->post_data["job_level"]) && ($this->results->job_level == "Top")) ? 'checked="checked"' : '' ?>  <?php echo (isset($this->post_data["job_level"]) && ($this->post_data["job_level"] == "Top")) ? 'checked="checked"' : '' ?> />
                                Top
                            </label>
                        </div>

                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>

<?php
//$selected_job_type = explode(",", $this->results->job_type);        
?>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Job Type: </label>
                <div class="col-sm-10 col-md-10">
                    <div class="check_box_scroller_container">
                        <div class="checkbox">
                            <label>
                                <input type="radio" id="job_type" name="job_type" value="Full Time" <?php echo (!isset($this->post_data["job_type"]) && ($this->results->job_type == "Full Time")) ? 'checked="checked"' : '' ?>  <?php echo (isset($this->post_data["job_type"]) && ($this->post_data["job_type"] == "Full Time")) ? 'checked="checked"' : '' ?> />
                                Full Time
                            </label>
                        </div>

                        <div class="checkbox">
                            <label>
                                <input type="radio" id="job_type" name="job_type"  value="Part Time" <?php echo (!isset($this->post_data["job_type"]) && ($this->results->job_type == "Part Time")) ? 'checked="checked"' : '' ?> <?php echo (isset($this->post_data["job_type"]) && ($this->post_data["job_type"] == "Part Time")) ? 'checked="checked"' : '' ?> />
                                Part Time
                            </label>
                        </div> 

                        <div class="checkbox">
                            <label>
                                <input type="radio" id="job_type" name="job_type"  value="Contractual" <?php echo (!isset($this->post_data["job_type"]) && ($this->results->job_type == "Contractual")) ? 'checked="checked"' : '' ?> <?php echo (isset($this->post_data["job_type"]) && ($this->post_data["job_type"] == "Contractual")) ? 'checked="checked"' : '' ?> />
                                Contractual
                            </label>
                        </div> 
                        <div class="checkbox">
                            <label>
                                <input type="radio" id="job_type" name="job_type" value="Intern" <?php echo (!isset($this->post_data["job_type"]) && ($this->results->job_type == "Intern")) ? 'checked="checked"' : '' ?> <?php echo (isset($this->post_data["job_type"]) && ($this->post_data["job_type"] == "Intern")) ? 'checked="checked"' : '' ?> />
                                Intern
                            </label>
                        </div>

                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">  Job Location: </label>
                <div class="col-sm-5 col-md-5">
                    <input type="text" class="form-control" id="job_location" name="job_location" placeholder="Enter job location" required value="<?php echo ($this->post_data["job_location"] != "") ? $this->post_data["job_location"] : $this->results->job_location; ?>">
                </div>
                <div class="clearfix"></div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">   No of Vacancies: </label>
                <div class="col-sm-5 col-md-5">
                    <input type="text" class="form-control" id="no_of_vacencies" name="no_of_vacencies" placeholder="Enter Number of vacancies" required value="<?php echo ($this->post_data["no_of_vacencies"] != "") ? $this->post_data["no_of_vacencies"] : $this->results->no_of_vacencies; ?>">
                </div>
                <div class="clearfix"></div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label"> Job Requirement:</label>
                <div class="col-sm-10 col-md-10">
                    <textarea id="job_requirement" name="job_requirement" rows="8" cols="80"><?php echo ($this->post_data["job_requirement"] != "") ? $this->post_data["job_requirement"] : $this->results->job_requirement; ?></textarea>
                </div>
                <div class="clearfix"></div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label"> Job Description: </label>
                <div class="col-sm-10 col-md-10">
                    <textarea id="job_description" name="job_description" rows="8" cols="80"><?php echo ($this->post_data["job_description"] != "") ? $this->post_data["job_description"] : $this->results->job_description; ?></textarea>
                </div>
                <div class="clearfix"></div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label"> Educational Qualification: </label>
                <div class="col-sm-10 col-md-10">
                    <textarea id="job_education" name="job_education" rows="8" cols="80"><?php echo ($this->post_data["job_education"] != "") ? $this->post_data["job_education"] : $this->results->job_education; ?></textarea>
                </div>
                <div class="clearfix"></div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label"> Job Experience: </label>
                <div class="col-sm-10 col-md-10">
                    <textarea id="job_experienced" name="job_experienced" rows="8" cols="80"><?php echo ($this->post_data["job_experienced"] != "") ? $this->post_data["job_experienced"] : $this->results->job_experienced; ?></textarea>
                </div>
                <div class="clearfix"></div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Age Limit: </label>            
                <div class="age_limit_box col-sm-2 col-md-2"> 
                    <select name="age_limit_to" class="form-control">
                        <option value=''>To</option>
<?php
for ($i = 18; $i <= 80; $i++) {
    ?>
                            <option value="<?php echo $i; ?>" <?php echo (!isset($this->post_data["age_limit_to"]) && ($this->results->age_limit_to == $i)) ? 'selected=""' : '' ?>  <?php echo (isset($this->post_data["age_limit_to"]) && ($this->post_data["age_limit_to"] == $i)) ? 'selected=""' : '' ?>><?php echo $i; ?></option>
                            <?php
                        }
                        ?>
                    </select>
                </div>

                <div class="age_limit_box col-sm-2 col-md-2"> 
                    <select name="age_limit_from" class="form-control">
                        <option value=''>From</option>
<?php
for ($i = 18; $i <= 80; $i++) {
    ?>
                            <option value="<?php echo $i; ?>" <?php echo (!isset($this->post_data["age_limit_from"]) && ($this->results->age_limit_from == $i)) ? 'selected=""' : '' ?>  <?php echo (isset($this->post_data["age_limit_from"]) && ($this->post_data["age_limit_from"] == $i)) ? 'selected=""' : '' ?>><?php echo $i; ?></option>
                            <?php
                        }
                        ?>
                    </select>
                </div>

                <div class="age_limit_other_box col-sm-2 col-md-2" style="display:none;"> 
                    <input type="text" class="form-control" id="age_limit_other" name="age_limit_other" placeholder="Type Age" value="<?php echo ($this->post_data["age_limit_other"] != "") ? $this->post_data["age_limit_other"] : $this->results->age_limit_other; ?>">
                </div>

                <div class="col-sm2 col-md-2">
                    <input type="checkbox" id="type_age" name="type_age" value="type_age" <?php echo ($this->post_data["type_age"] == "type_age") ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["type_age"]) && ($this->results->age_limit_other != "")) ? 'checked=""' : ''; ?> /> Type Age
                </div>
                <div class="clearfix"></div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">   Salary: </label>
                <div class="col-sm-5 col-md-5">
                    <input type="text" class="form-control" id="salary_range" name="salary_range" placeholder="Salary range" required value="<?php echo ($this->post_data["salary_range"] != "") ? $this->post_data["salary_range"] : $this->results->salary_range; ?>">
                </div>
                <div class="clearfix"></div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">   Direct URL: </label>
                <div class="col-sm-5 col-md-5">
                    <input type="text" class="form-control" id="direct_url" name="direct_url" placeholder="www.url.com" value="<?php echo ($this->post_data["direct_url"] != "") ? $this->post_data["direct_url"] : $this->results->direct_url; ?>">
                </div>
                <div class="clearfix"></div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">  Instruction To Apply: </label>
                <div class="col-sm-10 col-md-10">
                    <textarea id="job_apply_instruction" name="job_apply_instruction" rows="8" cols="80"><?php echo ($this->post_data["job_apply_instruction"] != "") ? $this->post_data["job_apply_instruction"] : $this->results->job_apply_instruction; ?></textarea>
                </div>
                <div class="clearfix"></div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">  Company Address: </label>
                <div class="col-sm-10 col-md-10">
                    <textarea id="compnay_address" name="compnay_address" rows="8" cols="80"><?php echo ($this->post_data["compnay_address"] != "") ? $this->post_data["compnay_address"] : $this->results->compnay_address; ?></textarea>
                </div>
                <div class="clearfix"></div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label"> Other Information: </label>
                <div class="col-sm-10 col-md-10">
                    <textarea id="other_information" name="other_information" rows="8" cols="80"><?php echo ($this->post_data["other_information"] != "") ? $this->post_data["other_information"] : $this->results->other_information; ?></textarea>
                </div>
                <div class="clearfix"></div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Published In:</label>
                <div class="col-sm-5 col-md-5">
                    <select class="form-control" name="published">
                        <option value="The Daily Prothom Alo" <?php echo (!isset($this->post_data["published"]) && ($this->results->published == 'The Daily Prothom Alo')) ? 'selected=""' : '' ?>  <?php echo (isset($this->post_data["published"]) && ($this->post_data["published"] == "The Daily Prothom Alo")) ? 'selected=""' : '' ?>>The Daily Prothom Alo</option>
                        <option value="The Daily Star" <?php echo (!isset($this->post_data["published"]) && ($this->results->published == 'The Daily Star')) ? 'selected=""' : '' ?>  <?php echo (isset($this->post_data["published"]) && ($this->post_data["published"] == "The Daily Star")) ? 'selected=""' : '' ?>>The Daily Star</option>
                        <option value="The Financial Express" <?php echo (!isset($this->post_data["published"]) && ($this->results->published == 'The Financial Express')) ? 'selected=""' : '' ?>  <?php echo (isset($this->post_data["published"]) && ($this->post_data["published"] == "The Financial Express")) ? 'selected=""' : '' ?>>The Financial Express</option>
                        <option value="The Daily Naya Diganta" <?php echo (!isset($this->post_data["published"]) && ($this->results->published == 'The Daily Naya Diganta')) ? 'selected=""' : '' ?>  <?php echo (isset($this->post_data["published"]) && ($this->post_data["published"] == "The Daily Naya Diganta")) ? 'selected=""' : '' ?>>The Daily Naya Diganta</option>
                        <option value="The Independent" <?php echo (!isset($this->post_data["published"]) && ($this->results->published == 'The Independent')) ? 'selected=""' : '' ?>  <?php echo (isset($this->post_data["published"]) && ($this->post_data["published"] == "The Independent")) ? 'selected=""' : '' ?>>The Independent</option>
                        <option value="The Daily Jugantor" <?php echo (!isset($this->post_data["published"]) && ($this->results->published == 'The Daily Jugantor')) ? 'selected=""' : '' ?>  <?php echo (isset($this->post_data["published"]) && ($this->post_data["published"] == "The Daily Jugantor")) ? 'selected=""' : '' ?>>The Daily Jugantor</option>
                        <option value="The Daily Ittefaq" <?php echo (!isset($this->post_data["published"]) && ($this->results->published == 'The Daily Ittefaq')) ? 'selected=""' : '' ?>  <?php echo (isset($this->post_data["published"]) && ($this->post_data["published"] == "The Daily Ittefaq")) ? 'selected=""' : '' ?>>The Daily Ittefaq</option>
                        <option value="Samakal" <?php echo (!isset($this->post_data["published"]) && ($this->results->published == 'Samakal')) ? 'selected=""' : '' ?>  <?php echo (isset($this->post_data["published"]) && ($this->post_data["published"] == "Samakal")) ? 'selected=""' : '' ?>>Samakal</option>
                        <option value="Others" <?php echo (!isset($this->post_data["published"]) && ($this->results->published == 'Others')) ? 'selected=""' : '' ?>  <?php echo (isset($this->post_data["published"]) && ($this->post_data["published"] == "Others")) ? 'selected=""' : '' ?>>Others</option>
                    </select>
                </div>
                <div class="clearfix"></div>
            </div>


            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label"> Posting Date:</label>
                <div class="col-sm-5 col-md-5">
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-calendar"></i>
                        </div>
<?php
if (($this->results->posting_date != "") && ($this->results->posting_date != "0000-00-00")) {
    $posting_date = $this->results->posting_date;
} elseif ($this->post_data["posting_date"] != "") {
    $posting_date = $this->post_data["posting_date"];
} else {
    $posting_date = date("Y-m-d");
}
?>
                        <input type="text" name="posting_date" value="<?php echo $posting_date; ?>" class="form-control" data-inputmask="'alias': 'yyyy-mm-dd'" data-mask/>
                    </div>                
                </div>

                <div class="clearfix"></div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Deadline: </label>
                <div class="col-sm-5 col-md-5">
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-calendar"></i>
                        </div>
<?php
if (($this->results->job_deadline != "") && ($this->results->job_deadline != "0000-00-00")) {
    $job_deadline = $this->results->job_deadline;
} elseif ($this->post_data["job_deadline"] != "") {
    $job_deadline = $this->post_data["job_deadline"];
}
?>
                        <input type="text" name="job_deadline" value="<?php echo $job_deadline; ?>" class="form-control" data-inputmask="'alias': 'yyyy-mm-dd'" data-mask/>
                    </div>                
                </div>

                <div class="clearfix"></div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Job Image : </label>
                <div class="col-sm-5 col-md-5">
                    <input type="file" id="image-file" name="image-file">                
                </div>

<?php
if ($this->results->job_image != "") {
    ?>
                    <div class="col-sm-10 col-md-10">                   
                        <img width="150" src="<?php echo $this->basePath("upload/job/" . $this->results->job_image); ?>" alt="spotlight logo" title="spotlight loho" />
                    </div>
    <?php
}
?>
                <div class="clearfix"></div>
            </div>

            <!--
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Govt. Job? </label>
                <div class="col-sm-5 col-md-5">                
                <?php
                $job_circular_type = $this->results->job_circular_type;
                $selected_job_circular_type = explode(",", $job_circular_type);
                ?>
                    <label>
                        <input type="radio" name="govtJobStatus" value="1" class="minimal" <?php echo ($this->post_data["govtJobStatus"] == "1") ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["govtJobStatus"]) && in_array(1, $selected_job_circular_type)) ? 'checked=""' : ''; ?>  />Yes
                    </label>
                    <label>
                        <input type="radio" name="govtJobStatus" value="0" class="minimal" <?php echo ($this->post_data["govtJobStatus"] == "0") ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["govtJobStatus"]) && in_array(0, $selected_job_circular_type)) ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["govtJobStatus"]) && ($this->results->job_circular_type == "")) ? 'checked=""' : ''; ?> />No
                    </label>
                </div>
                <div class="clearfix"></div>
            </div>
            -->    

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Is Spotlight. Job? </label>
                <div class="col-sm-5 col-md-5">                
                    <label>                    
                        <input type="radio" name="spot_light_used" id="splUsed" onclick="spotLightJob(1);" value="1"  class="minimal" <?php echo ($this->post_data["spot_light_used"] == "1") ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["spot_light_used"]) && ($this->results->spot_light_used == "1")) ? 'checked=""' : ''; ?> />Yes
                    </label>
                    <label>                    
                        <input type="radio" name="spot_light_used" id="splNUsed" onclick="spotLightJob(0);" value="0" class="minimal"  <?php echo ($this->post_data["spot_light_used"] == "0") ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["spot_light_used"]) && ($this->results->spot_light_used == "0")) ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["spot_light_used"]) && ($this->results->spot_light_used == "")) ? 'checked=""' : ''; ?>  />No
                    </label>

                </div>
                <div class="clearfix"></div>
            </div>

            <div class="spot_light_used_box">  
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Spotlight Job Content:</label>
                    <div class="col-sm-10 col-md-10">
                        <textarea id="editor1" name="spotlight_job_content" rows="10" cols="80"><?php echo ($this->post_data["spotlight_job_content"] != "") ? $this->post_data["spotlight_job_content"] : $this->results->spotlight_job_content; ?></textarea>
                    </div>
                    <div class="clearfix"></div>
                </div>

                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Spotlight Logo:</label>
                    <div class="col-sm-10 col-md-10">

                        <input type="file" name="spotlight_job_logo" id="spotlight_job_logo">
                    </div>
<?php
if ($this->results->spotlight_job_logo != "") {
    ?>
                        <div class="col-sm-10 col-md-10">                   
                            <img width="150" src="<?php echo $this->basePath("upload/job/" . $this->results->spotlight_job_logo); ?>" alt="spotlight logo" title="spotlight loho" />
                        </div>
    <?php
}
?>
                    <div class="clearfix"></div>
                </div>

                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Spotlight Order</label>
                    <div class="col-sm-3 col-md-3">                    
                        <select class="form-control" name="spotlight_job_order">
                            <option value="">Select order</option>
                    <?php
                    for ($order = 1; $order <= 10; $order ++) {
                        ?>
                                <option value="<?php echo $order; ?>" <?php echo (!isset($this->post_data["spotlight_job_order"]) && ($this->results->spotlight_job_order == $order)) ? 'selected=""' : '' ?>  <?php echo (isset($this->post_data["spotlight_job_order"]) && ($this->post_data["spotlight_job_order"] == $order)) ? 'selected=""' : '' ?>><?php echo $order; ?></option>
    <?php
}
?>
                        </select>
                    </div>
                    <div class="clearfix"></div>
                </div>

                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Spotlight Group</label>
                    <div class="col-sm-3 col-md-3">                    
                        <select class="form-control" name="spotlight_job_gorup">
                            <option value="">Select group</option>
                            <?php
                            for ($group = 1; $group <= 10; $group ++) {
                                ?>
                                <option value="<?php echo $group; ?>" <?php echo (!isset($this->post_data["spotlight_job_gorup"]) && ($this->results->spotlight_job_gorup == $group)) ? 'selected=""' : '' ?> <?php echo (isset($this->post_data["spotlight_job_gorup"]) && ($this->post_data["spotlight_job_gorup"] == $group)) ? 'selected=""' : '' ?>><?php echo $group; ?></option>
    <?php
}
?>
                        </select> 
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>

            <!--    
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label"> Walk-in Interview ? </label>
                <div class="col-sm-5 col-md-5">
                    
                    <label>
                        <input type="radio" name="walk_in_active" value="1" class="minimal" <?php echo ($this->post_data["walk_in_active"] == "1") ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["walk_in_active"]) && ($this->results->walk_in_active == "1")) ? 'checked=""' : ''; ?>  />Yes
                </label>
                <label>
                    <input type="radio" name="walk_in_active" value="0" class="minimal" <?php echo ($this->post_data["walk_in_active"] == "1") ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["walk_in_active"]) && ($this->results->walk_in_active == "0")) ? 'checked=""' : ''; ?>  <?php echo (!isset($this->post_data["walk_in_active"]) && ($this->results->walk_in_active == "")) ? 'checked=""' : ''; ?> />No
                </label>
    
                </div>
                <div class="clearfix"></div>
            </div>
            -->    

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Job Circular: </label>
                <div class="col-sm-10 col-md-10">
                    <div class="check_box_scroller_container">
<?php
foreach ($job_circular as $val) {
    ?>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="job_circular_id[]" value="<?php echo $val["id"]; ?>" <?php echo (!isset($this->post_data["job_circular_id"]) && in_array($val["id"], $selected_job_circular)) ? 'checked="checked"' : '' ?>  <?php echo (isset($this->post_data["job_circular_id"]) && in_array($val["id"], $this->post_data["job_circular_id"])) ? 'checked="checked"' : '' ?> />
    <?php echo $val["type"]; ?>
                                </label>
                            </div>
    <?php
}
?>                  

                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>    

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label"> Active ?</label>
                <div class="col-sm-5 col-md-5">
                    <label>
                        <input type="radio" name="status" value="1"  class="minimal" <?php echo ($this->post_data["status"] == "1") ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["status"]) && ($this->results->status == "1")) ? 'checked=""' : ''; ?> checked/>Yes
                    </label>
                    <label>                    
                        <input type="radio" name="status" value="0" class="minimal"  <?php echo ($this->post_data["status"] == "0") ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["status"]) && ($this->results->status == "0")) ? 'checked=""' : ''; ?> />No
                    </label>
                </div>
                <div class="clearfix"></div>
            </div>     


            <div class="form-group">
                <div class=" col-xs-12 col-sm-6 col-md-6 col-sm-offset-2 col-md-offset-2 btn_submit">
                    <button type="submit" class="btn btn-primary pull-left">Submit</button>&nbsp;
                    <a class="btn btn-default" href="<?php echo $this->serverUrl() . "/admin/job/newsjob"; ?>" role="button">Back</a>
                </div>                                            
            </div>            
            <div class="clearfix"></div>





        </form>



    </div>

</section>

<script type="text/javascript">

    function spotLightJob(val)
    {
        if (val == 1)
        {
            $(".spot_light_used_box").show();
        }
        else
        {
            $(".spot_light_used_box").hide();
        }
    }


    $(function () {

        //for spotlight job
        if (document.getElementById('splUsed').checked)
        {
            spotLightJob(1);
        }

        if (document.getElementById('splNUsed').checked)
        {
            spotLightJob(0);
        }


        //Money Euro
        $("[data-mask]").inputmask();

        // Replace the <textarea id="editor1"> with a CKEditor
        // instance, using default configuration.
         CKEDITOR.replace('company_description');
         CKEDITOR.replace('job_education');
         CKEDITOR.replace('job_description');
         CKEDITOR.replace('job_requirement');
         CKEDITOR.replace('job_experienced');
         //CKEDITOR.replace('job_apply_instruction');
         CKEDITOR.replace('compnay_address');
         CKEDITOR.replace('other_information');
         //$(".textarea").wysihtml5();
         
         
         /*CKEDITOR.replace('job_apply_instruction',
         {
         filebrowserBrowseUrl: '/ckfinder/ckfinder.html',
         filebrowserImageBrowseUrl: '/ckfinder/ckfinder.html',
         filebrowserFlashBrowseUrl: '/ckfinder/ckfinder.html',
         filebrowserUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload',
         filebrowserImageUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload',
         filebrowserFlashUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload'
         });
         */



        /*CKEDITOR.replace('job_requirement', {
         customConfig: '/plugins/ckeditor/custom_config.js'
         });*/



        /*CKEDITOR.replace('editor1', {
         filebrowserBrowseUrl: '/ckfinder/ckfinder.html',
         filebrowserImageBrowseUrl: '/ckfinder/ckfinder.html',
         filebrowserFlashBrowseUrl: '/ckfinder/ckfinder.html',
         filebrowserUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload',
         filebrowserImageUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload',
         filebrowserFlashUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload'
         });*/

        

        CKEDITOR.replace('job_apply_instruction', {
            customConfig: '/plugins/ckeditor/custom_config.js',
            filebrowserBrowseUrl: '/ckfinder/ckfinder.html',
            filebrowserImageBrowseUrl: '/ckfinder/ckfinder.html',
            filebrowserFlashBrowseUrl: '/ckfinder/ckfinder.html',
            filebrowserUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload',
            filebrowserImageUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload',
            filebrowserFlashUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload'

        });
        
        
        CKEDITOR.replace('editor1', {
            customConfig: '/plugins/ckeditor/custom_config.js',
            filebrowserBrowseUrl: '/ckfinder/ckfinder.html',
            filebrowserImageBrowseUrl: '/ckfinder/ckfinder.html',
            filebrowserFlashBrowseUrl: '/ckfinder/ckfinder.html',
            filebrowserUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload',
            filebrowserImageUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload',
            filebrowserFlashUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload'

        });


        //iCheck for checkbox and radio inputs
        $('input[type="checkbox"].minimal').iCheck({
            checkboxClass: 'icheckbox_minimal-blue'
                    //radioClass: 'iradio_minimal-blue'
        });

        //Type age
        if (document.getElementById('type_age').checked)
        {
            $(".age_limit_box").hide();
            $(".age_limit_other_box").show();
        }


        $('input[type="checkbox"][name="type_age"]').on('ifChanged', function (event) {
            if (this.checked) {
                $(".age_limit_box").hide();
                $(".age_limit_other_box").show();
            }
            else
            {
                $(".age_limit_box").show();
                $(".age_limit_other_box").hide();
            }
        });


    });

</script>