<div>
    <?php
    $flash = $this->flashMessenger();
    echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger'));
    echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info'));
    echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
    echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
    ?>
</div> 

<section class="content">    
    <div class="govt_job_ad_form_container box box-default admin_form_bg"> 
        <form role="form" data-toggle="validator" class="form-horizontal register_employer_form" method="post" enctype="multipart/form-data">
            <h1>New Spotlight job Add</h1>          

            <?php if (count($this->error_messages) > 0) { ?>
                <div class="alert alert-danger">
                    <?php
                    foreach ($this->error_messages as $messageId => $message) {
                        echo "<p>  $message </p>";
                    }
                    ?>   
                </div> 
            <?php } ?>

            <?php if (count($this->success_messages) > 0) { ?>
                <div class="alert alert-success">
                    <?php
                    foreach ($this->success_messages as $messageId => $message) {
                        echo "<p>  $message </p>";
                    }
                    ?>   
                </div>
            <?php } ?>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Title:</label>
                <div class="col-sm-5 col-md-5">                    
                    <input type="text" class="form-control" id="job_title" name="job_title" placeholder="Title" value="<?php echo ($this->post_data["job_title"] != "") ? $this->post_data["job_title"] : $this->results->job_title; ?>" required  />
                </div>
                <div class="clearfix"></div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Company Url:</label>
                <div class="col-sm-5 col-md-5">
                    <input type="text" class="form-control" id="inputPassword3" name="job_url" placeholder="website" value="<?php echo ($this->post_data["job_url"] != "") ? $this->post_data["job_url"] : $this->results->job_url; ?>" required />
                </div>
                <div class="clearfix"></div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Job Content</label>
                <div class="col-sm-10 col-md-10">
                    <textarea id="editor1" name="job_content" rows="10" cols="80"><?php echo ($this->post_data["job_content"] != "") ? $this->post_data["job_content"] : $this->results->job_content; ?></textarea>
                </div>
                <div class="clearfix"></div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Logo</label>
                <div class="col-sm-10 col-md-10">

                    <input type="file" name="image-file" id="image-file">
                </div>
                <div class="clearfix"></div>
            </div>
            
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Order</label>
                <div class="col-sm-5 col-md-5">                    
                    <input type="text" class="form-control" id="job_order" name="job_order" placeholder="Order of job" value="<?php echo ($this->post_data["job_title"] != "") ? $this->post_data["job_title"] : $this->results->job_title; ?>" required  />
                </div>
                <div class="clearfix"></div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Date of Interview:</label>
                <div class="col-sm-5 col-md-5">
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-calendar"></i>
                        </div>
                        <?php
                        if (($this->results->job_deadline != "") && ($this->results->job_deadline != "0000-00-00")) {
                            $job_deadline = $this->results->job_deadline;
                        } else {
                            $job_deadline = "";
                        }
                        ?>
                        <input type="text" name="job_deadline" value="<?php echo ($this->post_data["job_deadline"] != "") ? $this->post_data["job_deadline"] : $job_deadline; ?>" class="form-control" data-inputmask="'alias': 'yyyy-mm-dd'" data-mask required />
                    </div>                
                </div>

                <div class="clearfix"></div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Bill Status:</label>
                <div class="col-sm-5 col-md-5">
                    <select class="form-control" name="published">
                        <option value="billable" <?php echo ($this->post_data["bill_status"] == "billable") ? 'selected=""' : ''; ?> <?php echo (!isset($this->post_data["bill_status"]) && ($this->results->published == "billable")) ? 'selected=""' : ''; ?>>Billable</option>
                        <option value="non-billable" <?php echo ($this->post_data["bill_status"] == "non-bilallable") ? 'selected=""' : ''; ?> <?php echo (!isset($this->post_data["published"]) && ($this->results->published == "non-billable")) ? 'selected=""' : ''; ?>>Non-billable</option>

                    </select>
                </div>
                <div class="clearfix"></div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Bill amount</label>
                <div class="col-sm-5 col-md-5">                    
                    <input type="text" class="form-control" id="bill_amount" name="bill_amount" placeholder="Bill amount" value="<?php echo ($this->post_data["job_title"] != "") ? $this->post_data["bill_amount"] : $this->results->bill_amount; ?>"   />
                </div>
                <div class="clearfix"></div>
            </div>



            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Job of the week</label>
                <div class="col-sm-5 col-md-5">
                    <label>
                        <input type="radio" name="job_of_week" value="1"  class="minimal" <?php echo ($this->post_data["job_of_week"] == 1) ? 'checked=""' : '';?> <?php echo (!isset($this->post_data["job_of_week"]) && ($this->results->job_of_the_week == "1")) ? 'checked=""' : ''; ?> />Yes
                    </label>
                    <label>                    
                        <input type="radio" name="job_of_week" value="0" class="minimal" <?php echo (isset($this->post_data["job_of_week"]) && ($this->post_data["job_of_week"] == 0)) ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["status"]) && ($this->results->job_of_the_week == "0")) ? 'checked=""' : ''; ?> checked />No
                    </label>
                </div>
                <div class="clearfix"></div>
            </div>     



            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Is Active?</label>
                <div class="col-sm-5 col-md-5">
                    <label>
                        <input type="radio" name="status" value="1"  class="minimal" <?php //echo ($this->post_data["status"] == 1) ? 'checked=""' : '';          ?> <?php echo (!isset($this->post_data["status"]) && ($this->results->status == "1")) ? 'checked=""' : ''; ?> checked/>Yes
                    </label>
                    <label>                    
                        <input type="radio" name="status" value="0" class="minimal" <?php echo (isset($this->post_data["status"]) && ($this->post_data["status"] == 0)) ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["status"]) && ($this->results->status == "0")) ? 'checked=""' : ''; ?> />No
                    </label>
                </div>
                <div class="clearfix"></div>
            </div>     


            <div class="form-group">
                <div class=" col-xs-12 col-sm-6 col-md-6 col-sm-offset-2 col-md-offset-2 btn_submit">
                    <button type="submit" class="btn btn-primary pull-left">Submit</button>
                    <a class="btn btn-default" href="<?php echo $this->serverUrl()."/admin/job/spotlightjob";?>" role="button">Back</a>
                </div>
            </div>            
            <div class="clearfix"></div>

        </form>

        <!-- media modal... -->
        <div id="media-modal" class="modal fade">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <button class="close" data-dismiss="modal">&times;</button>
                        <h4>Media Manager</h4>
                    </div>
                    <div class="modal-body">
                        <!-- nav tabs -->
                        <ul class="nav nav-tabs" id="myTabs">
                            <li class="active"><a href="#upload" data-toggle="tab">Upload</a></li>
                            <li><a href="#librayr" data-toggle="tab">Library</a></li>
                        </ul>
                        <!-- tab panes -->
                        <div class="tab-content">
                            <div class="tab-pane active fade in" id="upload">
                                <p>upload area is here...... will be here.....</p>
                                <button class="btn btn-info">Add Files</button>
                            </div>
                            <!-- library tab -->
                            <div class="tab-pane fade" id="librayr">
                                <!-- images hard coded.. -->
                                <!-- data-image-id contains image id from database... -->
                                <?php
                                $destination_url = $this->basePath() . '/images';
                                $files = glob("$destination_url/*.{jpg,png,gif}", GLOB_BRACE);
                                print_r($files);
                                $files = sort($files);
                                foreach ($files as $file) {
                                    //do your work here
                                    ?>
                                    <a href="#" data-image-id="1">
                                        <img src="/images/<?php echo $file; ?>" alt="">
                                        <input type="checkbox" name="images-check" value="<?php echo $file; ?>"><?php echo $file; ?></a>
                                    </a>
                                <?php } ?>
                                <a href="#" data-image-id="2">
                                    <img src="images/graphic-card.jpg" alt="">
                                    <input type="checkbox" name="images-check">
                                </a>
                                <a href="#" data-image-id="3">
                                    <img src="images/laptop.jpg" alt="">
                                    <input type="checkbox" name="images-check">
                                </a>
                                <a href="#" data-image-id="4">
                                    <img src="images/motherboard.jpg" alt="">
                                    <input type="checkbox" name="images-check">
                                </a>
                                <div class="clearfix"></div>
                                <!-- insert button -->
                                <button type="button" class="btn btn-sm btn-info insert">Insert</button>
                            </div><!-- end .library -->
                        </div><!-- end tab-content -->
                    </div>
                </div><!-- end .modal-content -->
            </div><!-- end .modal-dialog -->
        </div><!-- end .modal -->

    </div>    
</section>

<script type="text/javascript">

    $(function() {

        //Datemask dd/mm/yyyy
        //$("#datemask").inputmask("yyyy/mm/dd", {"placeholder": "yyyy/mm/dd"});
        //Datemask2 mm/dd/yyyy
        //$("#datemask2").inputmask("yyyy/mm/dd", {"placeholder": "yyyy/mm/dd"});
        //Money Euro
        $("[data-mask]").inputmask();

        // Replace the <textarea id="editor1"> with a CKEditor
        // instance, using default configuration.
        // CKEDITOR.replace('editor1');
        // $(".textarea").wysihtml5();


        CKEDITOR.replace('editor1', {
            filebrowserBrowseUrl: '/ckfinder/ckfinder.html',
            filebrowserImageBrowseUrl: '/ckfinder/ckfinder.html',
            filebrowserFlashBrowseUrl: '/ckfinder/ckfinder.html',
            filebrowserUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload',
            filebrowserImageUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload',
            filebrowserFlashUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload'
        });

        //iCheck for checkbox and radio inputs
        $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
            checkboxClass: 'icheckbox_minimal-blue',
            radioClass: 'iradio_minimal-blue'
        });



    });

</script>
<script>
    var mediaModal = $('#media-modal'),
            library = $('#librayr'), //tab
            productImagesContainer = $('.product-images'); //container
    library.on('click', 'a', function(e) {
        e.preventDefault();
//checkboxprocessing........
        var checkbox = $(this).find('input[type=checkbox]');
        if (!checkbox.is(':checked')) {
            checkbox.prop('checked', true);
        } else {
            checkbox.prop('checked', false);
        }
    });
//insert button and send images to the form and hidden fields tooo....
    $('.insert').click(function(e) {
//collect checkbox
        var checkboxes = library.find('input[type=checkbox]');
        checkboxes.each(function(i, el) {
            if (el.checked) {
                var imageId = $(el).parent().data('image-id');
                var imgSrc = $(el).siblings('img').attr('src');
//template
                var template = '<div class="product-img">' +
                        '<input type="hidden" name="image-ids[]" value="' + imageId + '">' +
                        '<img src="' + imgSrc + '" />' +
                        '<a href="#" class="btn btn-xs btn-danger remove">' +
                        '<span class="glyphicon glyphicon-remove-sign"></span></a>' +
                        '</div>';
//append
                productImagesContainer.append(template);
            }
        });
//hide modal
        mediaModal.modal('hide');
    });
//remove product images js
    productImagesContainer.on('click', '.remove', function(e) {
        e.preventDefault();
//fadeout animation and remove....
        $(this).parent('.product-img').fadeOut('100', function() {
            $(this).remove();
        });
    });
//thanks for watching........... this video..............
//subscribe, share, like, comment....
/////...............
</script>

