    <div>
    <?php
        $flash = $this->flashMessenger();
        echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger'));
        echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info'));
        echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
        echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
    ?>
    </div> 

<section class="content">    
    <div class="govt_job_ad_form_container box box-default admin_form_bg"> 
        <form role="form" data-toggle="validator" class="form-horizontal register_employer_form" method="post" enctype="multipart/form-data">
            <h1>New Walk-in-Interview Add</h1>          
            
            <?php 
            if (count($this->error_messages) > 0) { ?>
            <div class="alert alert-danger">
                <?php                                 
                foreach ($this->error_messages as $messageId => $message) {                        
                        echo "<p>  $message </p>";           
                }
                ?>   
            </div> 
            <?php } ?>

            <?php if (count($this->success_messages) > 0) { ?>
            <div class="alert alert-success">
                <?php
                foreach ($this->success_messages as $messageId => $message) {
                    echo "<p>  $message </p>";
                }
                ?>   
            </div>
            <?php } ?>
            
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Company name:</label>
                <div class="col-sm-5 col-md-5">                    
                    <input type="text" class="form-control" id="job_company_name" name="job_company_name" placeholder="Company Name" value="<?php echo ($this->post_data["job_company_name"] != "") ? $this->post_data["job_company_name"] : $this->results->job_company_name; ?>" required  />
                </div>
                <div class="clearfix"></div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Position:</label>
                <div class="col-sm-5 col-md-5">
                    <input type="text" class="form-control" id="inputPassword3" name="position" placeholder="position" value="<?php echo ($this->post_data["position"] != "") ? $this->post_data["position"] : $this->results->job_level; ?>" required />
                </div>
                <div class="clearfix"></div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Education:</label>
                <div class="col-sm-10 col-md-10">
                    <textarea id="editor1" name="job_education" rows="10" cols="80"><?php echo ($this->post_data["job_education"] != "") ? $this->post_data["job_education"] : $this->results->job_education; ?></textarea>
                </div>
                <div class="clearfix"></div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Job Category</label>
                <div class="col-sm-10 col-md-10">
                    <div class="check_box_scroller_container">
                        <?php
                        $job_category_id = $this->results->job_category_id;
                        $job_category    = explode(",", $job_category_id);
                        
                        foreach($this->job_category as $category)
                        {
                           ?>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" id="checkboxSuccess" name="job_category_id[]" value="<?php echo $category["id"]; ?>" <?php echo (! isset($this->post_data["job_category_id"]) && in_array($category["id"], $job_category)) ? 'checked="checked"' : '' ?> <?php echo (isset($this->post_data["job_category_id"]) && in_array($category["id"], $this->post_data["job_category_id"])) ? 'checked="checked"' : '' ?> />
                                    <?php echo $category["name"]; ?>
                                </label>
                             </div>
                           <?php
                        }    
                        ?>                   

                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Published In:</label>
                <div class="col-sm-5 col-md-5">
                    <select class="form-control" name="published">
                        <option value="The Daily Prothom Alo" <?php echo ($this->post_data["published"] == "The Daily Star") ? 'selected=""' : ''; ?> <?php echo (!isset($this->post_data["published"]) && ($this->results->published == "The Daily Prothom Alo")) ? 'selected=""' : ''; ?>>The Daily Prothom Alo</option>
                        <option value="The Daily Star" <?php echo ($this->post_data["published"] == "The Daily Star") ? 'selected=""' : ''; ?> <?php echo (!isset($this->post_data["published"]) && ($this->results->published == "The Daily Star")) ? 'selected=""' : ''; ?>>The Daily Star</option>
                        <option value="The Financial Express" <?php echo ($this->post_data["published"] == "The Financial Express") ? 'selected=""' : ''; ?> <?php echo (!isset($this->post_data["published"]) && ($this->results->published == "The Financial Express")) ? 'selected=""' : ''; ?>>The Financial Express</option>
                        <option value="The Daily Naya Diganta" <?php echo ($this->post_data["published"] == "The Daily Naya Diganta") ? 'selected=""' : ''; ?> <?php echo (!isset($this->post_data["published"]) && ($this->results->published == "The Daily Naya Diganta")) ? 'selected=""' : ''; ?>>The Daily Naya Diganta</option>
                        <option value="The Independent" <?php echo ($this->post_data["published"] == "The Independent") ? 'selected=""' : ''; ?> <?php echo (!isset($this->post_data["published"]) && ($this->results->published == "The Independent")) ? 'selected=""' : ''; ?>>The Independent</option>
                        <option value="The Daily Jugantor" <?php echo ($this->post_data["published"] == "The Daily Jugantor") ? 'selected=""' : ''; ?> <?php echo (!isset($this->post_data["published"]) && ($this->results->published == "The Daily Jugantor")) ? 'selected=""' : ''; ?>>The Daily Jugantor</option>
                        <option value="The Daily Ittefaq" <?php echo ($this->post_data["published"] == "The Daily Ittefaq") ? 'selected=""' : ''; ?> <?php echo (!isset($this->post_data["published"]) && ($this->results->published == "The Daily Ittefaq")) ? 'selected=""' : ''; ?>>The Daily Ittefaq</option>
                        <option value="Samakal" <?php echo ($this->post_data["published"] == "Samakal") ? 'selected=""' : ''; ?> <?php echo (!isset($this->post_data["published"]) && ($this->results->published == "Samakal")) ? 'selected=""' : ''; ?>>Samakal</option>
                        <option value="Others" <?php echo ($this->post_data["published"] == "Others") ? 'selected=""' : ''; ?> <?php echo (!isset($this->post_data["published"]) && ($this->results->published == "Others")) ? 'selected=""' : ''; ?>>Others</option>
                    </select>
                </div>
                <div class="clearfix"></div>
            </div>


            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Published Date:</label>
                <div class="col-sm-5 col-md-5">
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-calendar"></i>
                        </div>
                        <?php
                        if(($this->results->posting_date !="") && ($this->results->posting_date !="0000-00-00"))
                        {
                            $posting_date = $this->results->posting_date;
                        }
                        else{
                            $posting_date = date("Y-m-d");
                        }
                        ?>
                        
                        <input type="text" name="published_date" value="<?php echo ($this->post_data["published_date"] != "") ? $this->post_data["published_date"] : $posting_date; ?>" class="form-control" data-inputmask="'alias': 'yyyy-mm-dd'"  data-mask required />
                    </div>                
                </div>

                <div class="clearfix"></div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Deadline:</label>
                <div class="col-sm-5 col-md-5">
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-calendar"></i>
                        </div>
                        <?php
                        if(($this->results->job_deadline !="") && ($this->results->job_deadline !="0000-00-00"))
                        {
                            $job_deadline = $this->results->job_deadline;
                        }
                        else{
                            $job_deadline = "";
                        }
                        ?>
                        <input type="text" name="job_deadline" value="<?php echo ($this->post_data["job_deadline"] != "") ? $this->post_data["job_deadline"] : $job_deadline; ?>" class="form-control" data-inputmask="'alias': 'yyyy-mm-dd'" data-mask required />
                    </div>                
                </div>

                <div class="clearfix"></div>
            </div>            
            
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Picture:</label>
                <div class="col-sm-5 col-md-5">
                    <input type="file" id="image-file" name="image-file" />
                </div>
                <?php
                if($this->results->job_image !="")
                {    
                    ?>
                    <div class="col-sm-10 col-md-10">                   
                        <img width="150" src="<?php echo "/upload/job/".$this->results->job_image; ?>" alt="spotlight logo" title="spotlight logo" />
                    </div>
                <?php
                }
                ?>
                <div class="clearfix"></div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Is Active?</label>
                <div class="col-sm-5 col-md-5">
                    <label>
                        <input type="radio" name="status" value="1"  class="minimal" <?php echo ($this->post_data["status"] == 1) ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["status"]) && ($this->results->status == "1")) ? 'checked=""' : ''; ?> checked/>Yes
                    </label>
                    <label>                    
                        <input type="radio" name="status" value="0" class="minimal" <?php echo (isset($this->post_data["status"]) && ($this->post_data["status"] == 0)) ? 'checked=""' : ''; ?> <?php echo (!isset($this->post_data["status"]) && ($this->results->status == "0")) ? 'checked=""' : ''; ?> />No
                    </label>
                </div>
                <div class="clearfix"></div>
            </div>     


            <div class="form-group">
                <div class=" col-xs-12 col-sm-6 col-md-6 col-sm-offset-2 col-md-offset-2 btn_submit">
                    <button type="submit" class="btn btn-primary pull-left">Submit</button>&nbsp;
                    <a class="btn btn-default" href="<?php echo $this->serverUrl()."/admin/job/walkin"; ?>" role="button">Back</a>
                </div>                                            
            </div>            
            <div class="clearfix"></div>
            
        </form>
    </div>    
</section>

<script type="text/javascript">
    
      $(function(){
          
          //Datemask dd/mm/yyyy
        //$("#datemask").inputmask("yyyy/mm/dd", {"placeholder": "yyyy/mm/dd"});
        //Datemask2 mm/dd/yyyy
        //$("#datemask2").inputmask("yyyy/mm/dd", {"placeholder": "yyyy/mm/dd"});
        //Money Euro
        $("[data-mask]").inputmask();
          
        // Replace the <textarea id="editor1"> with a CKEditor
        // instance, using default configuration.
        CKEDITOR.replace('editor1');
        $(".textarea").wysihtml5();
        
        
        //iCheck for checkbox and radio inputs
        $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
          checkboxClass: 'icheckbox_minimal-blue',
          radioClass: 'iradio_minimal-blue'
        });
        
       
        
      });

</script>