<div class="hidden-xs common_google_ads t1-position-ad">   
    <!-- /85406138/Chakri_About-Policy-Terms_T1_970x90 -->
    <div id='div-gpt-ad-1444720035828-0'>
        <script type='text/javascript'>
            googletag.cmd.push(function() {
                googletag.display('div-gpt-ad-1444720035828-0');
            });
        </script>
    </div>    
</div>

<div class="col-xs-12 col-sm-12 col-md-12 about_us_page_container special_page_for_ad">     
    <div class="pagination_top_container">
        <ul>
            <li><a href="">Home</a></li>
            <li>About us</li>           
            <div class="clearfix"></div>
        </ul>        
    </div>
    
    <div class="row">
    <div class="col-md-7">
        <h2>About us</h2>
        <p>To meet digital-Bangladesh’s demand for a complete career portal, Prothom alojobs.com was founded in the year 2007 with the mission to connect job seekers directly with employers by shortening the job seeker's search and lowering the employer's cost per hire, through the application of pioneering online-based technology. </p> 

        <p>Prothom-alojobs.com allows job seekers to find and apply for jobs for the leading companies of the country, while employers are able to advertise on profession-specific categories to leverage focused advertising in finding qualified candidates for employment. We also aim to provide cost-effective employment advertising to employer companies.</p>

        <p>Prothom-alojobs.com also offers seminars, student consultancy programs, exclusive training sessions, job market awareness programs and job fairs to provide full knowledge about the current career market among the jobseekers and the employers. Also, we have established a dedicated career development radio show as well as a newspaper column to set the best guidelines for the aspiring job seekers, thus helping them to become a part of Bangladesh’s productive and skilled workforce besides being responsible citizens of Bangladesh.</p> 

        <p>To find more about the career development services that we provide,  visit Exclusive Features</p>

        <h3>Mission </h3>
        <p>Prothom-alojobs.com allows job seekers to find and apply for jobs for the leading companies of the country,
            while employers are able to advertise on profession-specific categories to leverage focused advertising in
            finding qualified candidates for employment. We also aim to provide cost-effective employment advertising
            to employer companies.</p>

        <h3>Vision</h3>
        <p>Prothom-alojobs.com allows job seekers to find and apply for jobs for the leading companies of the country,
            while employers are able to advertise on profession-specific categories to leverage focused advertising in
            finding qualified candidates for employment. We also aim to provide cost-effective employment advertising
            to employer companies.</p>
    </div>

    <div class="col-md-5 about_right_ad_container pull-right">
        <div class="hidden-xs common_google_ads no_top_margin">
            <!-- /85406138/Chakri_About-Policy-Terms_R1_336x280 -->
            <div id='div-gpt-ad-1444720195570-0' style='height:280px; width:336px;'>
                <script type='text/javascript'>
                    googletag.cmd.push(function() {
                        googletag.display('div-gpt-ad-1444720195570-0');
                    });
                </script>
            </div>
        </div>

        <div class="hidden-xs common_google_ads">               
            <!-- /85406138/Chakri_About-Policy-Terms_F1_300x600 -->
            <div id='div-gpt-ad-1444720239236-0' style='height:600px; width:300px;'>
                <script type='text/javascript'>
                    googletag.cmd.push(function() {
                        googletag.display('div-gpt-ad-1444720239236-0');
                    });
                </script>
            </div>                
        </div>
    </div>
</div>
</div>

<div class="hidden-xs col-sm-12 col-md-12 common_google_ads">
    <!-- /85406138/Chakri_About-Policy-Terms_B2_970x90 -->
    <div id='div-gpt-ad-1444720307947-0'>
        <script type='text/javascript'>
            googletag.cmd.push(function() {
                googletag.display('div-gpt-ad-1444720307947-0');
            });
        </script>
    </div>
</div>