<div class="row"> 
    <div class="hidden-xs col-sm-12 col-md-12 common_google_ads t1-position-ad">

        <!-- /85406138/Chakri_Search-Contact_T1_970x90 -->
        <div id='div-gpt-ad-1444720380589-0'>
            <script type='text/javascript'>
                googletag.cmd.push(function() {
                    googletag.display('div-gpt-ad-1444720380589-0');
                });
            </script>
        </div>
        <!-- /85406138/Chakri_Jobdetails_T1_970x90 -->
    </div>
</div>

<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 advanced_search_page_container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 pagination_top_container">
                <ul>
                    <li><a href="/">Home</a></li>
                    <li>Advanced Job Search</li>           
                    <div class="clearfix"></div>
                </ul>        
            </div>
        </div>

        <div class="row">        
            <div class="col-xs-12 col-sm-12 col-md-12 advanced_job_search_page">
                <h2>Advanced job search</h2>

                <p>Find the latest jobs on chakri.com. Target your job search by selecting from the relevant fields below.</p>
                <p>Please ensure that you <a href="/registration" target="_blank">post your CV</a> on our website. This will allow you to apply for jobs and allow employers to search for <i>you</i>. Applying for jobs on chakri.com is completely free!</p>

                <!-- <form name="form" method="get" action="/en/job-search-results/" onsubmit="return formValidator(this);"> -->

                <div class="advncd_job_search_container">
                    <form class="form-horizontal" method="get" action="/job">
                        <fieldset>
                            <legend>Job Information</legend>

                            <div class="form-group">
                                <label for="inputEmail3" class="col-sm-2 control-label">Keywords</label>
                                <div class="col-sm-7">
                                    <input type="keyword" name="job_title" class="form-control top_input_field" id="inputEmail3" placeholder="Keywords">
                                    <!--<label>
                                        <input type="radio" name="all" id="optionsRadios2" value="option2">
                                        All of these words
                                    </label>
        
                                    <label>
                                        <input type="radio" name="any" id="optionsRadios2" value="option2">
                                        Any of these words 
                                    </label>
        
                                    <label>
                                        <input type="radio" name="exact" id="optionsRadios2" value="option2">
                                        Exact phrase
                                    </label>-->
                                </div>
                                <div class="clearfix"></div>
                            </div>

                            <div class="form-group">
                                <label for="inputEmail3" class="col-sm-2 control-label">Company</label>
                                <div class="col-sm-7">
                                    <input type="text" name="company" class="form-control top_input_field" id="inputEmail3" placeholder="Company Name">                            
                                </div>
                                <div class="clearfix"></div>
                            </div>


                            <div class="form-group">
                                <label for="inputEmail3" class="col-sm-2 control-label">Job Location:</label>
                                <div class="col-sm-7">
                                    <select  class="form-control" name="loc">
                                        <option value=""> Select District </option>
                                        <?php foreach ($divisions as $division): ?>
                                            <option value="<?php echo $division['id']; ?>"><?php echo $division['name']; ?></option>
                                        <?php endforeach; ?>
                                    </select> 
                                </div>
                                <div class="clearfix"></div>
                            </div>


                            <div class="form-group">
                                <label for="inputEmail3" class="col-sm-2 control-label">Job Category:</label>
                                <div class="col-sm-7">
                                    <select class="form-control" name="job_category">
                                        <option value="">Select Category</option>   
                                        <?php foreach ($categories as $category): ?>
                                            <option value="<?php echo $category['id']; ?>"><?php echo $category['name']; ?></option> 
                                        <?php endforeach; ?>
                                    </select>                        
                                </div>
                                <div class="clearfix"></div>
                            </div>


                            <div class="form-group">
                                <label for="inputEmail3" class="col-sm-2 control-label">Salary Range:</label>
                                <div class="col-sm-7">
                                    <select class="form-control" name = 'salaryrange'>
                                        <option value="">Select</option>
                                        <option value="8000-12000">8000 - 12000</option>
                                        <option value="13000-25000">13000 - 25000</option>
                                        <option value="20000-40000">20000 - 40000</option>
                                        <option value="40000-60000">40000 - 60000</option>
                                        <option value="60000-80000">60000 - 80000</option>
                                        <option value="Negotiable">Negotiable</option>
                                    </select>                        
                                </div>
                                <div class="clearfix"></div>
                            </div> 

                            <div class="form-group">
                                <label for="inputEmail3" class="col-sm-2 control-label">Job Level:</label>
                                <div class="col-sm-7">
                                    <div class="col-xs-12 col-sm-2 col-md-3 no_padding_left">
                                        <label class="radio-inline">
                                            <input type="radio" name="job_level" id="optionsRadios2" value="Entry"> Entry
                                        </label>   
                                    </div>

                                    <div class="col-xs-12 col-sm-2 col-md-3 no_padding_left">
                                        <label class="radio-inline">
                                            <input type="radio" name="job_level" id="optionsRadios2" value="Mid"> Mid                                </label>   
                                    </div>

                                    <div class="col-xs-12 col-sm-2 col-md-3 no_padding_left">
                                        <label class="radio-inline">
                                            <input type="radio" name="job_level" id="optionsRadios2" value="Top"> Top
                                        </label>   
                                    </div> 

                                </div>
                                <div class="clearfix"></div>
                            </div> 

                            <div class="form-group">
                                <label for="inputEmail3" class="col-sm-2 control-label"> Job Type: </label>
                                <div class="col-sm-7">                       

                                    <div class="col-xs-12 col-sm-2 col-md-4 no_padding_left">
                                        <label class="radio-inline">
                                            <input type="radio" name="job_type" id="optionsRadios2" value="Full Time"> Full Time
                                        </label>   
                                    </div>

                                    <div class="col-xs-12 col-sm-2 col-md-3 no_padding_left">
                                        <label class="radio-inline">
                                            <input type="radio" name="job_type" id="optionsRadios2" value="Part Time"> Part Time
                                        </label>   
                                    </div>

                                    <div class="col-xs-12 col-sm-2 col-md-3 no_padding_left">
                                        <label class="radio-inline">
                                            <input type="radio" name="job_type" id="optionsRadios2" value="Contractual">Contractual
                                        </label>   
                                    </div> 
                                    <div class="col-xs-12 col-sm-2 col-md-3 no_padding_left">
                                        <label class="radio-inline">
                                            <input type="radio" name="job_type" id="optionsRadios2" value="Intern ">Intern 
                                        </label>   
                                    </div>

                                </div>
                                <div class="clearfix"></div>
                            </div>


                            <div class="form-group">
                                <label for="inputEmail3" class="col-sm-2 control-label">Newspaper Job Source:</label>
                                <div class="col-sm-7">
                                    <select class="form-control" name="newspaper_source">
                                        <option value="">Select Source</option>
                                        <option value="The Daily Prothom Alo">The Daily Prothom Alo</option>
                                        <option value="The Daily Star">The Daily Star</option>
                                        <option value="The Financial Express">The Financial Express</option>
                                        <option value="The Daily Naya Diganta">The Daily Naya Diganta</option>
                                        <option value="The Independent">The Independent</option>
                                        <option value="The Daily Jugantor">The Daily Jugantor</option>
                                        <option value="The Daily Ittefaq">The Daily Ittefaq</option>
                                        <option value="Samakal">Samakal</option>
                                    </select> 
                                </div>
                                <div class="clearfix"></div>
                            </div>

                            <div class="form-group">
                                <label for="inputEmail3" class="col-sm-2 control-label">Publish Date</label>
                                <div class="col-sm-7">

                                    <div class="input-group ">
                                        <div class="input-group-addon">
                                            <i class="fa fa-calendar"></i>
                                        </div>

                                        <input type='text' class="form-control" placeholder="yyyy-mm-dd" data-mask="" data-inputmask="'alias': 'yyyy-mm-dd'"  name="publish_date" value="" />

                                    </div>   
                                </div>
                                <div class="clearfix"></div>
                            </div>


                            <button type="submit" class="btn btn-primary col-md-offset-2">Search Jobs</button>

                        </fieldset>           

                    </form>
                </div>


            </div>
        </div>
    </div>

</div>

<script type="text/javascript">
    $(document).ready(function() {

        //$("[data-mask]").inputmask();
        $("#datemask").inputmask("yyyy-mm-dd", {"placeholder": "yyyy-mm-dd"});
        $("[data-mask]").inputmask();
    });

</script>
