<div class="col-xs-12 col-sm-12 col-md-12 category_dtls_page_top_container">   
    <div class="col-xs-12 col-sm-10 col-md-10">
        <h2>Find Your Perfect Jobs</h2> 
        <p>Choose from 8,973 jobs. Let employers find you online. Receive matching jobs by email.
            Easy and 100% free!</p>
    </div>
    <div class="col-xs-12 col-sm-2 col-md-2">
        <a href="/registration" class="btn btn-warning ctgry_dtls_post_cv">Post Your CV</a>
    </div>
</div>

<form method="get" action="/job" >
    <div class="col-xs-12 col-sm-12 col-md-12 category_dtls_page_bottom_container">   
        <div class="col-xs-12 col-sm-3 col-md-3  ctgry_dtls_left_container">
            <div class="ctgry_dtls_header_left">
                <h3>Refine Results</h3>            
            </div>

            <p class="functional_area_search">Functional Area</p>
            <div class="functional_area_list">
                <ul>
                    <?php foreach ($functional_type as $ftype) { ?> 
                        <li class="category_select_click"><label class="radio-inline">
                                <input type="radio" name="jobCategory" id="inlineRadio1" value="<?php echo $ftype['id']; ?>"> <?php echo $ftype['name']; ?>
                            </label></li>                                        

                    <?php } ?>
                    <div class="clearfix"></div>
                </ul>
            </div>


            <p class="industry_type_search">Industry Type</p>
            <div class="industry_list">
                <ul>
                    <?php foreach ($industries as $industry) { ?> 
                        <li><label class="radio-inline">
                                <input type="radio" name="jobInduetry" id="inlineRadio1" value="<?php echo $industry['id']; ?>" > <?php echo $industry['name']; ?>
                            </label></li>

                    <?php } ?>
                    <div class="clearfix"></div>
                </ul>
            </div>

            <p class="job_level_search">Job Level</p> 
            <div class="job_level_list">
                <ul>
                    <li><label class="radio-inline">
                            <input type="radio" name="job_level" id="inlineRadio1" value="anyLevel" > Any
                        </label></li>

                    <li><label class="radio-inline">
                            <input type="radio" name="job_level" id="inlineRadio1" value="entryLevel" > Entry Level 
                        </label></li>

                    <li><label class="radio-inline">
                            <input type="radio" name="job_level" id="inlineRadio1" value="midLevel" > Mid Level
                        </label></li>

                    <li><label class="radio-inline">
                            <input type="radio" name="job_level" id="inlineRadio1" value="top_level" > Top Level
                        </label></li>


                    <div class="clearfix"></div>
                </ul>
            </div>

            <p class="by_education_search">By Education</p>              

            <div class="education_list">
                <ul>
                    <?php foreach ($degrees as $degree) { ?> 
                        <li><label class="radio-inline">
                                <input type="radio" name="degreeType" id="inlineRadio1" value="<?php echo $degree['id']; ?>" > <?php echo $degree['name']; ?>
                            </label></li>

                    <?php } ?>
                    <div class="clearfix"></div>
                </ul>
            </div>


            <p class="by_employer_search">By Employer</p> 


            <div class="employer_list">
                <ul>
                    <?php foreach ($companies as $company) { ?> 
                        <li><label class="radio-inline">
                                <input type="radio" name="employeeId" id="inlineRadio1" value="<?php echo $company['id']; ?>" > <?php echo $company['full_name']; ?>
                            </label></li>

                    <?php } ?>
                    <div class="clearfix"></div>
                </ul>
            </div>

            <p class="job_type">Job Type</p> 
            <div class="job_type_list">
                <ul>
                    <li><label class="radio-inline">
                            <input type="radio" name="employeeId" id="inlineRadio1" value="any" > Any
                        </label></li>

                    <li><label class="radio-inline">
                            <input type="radio" name="employeeId" id="inlineRadio1" value="fullTime" > Full-Time 
                        </label></li>

                    <li><label class="radio-inline">
                            <input type="radio" name="employeeId" id="inlineRadio1" value="partTime" > Part-Time
                        </label></li>

                    <li><label class="radio-inline">
                            <input type="radio" name="employeeId" id="inlineRadio1" value="contractual" > Contractual
                        </label></li>

                    <div class="clearfix"></div>
                </ul>
            </div>



            <button type="submit" name="search_btn" class="btn btn-primary ctgry_dtls_submit">Search</button>
        </div>
</form>  
<div class="col-xs-12 col-sm-9 col-md-9">
    <div class="ctgry_dtls_header_full">
        <div class="col-xs-12 col-sm-7 col-md-7 ctgry_dtls_header_left">            
            <p><span class="ctgry_dtls_total_job">[ test: id: <?php echo $id; ?> ] 1-50 of 69222</span> <span class="ctgry_dtls_job_ctgory"> Information-technology</span>   Jobs</p>
        </div>
        <div class="col-xs-12 col-sm-5 col-md-5 no_right_padding ctgry_dtls_sort_icon">
            <ul>
                <li class="sort_short_li"><img src="<?php echo $this->basePath('/images/ctgry_dtls_sort_short_icon.jpg'); ?>" alt="details icon" class="ctgry_dtls_short_icon" /></li>
                <li class="sort_dtls_li"><img src="<?php echo $this->basePath('/images/ctgry_dtls_sort_dtls_icon.jpg'); ?>" alt="details icon" class="ctgry_dtls_long_icon" /></li>

            </ul>
        </div>
        <div class="clearfix"></div>
    </div>

    <!-- End of ctgry_dtls_header_full -->
    <?php foreach ($this->paginator as $catDetail): ?>
        <div class="ctgry_dtls_job_each_container">
            <div class="col-xs-12 col-sm-8 col-md-8 no_padding_left">
                <h3 class="dtls_job_title"><a href="/job/show/<?php echo $catDetail['id']; ?>"><?php echo $catDetail['job_title']; ?></a></h3>
                <h4 class="dtls_company_name">Symantic Software Company ltd</h4>
                <p class="dtls_experience">8-13 yrs</p> 
                <p class="dtls_company_location">Dhaka</p>
            </div>
            <div class="col-xs-12 col-sm-4 col-md-4 no_right_padding">
                <a href="#"> <img src="<?php echo $this->basePath('/images/job_dtls_company_logo.jpg'); ?>" alt="company_logo" class="job_dtls_company_logo"></a> 
            </div>
            <div class="clearfix"></div>

            <div class="ctgry_dtls_keyskill_des_container">

                <div class="col-xs-6 col-sm-3 col-md-3 no_padding_left no_right_padding">
                    <p class="ctgry_dtls_keyskill">Keyskills:</p>  
                </div>
                <div class="col-xs-6 col-sm-9 col-md-9 no_padding_left">
                    <p class="ctgry_dtls_keyskill">OSB, Oracle SOA, 11G, Fusion, BR, BPEL, Weblogic Server, Project Analysis...</p>  
                </div>


                <div class="col-xs-6 col-sm-3 col-md-3 no_padding_left">
                    <p class="ctgry_dtls_keyskill">Job Description:</p>  
                </div>
                <div class="col-xs-6 col-sm-9 col-md-9 no_padding_left">
                    <p class="ctgry_dtls_keyskill"> Role: Customer Support  Experience  : 6Months to 1 Year  Location: Chennai     1
                        EXCELLENT COMMUNICATION SKILLS (written and verbal) required 2	Facilitates
                        and/or provides end-user support for staff across Customer-hosted ...</p>  
                </div>
                <div class="clearfix"></div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12 dtls_save_full_container">        
                <div class="col-xs-3 col-sm-1 col-md-1 dtls_save_sprtr">
                    <a href="#"><img src="/images/dtls_saved_jobs_icon.png" alt="saved jobs"></a>
                </div>
                <div class="col-xs-3 col-sm-4 col-md-4 dtls_save_sprtr">
                    <p>Total job opening's:<span class="dtls_total_job"> 3 </span></p>
                </div>
                <div class="col-xs-3 col-sm-4 col-md-4">
                    <p>jobs posted:<span class="dtls_date_posted_job"> 1 </span> day ago </p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
        <!-- End of ctgry_dtls_job_each_container -->
    <?php endforeach; ?>


    <div class="common_google_ads">            
        <img src="<?php echo $this->basePath('/images/ctgry_dtls_ad_728_90.jpg'); ?>" alt="middle ad" class="img-responsive" />           
    </div>

    <div class="col-xs-12 col-sm-5 col-md-5 no_padding_left ctgry_dtls_job_per_page">
        <p>Jobs per page </p> 
        <select class="form-control">
            <option>1</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
            <option>5</option>
        </select> 
    </div>


    <div class="col-xs-12 col-sm-5 col-md-5 pull-right no_right_padding">
        <!--<div class="pagination">
            <nav>
                <ul class="pagination"> 
                    <li> <a href="#" aria-label="Previous"><span aria-hidden="true">«</span></a> </li>
                    <li class="active">
                        <span>1 <span class="sr-only">(current)</span></span>
                    </li>                    
                    <li> <a href="#"><span>2</span></a> </li>                    
                    <li>
                        <a href="#"> <span>3</span></a>
                    </li>                    
                    <li>
                        <a href="#"><span>4</span></a>
                    </li>                    
                    <li>
                        <a href="#"><span>5</span></a>
                    </li>                      
                    <li><a href="#" aria-label="Next"><span aria-hidden="true">»</span></a></li>


                </ul>
            </nav>  
        </div>-->
        <?php
// add at the end of the file after the table
        echo $this->paginationControl(
                // the paginator object
                $this->paginator,
                // the scrolling style
                'sliding',
                // the partial to use to render the control
                'partial/paginator.phtml', array('params' => $params)
        );
        ?>
    </div>
    <!-- End of Pagination -->

</div>
</div>

<script>
    $(document).ready(function() {
        $('.category_select_click').click(function() {
        event.preventdefault();
        }); 
        
        $('.sort_short_li img').click(function(){
    switch (this.id){

    case 'ctgry_dtls_short_icon':
            $('.ctgry_dtls_keyskill_des_container').hide();
            $('.sort_dtls_li').removeClass('active');
            $('.sort_short_li').addClass('active');
            break;
            
            default:
            $('.ctgry_dtls_keyskill_des_container').show();
            $('.sort_short_li').removeClass('active');
            $('.sort_dtls_li').addClass('active');
    }

    });
    
    
    
    
            $('.functional_area_search').click(function() {
    $('.industry_list, .job_level_list, .education_list, .employer_list, .job_type_list').hide();
            $('.functional_area_list').slideToggle(function() {
    var listItem = $('.functional_area_list').css('display');
            if (listItem === "block") {
    $('.functional_area_search').css('background', 'url(../images/ctgry_dtls_drop_icon_down.jpg) no-repeat left 15px');
    } else {
    $('.functional_area_search').css('background', 'url(../images/ctgry_dtls_drop_icon.jpg) no-repeat left 15px');
    }
    });
    });
            $('.industry_type_search').click(function() {
    $('.functional_area_list, .job_level_list, .education_list, .employer_list, .job_type_list').hide();
            $('.industry_list').slideToggle(function() {
    var listItem = $('.industry_list').css('display');
            if (listItem === "block") {
    $('.industry_type_search').css('background', 'url(../images/ctgry_dtls_drop_icon_down.jpg) no-repeat left 15px');
    } else {
    $('.industry_type_search').css('background', 'url(../images/ctgry_dtls_drop_icon.jpg) no-repeat left 15px');
    }
    });
    });
            $('.job_level_search').click(function() {
    $('.functional_area_list,.industry_list, .education_list, .employer_list, .job_type_list').hide();
            $('.job_level_list').slideToggle(function() {
    var listItem = $('.job_level_list').css('display');
            if (listItem === "block") {
    $('.job_level_search').css('background', 'url(../images/ctgry_dtls_drop_icon_down.jpg) no-repeat left 15px');
    } else {
    $('.job_level_search').css('background', 'url(../images/ctgry_dtls_drop_icon.jpg) no-repeat left 15px');
    }
    });
    });
            $('.by_education_search').click(function() {
    $('.functional_area_list, .job_level_list, .industry_list, .employer_list, .job_type_list').hide();
            $('.education_list').slideToggle(function() {
    var listItem = $('.education_list').css('display');
            if (listItem === "block") {
    $('.by_education_search').css('background', 'url(../images/ctgry_dtls_drop_icon_down.jpg) no-repeat left 15px');
    } else {
    $('.by_education_search').css('background', 'url(../images/ctgry_dtls_drop_icon.jpg) no-repeat left 15px');
    }
    });
    });
            $('.by_employer_search').click(function() {
    $('.functional_area_list, .job_level_list, .industry_list, .education_list, .job_type_list').hide();
            $('.employer_list').slideToggle(function() {
    var listItem = $('.employee_list').css('display');
            if (listItem === "block") {
    $('.by_employee_search').css('background', 'url(../images/ctgry_dtls_drop_icon_down.jpg) no-repeat left 15px');
    } else {
    $('.by_employee_search').css('background', 'url(../images/ctgry_dtls_drop_icon.jpg) no-repeat left 15px');
    }
    });
    });
            $('.job_type').click(function() {
    $('.functional_area_list, .job_level_list, .industry_list, .education_list, .employer_list').hide();
            $('.job_type_list').slideToggle(function() {
    var listItem = $('.job_type_list').css('display');
            if (listItem === "block") {
    $('.job_type').css('background', 'url(../images/ctgry_dtls_drop_icon_down.jpg) no-repeat left 15px');
    } else {
    $('.job_type').css('background', 'url(../images/ctgry_dtls_drop_icon.jpg) no-repeat left 15px');
    }
    });
    });
            //Remove margin bottom from last item
            $('.dtls_save_full_container').eq(9).css('margin-bottom', '0');


</script>