<div class="col-xs-12 col-sm-12 col-md-12 job_by_role_container">
    <div class="col-xs-12 col-sm-12 col-md-12 no_padding_left pagination_top_container">
        <ul>
            <li><a href="">Home</a></li>
            <li>roles</li>           
            <div class="clearfix"></div>
        </ul>        
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12 no_padding_left total_jobs_by_role">
        <h2>Jobs By Role</h2>
        <p>
            This page is an overview of jobs by role. Click on the job roles below to see related jobs based on your specific criteria.
            For more customized job search options, use our expanded <a href="/advancesearch">job search</a> page.
        </p>

        <div class="list_full_container">
<?php   foreach($departments as $department=>$roles){?>
            <div class="col-xs-12 col-sm-4 col-md-4 no_padding_left">
                <div class="list_item_container">
                    <h4><?php echo $department;?></h4>
                    <ul>
<?php               foreach($roles as $role){?>
                        <li><a href="#"><?php echo $role['name'];?> <span class="total_job">()</span></a></li>
<?php               }?>
                    </ul>
                </div>
            </div>
<?php   }?>
            <p class="view_all_roles"><a href="#">View All Roles</a></p>
        </div>
        <div class="clearfix"></div>
    </div>
</div>