<div class="hidden-xs common_google_ads t1-position-ad">   
    <!-- /85406138/Chakri_About-Policy-Terms_T1_970x90 -->
    <div id='div-gpt-ad-1444720035828-0'>
        <script type='text/javascript'>
            googletag.cmd.push(function() {
                googletag.display('div-gpt-ad-1444720035828-0');
            });
        </script>
    </div>    
</div>

<div class="col-xs-12 col-sm-12 col-md-12 about_us_page_container special_page_for_ad">
    <div class="pagination_top_container">
        <ul>
            <li><a href="/">Home</a></li>
            <li><?php echo $page['title']; ?></li>           
            <div class="clearfix"></div>
        </ul>        
    </div>

    <div class="row">

        <div class="col-md-7">
            <h2><?php echo $page['title']; ?></h2>
            <?php echo $page['content']; ?>
        </div>

        <div class="col-md-5 about_right_ad_container pull-right">
            <div class="hidden-xs common_google_ads no_top_margin">
                <!-- /85406138/Chakri_About-Policy-Terms_R1_336x280 -->
                <div id='div-gpt-ad-1444720195570-0' style='height:280px; width:336px;'>
                    <script type='text/javascript'>
                        googletag.cmd.push(function() {
                            googletag.display('div-gpt-ad-1444720195570-0');
                        });
                    </script>
                </div>
            </div>

            <div class="hidden-xs common_google_ads">               
                <!-- /85406138/Chakri_About-Policy-Terms_F1_300x600 -->
                <div id='div-gpt-ad-1444720239236-0' style='height:600px; width:300px;'>
                    <script type='text/javascript'>
                        googletag.cmd.push(function() {
                            googletag.display('div-gpt-ad-1444720239236-0');
                        });
                    </script>
                </div>                
            </div>
        </div>
    </div>
</div>