<div class="hidden-xs col-sm-12 col-md-12 common_google_ads t1-position-ad">
    <div class="row"> 
        <!-- /85406138/Chakri_About-Policy-Terms_T1_970x90 -->
        <div id='div-gpt-ad-1444720035828-0'>
            <script type='text/javascript'>
                googletag.cmd.push(function() {
                    googletag.display('div-gpt-ad-1444720035828-0');
                });
            </script>
        </div>
    </div> <!-- End of Row-->
</div>

<div class="col-xs-12 col-sm-12 col-md-12 about_us_page_container service_container">
    <a href="/"> <img src="/images/chakri.png" class="center-block service_logo"></a>
    <div class="clearfix"></div>
    <div class="col-xs-12 col-sm-12 col-md-12 service_content">
        <div class="row panel_body">
            <div class="col-md-6 service_panel_left">
                <div class="panel panel-default service_panel_box_shadow">
                    <div class="panel-heading"><strong>Spot-light jobs Announcement service</strong></div>
                    <div class="panel-body">
                        <p>Feature of Spotlight Jobs Announcement of Chakri.coms –</p>
                        <p>This is the premium job announcement service of <a href="http://www.chakri.com">www.Chakri.com</a>. This service is designed for organizations that would like to promote their respective organization to the prospective employees and also would like to make their job announcement stand out from hundreds of job announcements published at the site. </p>
                        <p>Basic Features of the service</p>
                        <p>• Organization logo and name displayed at the home/front page of <a href="http://www.chakri.com">www.Chakri.com</a> (for 20 days, under Spotlight Jobs title at the home page)</p>
                        <p>• The name of the job positions will be linked with a job detail page which will be custom designed (with company logo, slogan etc.) for the organization. This job details page can contain detail job announcement description, requirements, responsibilities, salary etc. and instructions to apply. It can also contain a brief description of the organization. To view the sample, please visit <a href="http://www.chakri.com">www.Chakri.com</a>.</p>
                        <p>• The particular job vacancy announcement published as the Spotlight Announcement will also be displayed at the respective Category/Classified job display section of <a href="http://www.chakri.com">www.Chakri.com</a> (for maximum 30 days).</p>
                        <p>• Employers will be able to receive job applications through online (either e-mail or at online account of the employer) or traditional methods (currier, mail, FAX etc.). If the employer chooses to receive CVs/Application online at its online account of <a href="http://www.chakri.com">www.Chakri.com</a>, the employer will be able to exclusively view, scrutinize and print applications/resumes through online advanced Application Management System.</p>
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <tr>
                                    <th>No of Designation</th>
                                    <th>Current Price</th>
                                    <th>Proposed price</th>
                                    <th>Increase in %</th>
                                    <th>Bdjobs Price</th>
                                </tr>
                                <tr>
                                    <td>For One Designation</td>
                                    <td>4,000</td>
                                    <td>67,000</td>
                                    <td>&nbsp;</td>
                                    <td>9,000</td>
                                </tr>
                                <tr>
                                    <td>For Two Designation</td>
                                    <td>4,000 each</td>
                                    <td>5,000 each</td>
                                    <td>25%</td>
                                    <td>6,250</td>
                                </tr>
                                <tr>
                                    <td>For 3- 4 Designation</td>
                                    <td>3,600 each</td>
                                    <td>4,2500 each</td>
                                    <td>25%</td>
                                    <td>5,000</td>
                                </tr>
                                <tr>
                                    <td>For 5 and above</td>
                                    <td>3,400 each</td>
                                    <td>34,8000 each</td>
                                    <td>20%</td>
                                    <td>4,250</td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="col-xs-4 col-sm-4 col-md-4 package_mb_btn_order"> 
                                <div class="form-group">                   
                                    <input type="submit" value="Order" class="btn package_btn">
                                </div>
                            </div>
                            <div class="col-xs-8 col-sm-8 col-md-8"> 
                                <div class="form-group">                   
                                    <input type="submit" value="Register and Order" class="btn package_btn">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 service_panel_right">
                <div class="panel panel-default service_panel_box_shadow" >
                    <div class="panel-heading"><strong>Feature of Classified/Category Section of <a href="http://www.chakri.com">www.Chakri.com</a></strong></div>
                    <div class="panel-body package_feature">
                        <p>Employers/Recruiters can announce job vacancy announcement at the category/classified pages of www.chakri.com through this service. Posting a job vacancy announcement at www.chakri.com is very simple. What the employers need to do is – just log on to www.chakri.com and creates an online account of the organization and then post the job vacancy announcement under the company account. As soon as the vacancy gets posted at www.chakri.com, the job becomes searchable by the job seekers.</p>
                        <p>Basic Features of the service </strong></p>
                        <p>• The announced/posted job vacancies will be displayed (for max. 30 days) under job display pages (linked with home page) of any particular category (chosen by the employer at the time of job posting) at <a href="http://www.chakri.com">www.chakri.com</a>.</p>
                        <p>• Employers will be able to receive job applications through online (either e-mail or at online account of the employer) or traditional methods (courier, mail, FAX etc.)</strong></p>
                        <p>• If the employer chooses to receive CVs/Application online at its online account of <a href="http://www.chakri.com"><strong>www.chakri.com</strong></a>, the employer will be able to exclusively view, scrutinize and print applications/resumes through online advanced Application Management System.</p>
                        <div class="clearfix"></div>
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <tr>
                                    <th>No of Designation</th>
                                    <th>Current Price</th>
                                    <th>Proposed price</th>
                                    <th>Increase in %</th>
                                    <th>Bdjobs Price</th>
                                </tr>
                                <tr>
                                    <td>For One Designation</td>
                                    <td>1,500</td>
                                    <td>2,000</td>
                                    <td>20%</td>
                                    <td>2,300</td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="col-xs-4 col-sm-4 col-md-4 package_mb_btn_order"> 
                                <div class="form-group">                   
                                    <input type="submit" value="Order" class="btn package_btn">
                                </div>
                            </div>
                            <div class="col-xs-8 col-sm-8 col-md-8"> 
                                <div class="form-group">                   
                                    <input type="submit" value="Register and Order" class="btn package_btn">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row panel_body row_top_padding">
            <div class="col-md-6 service_panel_left">
                <div class="panel panel-default service_panel_box_shadow">
                    <div class="panel-heading"><strong>Membership Packages (RM1):</strong></div>
                    <div class="panel-body">
                        <p>RM 1 Targeted to Single business units –Under this package company can post their jobs at category listing as many as needed through 12 months. Here company has an account with chakri.com and can post their jobs through the account. Company can receive the application at their account and will be able to shortlist candidates from here. Company will be able to post job by using only one name not multiple names.</p>
                        <p>Basic Features of regular membership 1 are  – </p>
                        <ul>
                            <li>Job  posting options as many as needed for 12 months. </li>
                            <li>Company will  receive application directly from their employer accounts. </li>
                            <li>Company can  be traced, short-listed, rejected, rate candidates (received) resumes.</li>
                            <li>Company can be announced 4  Spotlight job in this package.</li>
                        </ul>
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <tr>
                                    <th>Duration</th>
                                    <th>Job Posting Limit</th>
                                    <th>Fee</th>
                                    <th>Free Spotlights</th>
                                </tr>
                                <tr>
                                    <td>One year</td>
                                    <td>Unlimited</td>
                                    <td>50,000</td>
                                    <td>4</td>
                                </tr>
                                <tr>
                                    <td>Six Months</td>
                                    <td>30</td>
                                    <td>30,000</td>
                                    <td>2</td>
                                </tr>
                                <tr>
                                    <td>Three Months</td>
                                    <td>10</td>
                                    <td>15,000</td>
                                    <td>0</td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="col-xs-4 col-sm-4 col-md-4 package_mb_btn_order"> 
                                <div class="form-group">                   
                                    <input type="submit" value="Order" class="btn package_btn">
                                </div>
                            </div>
                            <div class="col-xs-8 col-sm-8 col-md-8"> 
                                <div class="form-group">                   
                                    <input type="submit" value="Register and Order" class="btn package_btn">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 service_panel_right">
                <div class="panel panel-default service_panel_box_shadow">
                    <div class="panel-heading"><strong>RM 2 Targeted to Group of companies (Max 3 business units)–</strong></div>
                    <div class="panel-body package_rm2">
                        <p>Basic under this package company can use  three individual concern accounts for posting jobs. Company can post their jobs  at category listing as many as needed throughout the year from three accounts.  Here company have an accounts with chakri.com and can post their jobs through  the account. Company can receive the applications at their accounts and also  will be able to shortlist candidates from here. Features of regular membership  2 are – </p>
                        <ul type="disc">
                            <li>Job posting       options as many as needed for 12 months. </li>
                            <li>Company will       get 3 individual account access including group account. </li>
                            <li>Company will       receive applications directly at their employer accounts. </li>
                            <li>Company can       be traced, short-listed, rejected, rate candidates (received) resumes </li>
                            <li>Company can       be announced 8 spot-light jobs in this package. </li>
                        </ul>
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <tr>
                                    <th>Duration</th>
                                    <th>Job Posting Limit</th>
                                    <th>Fee</th>
                                    <th>Free Spotlights</th>
                                </tr>
                                <tr>
                                    <td>One year</td>
                                    <td>Unlimited</td>
                                    <td>70,000</td>
                                    <td>8</td>
                                </tr>
                                <tr>
                                    <td>Six Months</td>
                                    <td>40</td>
                                    <td>40,000</td>
                                    <td>4</td>
                                </tr>
                                <tr>
                                    <td>Three Months</td>
                                    <td>17</td>
                                    <td>25,000</td>
                                    <td>0</td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="col-xs-4 col-sm-4 col-md-4 package_mb_btn_order"> 
                                <div class="form-group">                   
                                    <input type="submit" value="Order" class="btn package_btn">
                                </div>
                            </div>
                            <div class="col-xs-8 col-sm-8 col-md-8"> 
                                <div class="form-group">                   
                                    <input type="submit" value="Register and Order" class="btn package_btn">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row panel_body row_top_padding">
            <div class="col-md-6 service_panel_left">
                <div class="panel panel-default service_panel_box_shadow">
                    <div class="panel-heading"><strong>Gold Membership 1(Single) (with the Access in CV Bank):</strong></div>
                    <div class="panel-body package_gm1">
                        <p>Basic Under this package company can post their jobs at category listing as many needed through the 12 month and also can access CV data bank access for next 12 month. Company able to post job in using only one name not multiple name. fFeatures of goldFull membership 1 are–</p>
                        <ul>
                            <li>
                                Job posting options as many as needed for 12 months.
                            </li>
                            <li>
                                Company will get the access in CV data bank.
                            </li>
                            <li>
                                Company will receive application directly at their employer accounts.
                            </li>
                            <li>
                                Company can be traced, short-listed, rejected, rate candidates (received) resumes.
                            </li>
                            <li>Company can be announced 68 spot-light jobs in this package.</li>
                        </ul>
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <tr>
                                    <th>Duration</th>
                                    <th>Job Posting Limit</th>
                                    <th>Fee</th>
                                    <th>Free Spotlights</th>
                                </tr>
                                <tr>
                                    <td>One year</td>
                                    <td>Unlimited</td>
                                    <td>70,000</td>
                                    <td>6</td>
                                </tr>
                                <tr>
                                    <td>Six Months</td>
                                    <td>30</td>
                                    <td>45,000</td>
                                    <td>3</td>
                                </tr>
                                <tr>
                                    <td>Three Months</td>
                                    <td>10</td>
                                    <td>25,000</td>
                                    <td>0</td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="col-xs-4 col-sm-4 col-md-4 package_mb_btn_order"> 
                                <div class="form-group">                   
                                    <input type="submit" value="Order" class="btn package_btn">
                                </div>
                            </div>
                            <div class="col-xs-8 col-sm-8 col-md-8"> 
                                <div class="form-group">                   
                                    <input type="submit" value="Register and Order" class="btn package_btn">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 service_panel_right">
                <div class="panel panel-default service_panel_box_shadow">
                    <div class="panel-heading"><strong>GM Membership 2 (Group) (with the Access  in CV Bank) – </strong></div>
                    <div class="panel-body">
                        <p>Basic Under this package company can use three individual concern accounts for posting jobs. Company can post their jobs at category listing as many as needed throughout the year both three accounts. Also will get the access in CV data bank for 12 months but only for one account or mother account. Here company have an account with chakri.com and can post their jobs through the account. Company can receive the applications at their accounts and also will be able to shortlist candidates here. fFeatures of fFull membership 2 are –</p>
                        <ul>
                            <li>
                                Job posting options as many as needed for 12 months.
                            </li>
                            <li>
                                Company will get 3 individual account access including group account.
                            </li>
                            <li>
                                Company will get the access in CV data bank in mother account.
                            </li>
                            <li>
                                Company will receive applications directly at their employer accounts.
                            </li>
                            <li>
                                Company can be traced, short-listed, rejected, rate candidates (received) resumes.
                            </li>
                            <li>
                                Company can be announced 8 spot-light jobs in this package.
                            </li>
                        </ul>
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <tr>
                                    <th>Duration</th>
                                    <th>Job Posting Limit</th>
                                    <th>Fee</th>
                                    <th>Free Spotlights</th>
                                </tr>
                                <tr>
                                    <td>One year</td>
                                    <td>Unlimited</td>
                                    <td>90,000</td>
                                    <td>8</td>
                                </tr>
                                <tr>
                                    <td>Six Months</td>
                                    <td>40</td>
                                    <td>50,000</td>
                                    <td>4</td>
                                </tr>
                                <tr>
                                    <td>Three Months</td>
                                    <td>17</td>
                                    <td>30,000</td>
                                    <td>0</td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="col-xs-4 col-sm-4 col-md-4 package_mb_btn_order"> 
                                <div class="form-group">                   
                                    <input type="submit" value="Order" class="btn package_btn">
                                </div>
                            </div>
                            <div class="col-xs-8 col-sm-8 col-md-8"> 
                                <div class="form-group">                   
                                    <input type="submit" value="Register and Order" class="btn package_btn">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row panel_body row_top_padding">
            <div class="col-md-6 service_panel_left">
                <div class="panel panel-default service_panel_box_shadow">
                    <div class="panel-heading"><strong>Platinum Membership 1</strong></div>
                    <div class="panel-body package_cv">
                        <p>PM 1 single business unit – 100,000/= for 12 months unlimited category jobs, access in &nbsp;CV data bank, logo at the top employer panel for branding and also the link service for the company website. Features of platinum Top membership 1 are &nbsp;–</p>
                        <ul>
                            <li>
                                Job posting options as many as needed for 12 months.
                            </li>
                            <li>
                                Company will get the access in CV data bank access.
                            </li>
                            <li>
                                Company can be traced, short-listed, rejected, rate candidates (received) resumes.
                            </li>
                            <li>
                                Company can be announced 12 spot-light jobs in this package.
                            </li>
                            <li>
                                Company will have their logo at Employer zone.
                            </li>
                            <li>
                                Company can be used their website link at the home page.
                            </li>
                        </ul>
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="col-xs-4 col-sm-4 col-md-4 package_mb_btn_order"> 
                                <div class="form-group">                   
                                    <input type="submit" value="Order" class="btn package_btn">
                                </div>
                            </div>
                            <div class="col-xs-8 col-sm-8 col-md-8"> 
                                <div class="form-group">                   
                                    <input type="submit" value="Register and Order" class="btn package_btn">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 service_panel_right">
                <div class="panel panel-default service_panel_box_shadow">
                    <div class="panel-heading"><strong>Platinum Membership 2 </strong></div>
                    <div class="panel-body">
                        <p>Platinum  Membership 2 &nbsp;(Group) &nbsp;– 120,000/= for 12 months unlimited category  jobs for three individual account, access in &nbsp;CV data bank access in the  mother account, logo at the top employer panel for branding and also the link  service for the company website. Features of platinumTop membership 21 are  &nbsp;–</p>
                        <ul>
                            <li>Job posting  options as many as needed for 12 months. </li>
                            <li>Company will  get 3 individual account access including group account. </li>
                            <li>Company will  get the access in CV data bank in mother account. </li>
                            <li>Company can  receive applications directly at their employer accounts. </li>
                            <li>Company can  trace, short-list, reject, rate candidate (received) resumes. </li>
                            <li>Company can  also announce 12 spot-light jobs in this package. </li>
                            <li>Company can  have their logo at Employer zone. </li>
                            <li>Company can  also have their website link at the home page </li>
                        </ul>
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="col-xs-4 col-sm-4 col-md-4 package_mb_btn_order"> 
                                <div class="form-group">                   
                                    <input type="submit" value="Order" class="btn package_btn">
                                </div>
                            </div>
                            <div class="col-xs-8 col-sm-8 col-md-8"> 
                                <div class="form-group">                   
                                    <input type="submit" value="Register and Order" class="btn package_btn">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row panel_body row_top_padding">
            <div class="col-md-12 service_panel_left">
                <div class="panel panel-default service_panel_box_shadow">
                    <div class="panel-heading"><strong>CV Bank Access Membership –</strong></div>
                    <div class="panel-body package_cv">
                        <p>This service enables an employer to  search any CV from chakri.com's online CV bank (More than 300,000 CVs of  qualified professionals are currently hosted at the CV Bank). CVs can be  searched by using any single or multiple search criterion (e.g. no. of years of  experience, professional category/sub-category, education etc.) or keywords.</p>
                        <p><strong>Online CV Bank Access</strong></p>
                        <div align="center" class="package_cv_heading"><strong>1 month packages</strong></div>
                        <table class="table table-bordered">
                            <tr>
                                <td align="center" valign="top"><strong>CV Search Limit</strong></td>
                                <td align="center" valign="top"><strong>Package Price (Tk.)</strong></td>
                            </tr>
                            <tr>
                                <td align="center" valign="top">1,000</td>
                                <td align="center" valign="top">Tk. 3,000</td>
                            </tr>
                            <tr>
                                <td align="center" valign="top">2,500 </td>
                                <td align="center" valign="top">Tk. 6,250</td>
                            </tr>
                        </table>
                        <div align="center" class="package_cv_heading"><strong>3 months packages</strong></div>
                        <table class="table table-bordered">
                            <tr>
                                <td width="140" align="center" valign="top"><strong>CV Search Limit</strong></td>
                                <td width="162" align="center" valign="top"><strong>Package Price (Tk.)</strong></td>
                            </tr>
                            <tr>
                                <td align="center" valign="top">1,000 </td>
                                <td align="center" valign="top">Tk. 6,000 (6 TK per CV)</td>
                            </tr>
                            <tr>
                                <td align="center" valign="top">2,500 </td>
                                <td align="center" valign="top">Tk. 12500 (5 TK per CV)</td>
                            </tr>
                            <tr>
                                <td align="center" valign="top">5,000</td>
                                <td align="center" valign="top">Tk. 15000(3 TK per CV)</td>
                            </tr>
                        </table>
                        <div align="center" class="package_cv_heading"><strong>6 months packages</strong></div>
                        <table class="table table-bordered">
                            <tr>
                                <td width="154" align="center" valign="top"><strong>CV Search Limit</strong></td>
                                <td width="174" align="center" valign="top"><strong>Package Price (Tk.)</strong></td>
                            </tr>
                            <tr>
                                <td align="center" valign="top">2,500</td>
                                <td align="center" valign="top">Tk. 15000 (6 TK per CV)</td>
                            </tr>
                            <tr>
                                <td align="center" valign="top">5,000</td>
                                <td align="center" valign="top">Tk. 20d000 (4 TK per CV)</td>
                            </tr>
                            <tr>
                                <td align="center" valign="top">10,000 </td>
                                <td align="center" valign="top">Tk. 25000 (2.5 TK per CV)</td>
                            </tr>
                        </table>
                        <div align="center" class="package_cv_heading"><strong>12 months packages</strong></div>
                        <table class="table table-bordered">
                            <tr>
                                <td width="144" align="center" valign="top"><strong>CV Search Limit</strong></td>
                                <td width="166" align="center" valign="top"><strong>Package Price (Tk.)</strong></td>
                            </tr>
                            <tr>
                                <td align="center" valign="top">5,000</td>
                                <td align="center" valign="top">Tk. 20000 (4 TK per CV)</td>
                            </tr>
                            <tr>
                                <td align="center" valign="top">10,000 </td>
                                <td align="center" valign="top">Tk. 30,000 (3 TK per CV)</td>
                            </tr>
                        </table>

                        <div class="col-xs-12 col-sm-12 col-md-12" align="center" package_mb_btn_order> 
                            <div class="form-group">                   
                                <input type="submit" value="Order" class="btn package_btn">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
